### PR TITLE
Player Model

### PR DESCRIPTION
**Pull request by agshaidun**
Credit JDeu

### CODE REVIEW

**Comment by rosesware** [comment]
Just need to put a option "default" to play without any different model.

**Comment by agshaidun** [comment]
Sorry i can't make the PullRequest bcs already delete this repo

**Comment by giangero1** [comment]
good fuck ing jooob mate , ur legend we wanted this in osiris for a while.

**Comment by danielkrupinski** [comment]
Thank you!

**Comment by rosesware** [comment]
@danielkrupinski If you can put the "Default" option, I would appreciate it, me and lots of peps.

**Pull request merged**
