### PR TITLE
Dead ESP

### PR DESCRIPTION
**Pull request by ZerGo0**
Enables the ESP when you're dead. ESP itself doesn't need to be enabled obviously.

### CODE REVIEW

**Comment by Shaxzy** [comment]
Awesome! Thank you

**Comment by agshaidun** [comment]
🤩🤩🤩

**Comment by danielkrupinski** [comment]
Is it supposed to apply only to Player ESP? If so you should move `deadesp` field from Shared to the Player struct.

**Comment by ZerGo0** [comment]
> Is it supposed to apply only to Player ESP? If so you should move `deadesp` field from Shared to the Player struct.

Done, didn't even notice that. ^^

**Comment by danielkrupinski** [comment]
Thanks!

**Pull request merged**
