### PR TITLE
AddCircleImageFilled() + Upgrade Osiris Detection

### PR DESCRIPTION
**Pull request by techzin**
A simple Circle Image pasted from another imgui.
VMP is an away to make cheat more undetectable.
XorStr is an string encrypt at compile time, the best in my opinion, you can use to make cheat more undetectable and more secure against crack.

If you want you can add xorstr_("your string") to all strings to protect them.

### CODE REVIEW

**Comment by 3Ld4D** [comment]
What's the point of xorstr when it's public.

**Comment by techzin** [comment]
> What's the point of xorstr when it's public.
sorry if it was unnecessary, i just wanted to try to help the way i know.

**Comment by wemanzoz** [comment]
:thonk:

**Comment by mkot2** [comment]
> 
> 
> What's the point of xorstr when it's public.

LWSS fuzion uses xorstr and its public too

**Comment by wemanzoz** [comment]
@techzin how can i add this to my build, do i need to add the .lib file aswell? orr

**Comment by techzin** [comment]
@wemanzoz  add VMP path to Project Properties -> C++ Directories -> Lib Path

**Comment by cristeigabriel** [comment]
If an anticheat cared to look for strings, they wouldn't look solely at .rdata, they'd have the ability to be intrusive and make pages they read have EXECUTE_READWRITE permissions and access the contents of what's pushed as an argument if it's valid, as an example, or simply go over .data at runtime if the access pointers are valid.

**Comment by wemanzoz** [comment]
> @wemanzoz add VMP path to Project Properties -> C++ Directories -> Lib Path

can i have ur discord? i have some questions

**Comment by techzin** [comment]
> > @wemanzoz add VMP path to Project Properties -> C++ Directories -> Lib Path
> 
> can i have ur discord? i have some questions

Yeah, my nick: TechZiN#7640

**Comment by techzin** [comment]
> Se um anticheat se preocupasse em procurar strings, eles não olhariam apenas para .rdata, eles teriam a capacidade de ser intrusivos e fazer com que as páginas lidas tivessem permissões EXECUTE_READWRITE e acessassem o conteúdo do que é enviado como um argumento se for válido como exemplo, ou simplesmente examine .data em tempo de execução se os ponteiros de acesso forem válidos.

Some friends have told me before, that xorstr helps change signature (in theory), this could help since the VAC detects most cheats free, because of signatures.

**Comment by 3Ld4D** [comment]
> > Se um anticheat se preocupasse em procurar strings, eles não olhariam apenas para .rdata, eles teriam a capacidade de ser intrusivos e fazer com que as páginas lidas tivessem permissões EXECUTE_READWRITE e acessassem o conteúdo do que é enviado como um argumento se for válido como exemplo, ou simplesmente examine .data em tempo de execução se os ponteiros de acesso forem válidos.
> 
> Some friends have told me before, that xorstr helps change signature (in theory), this could help since the VAC detects most cheats free, because of signatures.

No, it only changes strings to random numbers. They get unhashed on runtime.

**Comment by cristeigabriel** [comment]
> 
> 
> > Se um anticheat se preocupasse em procurar strings, eles não olhariam apenas para .rdata, eles teriam a capacidade de ser intrusivos e fazer com que as páginas lidas tivessem permissões EXECUTE_READWRITE e acessassem o conteúdo do que é enviado como um argumento se for válido como exemplo, ou simplesmente examine .data em tempo de execução se os ponteiros de acesso forem válidos.
> 
> Some friends have told me before, that xorstr helps change signature (in theory), this could help since the VAC detects most cheats free, because of signatures.

I mean, it does change the signature because it adds more instructions to be executed to unhash the string at runtime, whereas the result is inlined in place from being processed at compiletime, but that doesn't make sense to do whatsoever. Anywho if they were to sig shit, they'd look into more important stuff, you'd be better using a lazy importer for API methods, or changing optimization settings, or using alternative compilers, etc.

**Comment by Shuvi-Moro** [comment]
https://i.imgur.com/vznDEJR.png
I don't understand where my mistake is...

**Comment by 3Ld4D** [comment]
@Shuvi-Moro you are building it as x64

**Comment by JukoiDev** [comment]
Build as x86

**Pull request closed without merging**
