### PR TITLE
Added Friendly Fire/Kills/Grief Counter

### PR DESCRIPTION
**Pull request by noteffex**
Basically logs how many kills your team mates and you are on.
Helps grief/not get grieved.
In action:
https://youtu.be/z5mhgFVTS2o

### CODE REVIEW

**Comment by Evilhelder** [comment]
Question:

Do you move the window from place?

or makes it more transparent?

**Comment by effex1337** [comment]
> Question:
> 
> Do you move the window from place?
> 
> or makes it more transparent?

Not sure what u meant but you can move it around.

**Comment by streamshark** [comment]
looks good, I think evil was trying to ask if he can adjust window transparency of the box to see through it while playing

**Comment by ClaudiuHKS** [comment]
Nice, but @danielkrupinski uses **MultiByteToWideChar** right after **GetPlayerInfo** for player names.

**Comment by Evilhelder** [comment]
> 
> 
> looks good, I think evil was trying to ask if he can adjust window transparency of the box to see through it while playing

exactly

**Comment by Evilhelder** [comment]
BUG: after switching sides it shows all players ..

image

**Comment by xAkiraMiura** [comment]
When somebody leaves and another person takes their index then the new person would probably inherit the previous values.

Wasn't the point of this checking how close someone was to getting kicked? I think it would be a lot more useful to know that Bot Gabe is 70 damage away from getting kicked rather than knowning that I did 30 to Bot Gabe and 80 to Bot Jon.

**Comment by steel4me** [comment]
Uhh, nice, are you interested to implement more? For example, showing matchmaking competetive wins of players. report / commend buttons behind colums and in future it could be the base for priority aimbot / trigger specific settings ;) 

Just some ideas.

**Comment by AbdallahMehiz** [comment]
can this Gui be used with the spectator list?
image
would be a good thing to change for the spec list

**Comment by xBaTm4n** [comment]
I have this problem: "Misc.cpp(30,40): error C2109: subscript requires array or pointer type"

**Comment by danielkrupinski** [comment]
Misc::griefingBox() is not thread-safe and will cause crashes if engine simultaneously invalidates entity while we're using it. See https://github.com/danielkrupinski/GOESP/blob/70100d09a06ec33ead2531ea9f974ef0bc025a0a/GOESP/Hacks/Misc.cpp#L114 to understand how to make it stable.

**Comment by CerberusGame** [comment]
https://prnt.sc/rymobq
I how to fix ?

**Comment by Evilhelder** [comment]
FIX pls :( I BEG YOU. D:

**Comment by braken1** [comment]
> can this Gui be used with the spectator list?
> image
> would be a good thing to change for the spec list

would be cool

**Pull request closed without merging**
