### PR TITLE
StatTrak fix

### PR DESCRIPTION
**Pull request by blackMasterLord**
Checking if we are adding StatTrak to the correct weapon.😎

### CODE REVIEW

**Review by danielkrupinski — COMMENTED** [review]
Please rebase your branch to the latest master.

**Comment by blackMasterLord** [comment]
> Please rebase your branch to the latest master.

🤔
image
I don't know much about working with GitHub.
Soooo.

**Comment by floydGG** [comment]
What this fix does?

**Comment by blackMasterLord** [comment]
> What this fix does?

https://github.com/danielkrupinski/Osiris/pull/3175#issue-705886730

**Pull request closed without merging**
