### PR TITLE
Complementary Edits

### PR DESCRIPTION
**Pull request by hamad12a**

### CODE REVIEW

**Comment by fanat1cc** [comment]
could you add standalone rcs and rcs settings to this so i only have to add this to my Osiris and not add 3 different pull requests

**Comment by hamad12a** [comment]
@fanat1cc Do you have the source code for RCS?

**Comment by TabuWare** [comment]
can confirm your fov code works wonders! any shot you can fix rcs from flippin all over the place (without randomization)

**Comment by fanat1cc** [comment]
> @fanat1cc Do you have the source code for RCS?

not sure if this will still work for how old it is but
https://github.com/danielkrupinski/Osiris/pull/2135

**Comment by wirekuro** [comment]
@hamad12a  Could you update the extended backtrack?

**Comment by wirekuro** [comment]
@hamad12a Can you help please? dc: howtozuhn#1222

**Comment by hamad12a** [comment]
> @hamad12a Could you update the extended backtrack?

Hey, sorry for the delayed reply.
By the way, I am not the owner of the extended backtrack nor I am an expert in this hack, except I tried some edits from what I understood so far in Osiris code structure not from what I know how things work frankly. Being busy these days, though, I will notify you if I edited something. 
Don't feel helpless, you could try things too as all of us started!
Take a look on previous commits and discussion. Pull requests provide also hints on the code.

**Comment by wirekuro** [comment]
> > @hamad12a Could you update the extended backtrack?
> 
> @wirekuro Hey, sorry for the delayed reply. By the way, I am not the owner of the extended backtrack nor I am an expert in this hack, except I tried some edits from what I understood so far in Osiris code structure not from what I know how things work frankly. Being busy these days, though, I will notify you if I edited something. Don't feel helpless, you could try things too as all of us started! Take a look on previous commits and discussion. Pull requests provide also hints on the code.

I have fixed 99% of it, there's 1 error I can't solve.
Please reach me out on Discord: howtozuhn#1222

**Comment by wirekuro** [comment]
> > @hamad12a Could you update the extended backtrack?
> 
> @wirekuro Hey, sorry for the delayed reply. By the way, I am not the owner of the extended backtrack nor I am an expert in this hack, except I tried some edits from what I understood so far in Osiris code structure not from what I know how things work frankly. Being busy these days, though, I will notify you if I edited something. Don't feel helpless, you could try things too as all of us started! Take a look on previous commits and discussion. Pull requests provide also hints on the code.

@hamad12a 
I have fixed 99% of it, there's 1 error I can't solve.
Please reach me out on Discord: howtozuhn#1222

**Pull request closed without merging**
