### PR TITLE
Triggerbot max inaccuracy, Human Bhop, and Aimbot FOV Circles

### PR DESCRIPTION
**Pull request by Vonr**
i would split it into individual prs but my monkey brain decided to push to my all branch.

### CODE REVIEW

**Comment by Vonr** [comment]
Human Bhop and Aimbot FOV are from other people btw I just made them work for the latest osiris update and changed human bhop

**Comment by Cyk-Fad** [comment]
Draw Aimbot FOV isn't working for me!

**Comment by Vonr** [comment]
works perfectly fine for me did you turn it on its in misc

**Comment by Slacky145** [comment]
How to download the stuff you changed?

**Comment by killzone559pl** [comment]
drawAimbotFov in misc.cpp don't work for me

**Comment by killzone559pl** [comment]
Could you please add color picker to this? Or it's too hard, you can just tell how to do this

**Comment by Vonr** [comment]
change these lines 
```
interfaces->surface->setDrawColor(255, 10, 10, 255); 
else interfaces->surface->setDrawColor(10, 255, 10, 255)```
to use variables instead of it shardcoded integers then make them appear in the gui as sliders by editing the respective files

**Comment by killzone559pl** [comment]
Thanks, but i have a problem with variables, i don't have idea how to use it. I tried to use it from bomb timer and change some thing but with errors. Thanks anyway.

**Comment by aceyx3** [comment]
How do I put these into work? Thank you!

**Comment by techprimedev** [comment]
Works!!

**Comment by aceyx3** [comment]
How do I put it together? Can someone help me?! Please.

**Comment by andreimerfu** [comment]
Works flawless! Thank you @Vonr 👍

**Comment by aceyx3** [comment]
> Works flawless! Thank you @Vonr 👍

Hey man, how do I put it together? Been trying to get the human bhop working, but it doesnt work, after i turn it on the misc, please help me!

**Comment by aceyx3** [comment]
Human bhop doesnt give me a slider, how do I fix this?

**Comment by aceyx3** [comment]
Can someone help me with the bhop thing? Being trying to make it work for 2 days now. :'(

**Comment by andreimerfu** [comment]
@aceyx3 Honestly I didn't test the human bhop, only the aim inaccuracy. I'll test the bhop and I'll come back with feedback.

**Comment by andreimerfu** [comment]
@aceyx3 Nope, the bunny hop doesn't work for me. @Vonr do you have a fix for this issue?

**Comment by Vonr** [comment]
it works fine as long as your max hops isnt 0

**Comment by Vonr** [comment]
and honestly that makes sense

**Comment by Vonr** [comment]
set max hops to like 7 or 8, min hops to 0 and chance to 60 or 70

**Comment by andreimerfu** [comment]
Yea, that make sens. Thank you @Vonr ! It works.

**Comment by ekstazas** [comment]
I tried adding in the draw fov to the newest osiris build, but get these 3 errors:
https://imgur.com/a/kOGNBOm

any fix/update?

**Comment by Zvonda1337** [comment]
@ekstazas  check the misc update

**Comment by TheFuryPT** [comment]
Doesn´t work, need fix

**Comment by stacylol** [comment]
@ekstazas @TheFuryPT to fix GetLocalPlayer issues
1) Go to Engine.h
2) Go to lines 53-end and locate "class Engine" (VIRTUAL_METHOD...)
3) Paste this line between anywhere around it
    [[deprecated]] VIRTUAL_METHOD(int, getLocalPlayer, 12, (), (this))
it should fix the problem

**Comment by stacylol** [comment]
How do you update the Max Aim Accuracy for the triggerbot? It doesn't work my way, does anyone have a type of source/example I can paste in?

**Comment by flowxrc** [comment]
Draw Aimbot Fov isnt working

**Comment by wemanzoz** [comment]
draw aimbot fov is broken lmfao

**Pull request closed without merging**
