### PR TITLE
Jump check for aimbot and triggerbot

### PR DESCRIPTION
**Pull request by newcommerdontblame**
1 line of code for not being too obvious with aimbot and not spamming in air with triggerbot

### CODE REVIEW

**Comment by Khajiitos** [comment]
In my opinion it's better to just implement an inaccuracy check for triggerbot like aimbot has

**Comment by newcommerdontblame** [comment]
> In my opinion it's better to just implement an inaccuracy check for triggerbot like aimbot has

there is triggerbot hitchance on my main too but its just for lplayer onground check that most of cheats has. Personally im using it for all weapons except ssg

**Comment by newcommerdontblame** [comment]
also i think u will miss that shoot due to spread even if u on %90 hitchance. It's just pr that u can add if u want or no :))

**Comment by dayz2000** [comment]
cant save load config

**Pull request closed without merging**
