### PR TITLE
Ragdoll/Dead chams

### PR DESCRIPTION
**Pull request by KisSsArt**
image

### CODE REVIEW

**Comment by nikita-tarasov3** [comment]
Good idea!

**Comment by KisSsArt** [comment]
that's not my idea. i just did it: https://github.com/danielkrupinski/Osiris/issues/2655

**Comment by ZokyChecks** [comment]
nice, thx!)

**Comment by ZokyChecks** [comment]
but it works only for 1 enemy(

**Comment by 3Ld4D** [comment]
This won't work, not all entities get passed thru DME.

**Comment by KisSsArt** [comment]
Бе123123зымянный

**Comment by KisSsArt** [comment]
> This won't work, not all entities get passed thru DME.


do you know how I can fix this? <3

**Comment by KisSsArt** [comment]
> This won't work, not all entities get passed thru DME.


and why is it bad

**Comment by KisSsArt** [comment]
> but it works only for 1 enemy(

please show a screenshot

**Comment by 3Ld4D** [comment]
> > This won't work, not all entities get passed thru DME.
> 
> do you know how I can fix this? <3

you need to hook/spoof `r_drawothermodels` and make it 2.

https://www.unknowncheats.me/forum/counterstrike-global-offensive/366471-dme-weapon-chams.html

**Comment by ZokyChecks** [comment]
image

**Comment by 0suddenly0** [comment]
You need to hook r_drawmodelstatsoverlay and return true on the desired _ReturnAddress.

**Pull request closed without merging**
