### PR TITLE
Fix GameUI::createCommandMsgBox() index

### PR DESCRIPTION
**Pull request by mdilai**
Issue #3077

### CODE REVIEW

**Comment by wemanzoz** [comment]
how can i make a popup when i  injected my osiris?

**Comment by mdilai** [comment]
@wemanzoz It just

`interfaces->gameUI->createCommandMsgBox("Title of messagebox", "Content of messagebox");`
Call it when and where you want to get a popup.

**Review by danielkrupinski — COMMENTED** [review]
Is it correct for both Windows and Linux?

**Comment by mdilai** [comment]
@danielkrupinski Yep, works perfect on Linux too with same offset.

**Review by danielkrupinski — APPROVED** [review]

**Comment by danielkrupinski** [comment]
Thanks!

**Pull request merged**
