### PR TITLE
VAMOS

### PR DESCRIPTION
**Pull request by SuperK2-OS**
ouch!

### CODE REVIEW

**Comment by wemanzoz** [comment]
wtf is this

**Comment by Scui1** [comment]
@danielkrupinski can you ban this guy from the repo please?

**Comment by techzin** [comment]
A Paster learns to use Github pull requests.

**Comment by notgoodusename** [comment]
@SuperK2-OS Abriste una pull request sin querer, podes cerrarla pls?

**Comment by techzin** [comment]
> @SuperK2-OS Abriste una pull request sin querer, podes cerrarla pls?

lol

**Comment by wemanzoz** [comment]
bruh, dont need to make pull for this, make your own repo for "osiris translated to spanish"

**Comment by mkot2** [comment]
can you stop already bro nobody cares

**Comment by wemanzoz** [comment]
> @SuperK2-OS Abriste una pull request sin querer, podes cerrarla pls?

oh shit @notgoodusename you are alive, have discord?

**Pull request closed without merging**
