### PR TITLE
Aspect ratio changer (stretch changer)

### PR DESCRIPTION
**Pull request by Straightplus**
as title says^^
ive been using it for a good while now so i thought it was time to give it away without bugs :)

### CODE REVIEW

**Comment by danielkrupinski** [comment]
Your branch has conflicts with origin.

**Comment by rosesware** [comment]
> Your branch has conflicts with origin.

I approve this pull request.

**Comment by MinecraftGoodGame** [comment]
https://imgur.com/a/K8wcH4W

**Comment by Straightplus** [comment]
lmao

**Comment by Straightplus** [comment]
Fixed it @danielkrupinski sorry he :)

**Comment by danielkrupinski** [comment]
I thinks better method would be to hook `CEngineClient::GetScreenAspectRatio(int,int)` function (index 101).

**Comment by Straightplus** [comment]
maybe that would make it easyer to a degree, hmm maybe?

**Comment by notgoodusename** [comment]
hey! why did you remove misc::slowwalk?

**Comment by xAkiraMiura** [comment]
they probably opened their branch over 10 days ago (when slowwalk was opened)
if you checked the commits none of them removed slow walk

**Comment by Straightplus** [comment]
i didnt? @notgoodusename

**Comment by giangero1** [comment]
@Straightplus Thanks for almost making me puke i'm still dizzy from it if u put it at 5 it's pure canc.... xd 
i guarantee you there are gonna be ton of people puking from testing out the feature.

**Comment by danielkrupinski** [comment]
Thank you!

**Comment by Straightplus** [comment]
Sure :D

**Pull request merged**
