### PR TITLE
AA on nade fix

### PR DESCRIPTION
**Pull request by effex1337**

### CODE REVIEW

**Comment by effex1337** [comment]
Video Proof : https://youtu.be/nbBrSDhDOW0
Nothing other than the game was captured but at first i threw a nade without the fix then uncommented the fix then threw the nade again.

**Comment by l0ccy** [comment]
is this aslo fixing the angle fail if someone specs you? ^^

**Comment by effex1337** [comment]
This only fixes the throw.

**Comment by Kron1Q** [comment]
@effex1337 how you injected 2nd time after unhooking?

**Comment by effex1337** [comment]
You can do it with mmap injection.

**Comment by Kron1Q** [comment]
@effex1337 wow. Didnt expected that manual mapping will normally unhook .dll while loadlibrarya couldnt. Strange, anyway thank you <3

**Comment by BlackmanWhite** [comment]
Damn why is this not getting pushed

**Comment by effex1337** [comment]
Debug and send ss.
Also why i literally recirded a vid with it.

**Comment by T4zzuu** [comment]
Please...
`
bool isInThrow() noexcept
{
	return !m_bPinPulled() && m_fThrowTime() > 0;
}
`

**Comment by Leeon123** [comment]
So where is the conflict code?

**Comment by 3L337-n2** [comment]
So where is the conflict code?

**Comment by 3L337-n2** [comment]
check activeweapon before call m_bPinPulled can fix the conflict.

**Comment by agshaidun** [comment]
its not working again. after the update

**Comment by Faysal1969** [comment]
it works thank you

**Pull request closed without merging**
