### PR TITLE
Close menu on Escape key

### PR DESCRIPTION
**Pull request by qualterz**
A more convenient way to close the menu

### CODE REVIEW

**Comment by wemanzoz** [comment]
why

**Comment by qualterz** [comment]
> 
> 
> why

I think it will improve usability

**Comment by wemanzoz** [comment]
> > 
> > 
> > why
> 
> I think it will improve usability

i mean u can bind it to del or pgdn or pgup

**Comment by mkot2** [comment]
you can change the keybind in config, also almost every cheat has the menu key on insert and nobody has a problem with it

**Comment by qualterz** [comment]
Closing a popup menu with the Escape key is more intuitive than using a different key on the other side of the keyboard, especially when setting up a config for the first time. It is just good UX practice

**Comment by mkot2** [comment]
> 
> 
> Closing a popup menu with the Escape key is more intuitive than using a different key on the other side of the keyboard, especially when setting up a config for the first time. It is just good UX practice

the first time user should read the getting started section in which it clearly states "menu key is INSERT", why should there be two different keys, also again almost every cheat does this too

**Comment by OTGCable** [comment]
surely you're aware that the escape key is also the cs:go pause button, correct?
the entire idea behind using the escape/del/insert/home keys is to use keys that are not in use by the game.

**Comment by qualterz** [comment]
> surely you're aware that the escape key is also the cs:go pause button, correct?
> the entire idea behind using the escape/del/insert/home keys is to use keys that are not in use by the game.

Yes, but in the context of a menu, the Escape key should mean closing it
I may not understand the philosophy of cheats, but from UX point of view, it is more convenient

**Comment by qualterz** [comment]
> > Closing a popup menu with the Escape key is more intuitive than using a different key on the other side of the keyboard, especially when setting up a config for the first time. It is just good UX practice
> 
> the first time user should read the getting started section in which it clearly states "menu key is INSERT", why should there be two different keys, also again almost every cheat does this too

The Insert key to toggle the menu, Escape key to close it. The Escape key is optional, but for some users it will be useful

**Comment by R3nzTheCodeGOD** [comment]
Might be the most useless feature I've ever seen

**Comment by Asviix** [comment]
Useless or not, let the man train his coding and share what HE thinks is useful to HIM
stop hating and just be thankful he shares his work.

**Review by techzin — APPROVED** [review]
Yeah, can put on source.

**Comment by techzin** [comment]
> Might be the most useless feature I've ever seen

I believe that the reason for an IT, to use windows so fast, is because it knows how to take useless shortcuts that others do not know.

CTRL + SHIFT + ESC

**Comment by techzin** [comment]
This makes it simpler, I think the distance from the esc button is smaller than Insert.

**Comment by techzin** [comment]
@qualterz  I imagine a little problem in theory, if ESC is now included in keycode list, then will the hotkey also understand ESC as a key, or as a cancel?

**Comment by qualterz** [comment]
> 
> 
> @qualterz I imagine a little problem in theory, if ESC is now included in keycode list, then will the hotkey also understand ESC as a key, or as a cancel?

It is a problem that it is not understood as a cancel action. The Escape key bind is out of context for the menu, so it will close the menu and discard uncommitted changes such as key bind or value change

**Comment by Metaphysical1** [comment]
thanks, I hope you catch syphlis

**Pull request closed without merging**
