### PR TITLE
Force Crosshair

### PR DESCRIPTION
**Pull request by xpossed-you**
worked the same way as `noscopeCrosshair` but with all weapon instead of sniper

thanks to https://github.com/KernCS for helping me removing the default crosshair

### CODE REVIEW

**Comment by wirekuro** [comment]
> worked the same way as `noscopeCrosshair` but with all weapon instead of sniper
> 
> thanks to https://github.com/KernCS for helping me removing the default crosshair

good but forcing game crosshair would be a lot cooler

**Comment by mkot2** [comment]
> 
> 
> > worked the same way as `noscopeCrosshair` but with all weapon instead of sniper
> > thanks to https://github.com/KernCS for helping me removing the default crosshair
> 
> good but forcing game crosshair would be a lot cooler
> 
> *EDIT: isn't good because it doesn't hide when you scope with sniper.

`static auto nsVar = interfaces->cvar->findVar("weapon_debug_spread_show");
nsVar->setValue(3);
`

ez force game crosshair

**Comment by danielkrupinski** [comment]
When it is useful?

**Comment by xpossed-you** [comment]
> When it is useful?

not useful, just for fun hehe

**Comment by xpossed-you** [comment]
> When it is useful?

shit my bad

**Comment by Flow512** [comment]
this would work too
static auto crosshair = interfaces->cvar->findVar("weapon_debug_spread_show");

    crosshair->setValue(0);

    if (!config->misc.noscopeCrosshair)
        return;

    if (!localPlayer || !localPlayer->isAlive())
        return;



    crosshair->setValue(3);

    if (!localPlayer || localPlayer->isScoped())
    {
        crosshair->setValue(0);
    }

    else if (!localPlayer || !localPlayer->isScoped())
    {
        crosshair->setValue(3);
    }

**Comment by cristeigabriel** [comment]
```        pattern_names_and_bytes.emplace_back(
          "crosshair_shoulddraw",
          pattern_scan(client, { 0x55, 0x8B, 0xEC, 0x83, 0xE4, 0xF8, 0x83, 0xEC, 0x3C, 0x56, 0x8B, 0xF1, 0xE8, -1, -1, -1, -1 }));
```

**Pull request closed without merging**
