### PR TITLE
Added Ammo Bar to Player ESP, resized bar width, moved health text above the healthbar

### PR DESCRIPTION
**Pull request by Oly-UK**
Simple ammo bar esp, useful for pushing when they are low ammo. Also made the health, armor and ammo bar smaller, personal preference, you can enlarge them as you please.
_if anyone can make this horizontal i would be very grateful :)_

Video: 
https://streamable.com/385hhg

### CODE REVIEW

**Comment by Oly-UK** [comment]
@danielkrupinski if you could check this out that'd be awesome :)

**Comment by Oly-UK** [comment]
the newest commit: 
image

**Comment by notgoodusename** [comment]
clean look

**Comment by Oly-UK** [comment]
> clean look

ty

**Comment by Araptois** [comment]
Hi Oly-UK,

I know this is not the place to ask you this, but do you think you'd be able to do a Head Level Indicator like in these pictures? :

https://prnt.sc/rww0x0
https://prnt.sc/rww1f6

I have already made the request but it hasn't been answered, if you think you know how to do it, it would be super nice of you to do it

Have a nice day

**Comment by Oly-UK** [comment]
> Hi Oly-UK,
> 
> I know this is not the place to ask you this, but do you think you'd be able to do a Head Level Indicator like in these pictures? :
> 
> https://prnt.sc/rww0x0
> https://prnt.sc/rww1f6
> 
> I have already made the request but it hasn't been answered, if you think you know how to do it, it would be super nice of you to do it
> 
> Have a nice day

never really looked into it, i'll give it a go

**Comment by Araptois** [comment]
> 
> 
> > Hi Oly-UK,
> > I know this is not the place to ask you this, but do you think you'd be able to do a Head Level Indicator like in these pictures? :
> > https://prnt.sc/rww0x0
> > https://prnt.sc/rww1f6
> > I have already made the request but it hasn't been answered, if you think you know how to do it, it would be super nice of you to do it
> > Have a nice day
> 
> never really looked into it, i'll give it a go

Thank you very much, keep me posted

**Comment by moonm00n** [comment]
image
inspired by your ammo bar

**Comment by Oly-UK** [comment]
what? @moonm00n i dont see anything new

**Comment by moonm00n** [comment]
image
look at the bottom of the esp

**Comment by Oly-UK** [comment]
oh i see, i just assumed that was my pull request #1451 @wirebruh

**Comment by wirebruh** [comment]
interfaces->surface->drawFilledRect(bbox.x0, bbox.y1 + 5, bbox.x1 - abs(bbox.x1 - bbox.x0) * (iClip - iClipMax) / iClip, bbox.y1 + 7); my code if someone wants it

**Comment by Araptois** [comment]
> 
> 
> oh i see, i just assumed that was my pull request #1451 @wirebruh


Have you looked at the Head Level Indicator ? :p

**Comment by wirebruh** [comment]
> > oh i see, i just assumed that was my pull request #1451 @wirebruh
> 
> Have you looked at the Head Level Indicator ? :p

why did u quote me?

**Comment by danielkrupinski** [comment]
Sorry but I can't resolve merge conflicts because your branch has been deleted.

**Pull request closed without merging**
