### PR TITLE
Jump Bug

### PR DESCRIPTION
**Pull request by Vonr**

### CODE REVIEW

**Comment by Vonr** [comment]
quite buggy because doesnt use engine prediction

**Comment by littlehurensohn** [comment]
Not works.

**Comment by xAkiraMiura** [comment]
please use more descriptive commit names. im not reviewing this.

**Comment by AbdallahMehiz** [comment]
> please use more descriptive commit names. im not reviewing this.

its basically a bug that lets you not take fall damage and keeps your momentum after falling from certain hieights
check [bananagaming's video](https://www.youtube.com/watch?v=OEACZ63gpUQ) for more information

**Comment by MinecraftGoodGame** [comment]
bruh why do u define variables in the header

**Comment by xAkiraMiura** [comment]
> 
> 
> > please use more descriptive commit names. im not reviewing this.
> 
> its basically a bug that lets you not take fall damage and keeps your momentum after falling from certain hieights
> check [bananagaming's video](https://www.youtube.com/watch?v=OEACZ63gpUQ) for more information

i know what jump bug is, i ment like saying "add menu entry" instead of "commit p2"

**Comment by Vonr** [comment]
mate i could have squeezed it in one commit and youre complaining?

**Comment by danielkrupinski** [comment]
Please post a video of this in action. I couldn't confirm it works.

**Comment by littlehurensohn** [comment]
> Please post a video of this in action. I couldn't confirm it works.

I can confirm it doesnt works.

**Comment by Vonr** [comment]
might have broke something cleaning up the code but it should be easy to
remake. but its not even good so if someone could make it using cl_move
prediction that would be great

**Comment by tirziz** [comment]
Is it actually work ?

**Comment by Vonr** [comment]
apparently not but i dont have time to fix it right now and even if i did it wouldnt be perfect because it doesnt use engine prediction

**Comment by Vonr** [comment]
actually it should work. the only maybe useful code i cleaned up was the code to jump if very close to the ground and jb was not activating

**Comment by Vonr** [comment]
honestly i should just close this and wait for someone to do it properly with engine prediction

**Pull request closed without merging**
