### PR TITLE
Added Metallic and Pearlescent chams

### PR DESCRIPTION
**Pull request by playday3008**
by [sapphire](https://github.com/Sapphire1337420)
and [Mustafa](https://github.com/MustafaDaPro)

### CODE REVIEW

**Comment by playday3008** [comment]
Pearlescent
image

**Comment by playday3008** [comment]
Metallic
image

**Comment by playday3008** [comment]
I know
https://i.pinimg.com/564x/5a/ac/d4/5aacd4140462d64e88cb30273858510c.jpg

**Comment by notgoodusename** [comment]
1 step closer to osiris becoming looking even cooler,
Thanks!

**Comment by Cyk-Fad** [comment]
good job, Thanks

**Comment by aljawary** [comment]
Ss?

**Comment by aljawary** [comment]
looks dope similar with sk33t

**Comment by danielkrupinski** [comment]
Cool, thanks!

**Comment by newcommerdontblame** [comment]
Thats dope

**Comment by playday3008** [comment]
> Cool, thanks!
But "Pearlescent" these chams just ignore Alpha, idk why

**Comment by playday3008** [comment]
> Cool, thanks!

But "Pearlescent" chams just ignore Alpha, idk why
@danielkrupinski

**Pull request merged**
