### PR TITLE
Aimbot Hitchance

### PR DESCRIPTION
**Pull request by dapaster**
Sharing is caring

Credit @mdilai 
https://github.com/mdilai/JweegaCSGO

Preview: https://i.imgur.com/eth3DRu.png

### CODE REVIEW

**Comment by xAkiraMiura** [comment]
wouldn't having control over both the movement accuracy *and* the spread inaccuracy be more precise than just setting one?
^ i would prefer to have a checkbox to switch between the existing method and the new method; fine adjustment and course adjustment.

**Comment by streamshark** [comment]
the option to switch methods is also desirable for servers like dangerzone with lots of players where tons of hitchance rays lags like hell

**Comment by dapaster** [comment]
what should i do to this line ?

    if (config.aimbot[weaponIndex].enabled && (cmd->buttons & UserCmd::IN_ATTACK || config.aimbot[weaponIndex].autoShot || config.aimbot[weaponIndex].aimlock) && activeWeapon->getInaccuracy() <= config.aimbot[weaponIndex].maxAimInaccuracy)

and this

    if (config.aimbot[weaponIndex].autoShot && activeWeapon->nextPrimaryAttack() <= memory.globalVars->serverTime() && !clamped && activeWeapon->getInaccuracy() <= config.aimbot[weaponIndex].maxShotInaccuracy)
        cmd->buttons |= UserCmd::IN_ATTACK;

how do i make the switch 

and is this GUI.cpp correct?

    ImGui::Checkbox("Hit chance", &config.aimbot[currentWeapon].enablehitchance);
    if (config.aimbot[currentWeapon].enablehitchance)
    {
     ImGui::SliderInt("Hit chance", &config.aimbot[currentWeapon].hitchance, 0, 100, "%d");
    }
      if (!config.aimbot[currentWeapon].enablehitchance)
        {
        ImGui::PushID(3);
        ImGui::SliderFloat("Max aim inaccuracy", &config.aimbot[currentWeapon].maxAimInaccuracy, 0.0f, 1.0f, "%.5f", 2.0f);
        ImGui::SliderFloat("Max shot inaccuracy", &config.aimbot[currentWeapon].maxShotInaccuracy, 0.0f, 1.0f, "%.5f", 2.0f);
        ImGui::PopID();
        };
      if (config.aimbot[currentWeapon].enablehitchance)
        {
        ImGui::PushID(4);
        ImGui::SliderFloat("Max aim inaccuracy", &config.aimbot[currentWeapon].maxAimInaccuracy, 0.0f, 0.0f, "Disabled for Hit chance");
        ImGui::SliderFloat("Max shot inaccuracy", &config.aimbot[currentWeapon].maxShotInaccuracy, 0.0f, 0.0f, "Disabled for Hit chance");
        ImGui::PopID();
        };

**Comment by Cyk-Fad** [comment]
Thank you for you share, I add it in my osiris

**Pull request closed without merging**
