### PR TITLE
Rainbow hud

### PR DESCRIPTION
**Pull request by Khajiitos**
Useless but cool

**Showcase:**
hud

### CODE REVIEW

**Comment by newcommerdontblame** [comment]
Add crosshair tho

**Comment by Khajiitos** [comment]
> Add crosshair tho

I might do that tomorrow

**Comment by SapphireCodenz** [comment]
ss?

**Comment by bastquu** [comment]
cl_drawhud 0 and draw own hud, example https://imgur.com/Fz8x6g8

**Comment by Khajiitos** [comment]
> cl_drawhud 0 and draw own hud, example https://imgur.com/Fz8x6g8

Using this command you would have to draw every single hud element by yourself, including crosshair and radar.

**Comment by newcommerdontblame** [comment]
@Khajiitos bro it doesnt look smooth as crosshair pr also every color change makes radar flicking and it doesnt look that good 
Cant u use rgb instead of cvar currentcolor thing

**Comment by Khajiitos** [comment]
> @Khajiitos bro it doesnt look smooth as crosshair pr also every color change makes radar flicking and it doesnt look that good
> Cant u use rgb instead of cvar currentcolor thing

No, because there are no rgb cvars for hud, only 10 presets, and I'm pretty sure that the radar flicking issue is caused by the game itself and I don't think we can do anything about it

**Pull request closed without merging**
