### PR TITLE
Added Ammo to Weapon ESP

### PR DESCRIPTION
**Pull request by Oly-UK**
Taken from Daniel's "GOESP"
image

### CODE REVIEW

**Comment by CantRememberMyself** [comment]
cool thanks

**Comment by Oly-UK** [comment]
> cool thanks

:)

**Comment by Cyk-Fad** [comment]
I think we can add a reload time

**Comment by Cyk-Fad** [comment]
ammo reload

**Comment by Oly-UK** [comment]
what do you mean?

**Comment by AbdallahMehiz** [comment]
> I think we can add a reload time



> what do you mean?

i think he means the reload progress feature on GOESP

**Comment by Oly-UK** [comment]
> > I think we can add a reload time
> 
> > what do you mean?
> 
> i think he means the reload progress feature on GOESP

ok okay, i'll take a look

**Comment by Oly-UK** [comment]
i can't even see what it does @Cyk-Fad i just injected GOESP enabled it and reloaded and legit nothing is happening

**Comment by RyDeem** [comment]
Oly i think it shows when other people are reloading they reload progress, like bomb defusal timer.

**Comment by Oly-UK** [comment]
@RyDeem incorrect
"if (localPlayerData.inReload) {"

**Comment by Mistrz1337** [comment]
can you add ammo to player esp ?

**Comment by Oly-UK** [comment]
@Mistrz1337 i tried it and for some reason it just displays 0 / 0

**Comment by Mistrz1337** [comment]
> @Mistrz1337 i tried it and for some reason it just displays 0 / 0

for me too that's why i was asking

**Comment by Cyk-Fad** [comment]
@Oly-UK  My means we can add players ammoreload time

**Pull request closed without merging**
