### PR TITLE
Anti aim

### PR DESCRIPTION
**Pull request by notgoodusename**
Been testing it, people mag dump my fake

### CODE REVIEW

**Comment by AbdallahMehiz** [comment]
can u add fake chams for the aa?

**Comment by effex1337** [comment]
The thirdperson angle you see is invalid,  first accurate localplayer animation fix would be needed, then fake matrix anim fix is needed.

Hence desync chams isn't coming anytime soon.

**Comment by notgoodusename** [comment]
> The thirdperson angle you see is invalid, first accurate localplayer animation fix would be needed, then fake matrix anim fix is needed.
> 
> Hence desync chams isn't coming anytime soon.

you said you did it already but you dont want to share it

**Comment by effex1337** [comment]
Well ye i was just replying to the guy asking for desync chams.

**Comment by notgoodusename** [comment]
> Well ye i was just replying to the guy asking for desync chams.

ok, btw im trying to add fake chams. i dont think is necesary to make an accurate localplayer, u can just do the deadflag + 4 on sendpacket and it will show your real, and about the fake matrix i have no idea

**Comment by notgoodusename** [comment]
i am curious about something, fake old chams should work the same as desync chams, right?

**Comment by effex1337** [comment]
Technically yes.
You just need to get the fake matrix for dme.

But i think endscene chams were more common in past days.
Which is pretty much useless in the era of desync.

**Comment by notgoodusename** [comment]
i have this
`void Chams::renderDesync(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept 
{
    const auto localPlayer{ interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()) };
    auto applied{ false };
    matrix3x4* matrix;
    Vector nangle;
    AngleMatrix1(nangle, info.origin, matrix);
    ModelRenderInfo newinfo;
    newinfo = info;
    newinfo.modelToWorld = matrix;
    for (size_t i = 0; i < config.chams[DESYNC].materials.size(); i++) {
        if (applied){
            hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, newinfo, customBoneToWorld);
    }
        applyChams(config.chams[DESYNC].materials[i], false, localPlayer->health());
        applied = true;
    }

}`

**Comment by asraskmekaidasid** [comment]
indicator will not be better?

**Comment by giangero1** [comment]
@notgoodusename i pasted everything and then i have these errors and now my whole source is ruined help :(  i tried the feature on a new osiris source doesn't even work just want my source fixed :( 
image

**Comment by notgoodusename** [comment]
> @notgoodusename i pasted everything and then i have these errors and now my whole source is ruined help :( i tried the feature on a new osiris source doesn't even work just want my source fixed :(
> image
paste this into antiaim.h
#pragma once

struct UserCmd;
struct Vector;

namespace AntiAim {
	void run(UserCmd*, const Vector&, const Vector&, bool&) noexcept;
}

**Comment by giangero1** [comment]
image
@notgoodusename ty for answering

**Comment by giangero1** [comment]
@notgoodusename 
image my issue is in misc.obj why :(

**Comment by notgoodusename** [comment]
PASTE THE CODE IN antiaim.h
>struct UserCmd;
struct Vector;

namespace AntiAim {
void run(UserCmd*, const Vector&, const Vector&, bool&) noexcept;
}

**Comment by Straightplus** [comment]
aa doesent work on ladders

**Comment by giangero1** [comment]
image
image
****

**Comment by notgoodusename** [comment]
Use my newer slowwalk #917

**Comment by giangero1** [comment]
image
@notgoodusename  autoblocker

**Comment by Straightplus** [comment]
crashes when i try and join a game

**Comment by notgoodusename** [comment]
that cant happen, its a problem with your project

**Comment by Straightplus** [comment]
okay ill try do something

**Comment by Straightplus** [comment]
it was because i tried making a aa fix for nades

	auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	const auto activeWeapon = localPlayer->getActiveWeapon();
	if (config.antiAim.enabled && activeWeapon->getClientClass()->classId == ClassId::Knife
		|| activeWeapon->getClientClass()->classId == ClassId::BaseCSGrenadeProjectile
		|| activeWeapon->getClientClass()->classId == ClassId::BreachChargeProjectile
		|| activeWeapon->getClientClass()->classId == ClassId::BumpMineProjectile
		|| activeWeapon->getClientClass()->classId == ClassId::Knife
		|| activeWeapon->getClientClass()->classId == ClassId::MolotovProjectile
		|| activeWeapon->getClientClass()->classId == ClassId::SensorGrenadeProjectile
		|| activeWeapon->getClientClass()->classId == ClassId::SmokeGrenadeProjectile
		|| activeWeapon->getClientClass()->classId == ClassId::SnowballProjectile
		|| activeWeapon->getClientClass()->classId == ClassId::AmmoBox
		|| activeWeapon->getClientClass()->classId == ClassId::Cash) {

**Comment by linkupbiz** [comment]
> i have this
> ``void Chams::renderDesync(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept
> {
> const auto localPlayer{ interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()) };
> auto applied{ false };
> matrix3x4* matrix;
> Vector nangle;
> AngleMatrix1(nangle, info.origin, matrix);
> ModelRenderInfo newinfo;
> newinfo = info;
> newinfo.modelToWorld = matrix;
> for (size_t i = 0; i < config.chams[DESYNC].materials.size(); i++) {
> if (applied){
> hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, newinfo, customBoneToWorld);
> }
> applyChams(config.chams[DESYNC].materials[i], false, localPlayer->health());
> applied = true;
> }
> 
> }``

Do you have the def for AngleMatrix1?

**Comment by notgoodusename** [comment]
im not at home rn

**Comment by notgoodusename** [comment]
> > i have this
> > ``void Chams::renderDesync(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept
> > {
> > const auto localPlayer{ interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()) };
> > auto applied{ false };
> > matrix3x4* matrix;
> > Vector nangle;
> > AngleMatrix1(nangle, info.origin, matrix);
> > ModelRenderInfo newinfo;
> > newinfo = info;
> > newinfo.modelToWorld = matrix;
> > for (size_t i = 0; i < config.chams[DESYNC].materials.size(); i++) {
> > if (applied){
> > hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, newinfo, customBoneToWorld);
> > }
> > applyChams(config.chams[DESYNC].materials[i], false, localPlayer->health());
> > applied = true;
> > }
> > }``
> 
> Do you have the def for AngleMatrix1?
void MatrixSetColumn(Vector& in, int column, matrix3x4* out)
{
    out[0][column] = in.x;
    out[1][column] = in.y;
    out[2][column] = in.z;
}
void AngleMatrix(const Vector& angles, matrix3x4* matrix)
{
    Vector quakeEuler{ radiansToDegrees(angles.y), radiansToDegrees(angles.z), radiansToDegrees(angles.x) };

    AngleMatrix(quakeEuler, matrix);
}
void AngleMatrix1(const Vector& angles, Vector position, matrix3x4* matrix)
{
    AngleMatrix(angles, matrix);
    MatrixSetColumn(position, 3, matrix);
}
there

**Comment by Straightplus** [comment]
Maybe new pull request?

**Comment by Straightplus** [comment]
Iam getting this error if i try and paste it?
https://i.imgur.com/C7xFJwa.png

**Comment by asraskmekaidasid** [comment]
where add this anglematrix1?

**Comment by notgoodusename** [comment]
> Iam getting this error if i try and paste it?
> https://i.imgur.com/C7xFJwa.png

I didnt ment the code to be used

**Comment by Straightplus** [comment]
oh

**Comment by Straightplus** [comment]
i just added it to the chams and did the other things necessary
https://i.imgur.com/WRE6hjB.png

**Comment by notgoodusename** [comment]
you need another matrix

**Comment by Straightplus** [comment]
okay but it says the "out needs to be a modifiable value"
https://i.imgur.com/9KJeLiY.png

**Comment by notgoodusename** [comment]
Because matrix3x4 is constant

**Comment by Straightplus** [comment]
oh okay makes sense lmao

**Comment by Pateeesz** [comment]
> you need another matrix

Can you help me? Which matrix is good?

**Comment by asraskmekaidasid** [comment]
me too this got https://imgur.com/9KJeLiY, help

**Comment by githubuser-del** [comment]
Can you add fake chams please?

**Comment by asraskmekaidasid** [comment]
@Straightplus how you repair this https://imgur.com/9KJeLiY?

**Comment by Straightplus** [comment]
guys chill the fuck out

**Comment by Straightplus** [comment]
its under development still i think

**Comment by Straightplus** [comment]
i didnt? @asraskmekaidasid

**Comment by time21** [comment]
@notgoodusename i got the problem with oldangle.y
image

**Comment by agshaidun** [comment]
All good

**Comment by Straightplus** [comment]
did you define it? @time21 
	Vector oldangle = cmd->viewangles;

**Comment by time21** [comment]
> did you define it? @time21
> Vector oldangle = cmd->viewangles;

oh i didnt define it thanks.

**Comment by time21** [comment]
image
now i got this problem sad

**Comment by Pateeesz** [comment]
> image
> now i got this problem sad

bruh, read the first debug line on the pic

**Comment by Straightplus** [comment]
lol

**Comment by Straightplus** [comment]
and sure @time21

**Comment by GA9BR** [comment]
can we upload all AA files on github for me to download?

**Comment by GA9BR** [comment]
What do I have to do to update Osiris source without having to delete and download again?

**Comment by Straightplus** [comment]
update the offsets/indexes

**Comment by Straightplus** [comment]
or code if needed

**Comment by GA9BR** [comment]
i'm a begginer paster and i dont know how i do this

**Comment by Straightplus** [comment]
there is no new indexes yet?

**Comment by GA9BR** [comment]
I downloaded the notgoodusename source, but a new daniel source update came out so I want to know how do I update the notgoodousename source based on the Daniel update

**Comment by GA9BR** [comment]
notgoodusename did you add chams for AA ?

**Comment by rosesware** [comment]
> I downloaded the notgoodusename source, but a new daniel source update came out so I want to know how do I update the notgoodousename source based on the Daniel update

Manually.

**Comment by notgoodusename** [comment]
p walking https://streamable.com/29t9x

**Comment by Straightplus** [comment]
ahahaha

**Comment by streamshark** [comment]
> p walking https://streamable.com/29t9x

most P AA, literally unhittable

**Comment by xAkiraMiura** [comment]
how did you mess up the animations that much?

**Comment by notgoodusename** [comment]
1 function only

**Comment by igothxps** [comment]
@notgoodusename idk im using ur source and i cant get anyone to shoot my fake its always my real if you could provide setting please do

**Comment by notgoodusename** [comment]
> @notgoodusename idk im using ur source and i cant get anyone to shoot my fake its always my real if you could provide setting please do

are u chocking packets?

**Comment by igothxps** [comment]
@notgoodusename no im not

**Comment by notgoodusename** [comment]
> @notgoodusename no im not

well then, chocke packtes on misc atleast 1

**Comment by igothxps** [comment]
@notgoodusename do i need to bind it or is it on by default and what number do you recommend

**Comment by notgoodusename** [comment]
u dont have to bind it

**Comment by igothxps** [comment]
@notgoodusename still not working

**Comment by igothxps** [comment]
@notgoodusename nvm

**Comment by igothxps** [comment]
@notgoodusename also im being told by my friend im looking backwards like standard aa

**Comment by igothxps** [comment]
@notgoodusename yeah it flicks around like a mother fucker its no better than normal aa

**Comment by notgoodusename** [comment]
send a video, and whats your yaw angle?

**Comment by igothxps** [comment]
@notgoodusename its at the default 0.0 i believe https://streamable.com/shsid now for the third person it looks normal but to the demo and everyone else its doing that

**Comment by notgoodusename** [comment]
> @notgoodusename its at the default 0.0 i believe https://streamable.com/shsid now for the third person it looks normal but to the demo and everyone else its doing that

thanks for the feedback, the problem is that i dont know which angle do people see so i have to guess
whats your discord btw

**Comment by igothxps** [comment]
@notgoodusename Kaito#1827

**Comment by Straightplus** [comment]
@notgoodusename yo i have tried using the new aa and it seems like the pitch doesent work?
am i doing something wrong or?

**Comment by notgoodusename** [comment]
> yo @notgoodusename i have tried using the new aa and it seems like the pitch doesent work?
> am i doing something wrong or?
just checked and it is working

**Comment by Straightplus** [comment]
hmm

**Comment by Straightplus** [comment]
1 sec

**Comment by Straightplus** [comment]
csgo_stBXyyo47c

#include "AntiAim.h"
#include "../Interfaces.h"
#include "../SDK/Engine.h"
#include "../SDK/Entity.h"
#include "../SDK/EntityList.h"
#include "../SDK/NetworkChannel.h"
#include "../SDK/UserCmd.h"
#include "../Memory.h"
#include "../SDK/GlobalVars.h"
#include "Misc.h"

bool LbyBreaker()
{
	auto local_player = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	static float NextUpdate = 0;
	float velocity = local_player->velocity();
	float time = memory.globalVars->serverTime();
	if (!(local_player->flags() & 1) || (!(local_player->isAlive()))) {
		return false;
	}
	if (velocity > 0.1f) {
		NextUpdate = time + 0.22f;
	}
	if (NextUpdate <= time)
	{
		NextUpdate = time + 1.1f;
		return true;
	}

	return false;
}

void AntiAim::run(UserCmd* cmd, const Vector& previousViewAngles, const Vector& currentViewAngles, bool& sendPacket) noexcept
{
	float desync = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->getMaxDesyncAngle();
	auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	static float lastTime{ 0.0f };
	static bool invert;
	bool lby = LbyBreaker();
	int yaw = config.antiAim.yawangle;
	Vector oldangle = cmd->viewangles;
	float velocity = localPlayer->velocity().length();

	if (config.antiAim.enabled) {
		if (GetAsyncKeyState(config.antiAim.invertkey) && memory.globalVars->realtime - lastTime > 0.5f) {
			invert = !invert;
			lastTime = memory.globalVars->realtime;
		}

		auto weapon = localPlayer->getActiveWeapon();
		if (!weapon) {
			return;
		}

		auto weaponClass = getWeaponClass(weapon->itemDefinitionIndex2());
		if (weaponClass == 40) {
			if (!weapon->m_bPinPulled()) {
				float throwTime = weapon->m_fThrowTime();
				if (throwTime > 0.f)
					return;
			}

			if ((cmd->buttons & UserCmd::IN_ATTACK) || (cmd->buttons & UserCmd::IN_ATTACK2)) {
				if (weapon->m_fThrowTime() > 0.f)
					return;
			}
		}

		if (config.antiAim.pitch && cmd->viewangles.x == currentViewAngles.x) {
			cmd->viewangles.x = config.antiAim.pitchAngle;
		}

		if (config.antiAim.yaw) {
			if (lby) {
				sendPacket = false;
				invert ? cmd->viewangles.y -= 118.f : cmd->viewangles.y += 118.f;
			} else if (sendPacket) {
				if (velocity > 0.1f) {
					invert ? cmd->viewangles.y += yaw + desync : cmd->viewangles.y += yaw - desync;
				} else if (velocity < 0.1f) {
					invert ? cmd->viewangles.y += yaw + (desync * 2) : cmd->viewangles.y += yaw - (desync * 2);
				}
				} else {
				cmd->viewangles.y += yaw;
			}
		}
	}
	cmd->viewangles.normalize();
	Misc::fixMovement(cmd, oldangle.y);

	cmd->viewangles.x = std::clamp(cmd->viewangles.x, -89.0f, 89.0f);
	cmd->viewangles.y = std::clamp(cmd->viewangles.y, -180.0f, 180.0f);
	cmd->viewangles.z = 0.0f;
}

**Comment by GA9BR** [comment]
Bro is totality necessary add the fake chams 
 please and manual AA, is impossible use AA im matchmaking without fake chams

**Comment by rosesware** [comment]
> Bro is totality necessary add the fake chams
> please and manual AA, is impossible use AA im matchmaking without fake chams

Can all guys stop begging for a "fake chams", @notgoodusename already knows. **JUST WAIT**.

**Comment by xAkiraMiura** [comment]
you cant make fake chams when you have no fake 🤔

**Comment by notgoodusename** [comment]
> you cant make fake chams when you have no fake 🤔

u sure?

**Comment by xAkiraMiura** [comment]
considering the AA is yaw forward and the fake is on the real i doubt there is a fake.
also he just added bSendPacket to CreateMove i dont think there was a desync/fake in the old anti-aim

**Comment by notgoodusename** [comment]
> considering the AA is yaw forward and the fake is on the real i doubt there is a fake.
> also he just added bSendPacket to CreateMove i dont think there was a desync/fake in the old anti-aim

who added bSendPacket?

**Comment by GA9BR** [comment]
I know there is nothing here, about what I will ask but someone can fix a source for me, I do not know code and from what I saw is something simple 

https://www.sendspace.com/file/myx1pg

**Comment by xAkiraMiura** [comment]
That is completely unrelated to Osiris, let alone this issue.
Please go ask someone from where you downloaded that paste.

that paste probably doesnt even work anymore considering Antario is outdated.

**Comment by xAkiraMiura** [comment]
also all you skids, please stop trying to manually move the code from github into your local repo
just use `git clone https://github.com/notgoodusename/Osiris-1`

**Comment by rosesware** [comment]
> you cant make fake chams when you have no fake 🤔

I test the Anti Aim today with a mate and he even't see fakes, he just see a body yaw to his right.

**Comment by notgoodusename** [comment]
> > you cant make fake chams when you have no fake 🤔
> 
> I test the Anti Aim today with a mate and he even't see fakes, he just see a body yaw to his right.

bruh, thats because i didnt add a thirdperson fix

**Comment by xAkiraMiura** [comment]
@rosesware test if the yaw on your end differs from the yaw on their end.
if there is a difference then the AA is working (to some extent)
then check if the hitbox is at where you see or where they see 
^ if it is where your friend sees then the anti-aim failed.

also you dont "fix" thirdperson. you add a second model with chams to represent the desync. (your real shouldnt appear to be on the fake)

**Comment by anarbmw** [comment]
@notgoodusename can u add an indicator like an arrow or type LEFT RIGHT to show which side is fake and which side is real body

**Comment by notgoodusename** [comment]
> @notgoodusename can u add an indicator like an arrow or type LEFT RIGHT to show which side is fake and which side is real body

unless you always use 0 in yaw angle that would be useless

**Comment by rosesware** [comment]
> then check if the hitbox is at where you see or where they see

@xAkiraMiura It's really strange. So, my friend see my fake angle and I see the real angle (on my screen, in third person) , but when he shoot at my head in suppose to be "fake angles", he hits me anyways (in head, course). So resuming... The Anti Aim works, but not correctly **(I THINK)**.

> also you dont "fix" thirdperson. you add a second model with chams to represent the desync. (your real shouldnt appear to be on the fake)

Also I know that, but I don't really need this if I'm testing with a friend and hes sharing is screen. I literally know what hes seing, and where is the fake angle, and still not working, fakes is not working 'cause the fake angles it's a real angle (basically, it's just like doesn't have fake angles and you just have a option to put your yaw and pitch changed).  

**SORRY, IF I'M COMPLETELY WRONG.**

**Comment by notgoodusename** [comment]
thanks for feedback! yeah the code is wrong, i shouldnt check the velocity in antiaim::run and lby breaker doesnt work (no idea why it doesnt it did a few days ago) i just need to fix that

**Comment by effex1337** [comment]
Uhh ur 'desync' just makes ur realyaw go left and right. (with the tp fix)
Also u need to predict when ur lby updates b4hand and then u do stuff.
Now think how do u achieve desync.

**Comment by effex1337** [comment]
As a matter of fact someone paid me to do this
https://cdn.otaku.ooo/czsie.png
Hf

**Comment by notgoodusename** [comment]
> As a matter of fact someone paid me to do this
> https://cdn.otaku.ooo/czsie.png
> Hf

yeah, what are u doing to draw the model? i mean i tried sceneEnd chams but it keeps crashing, rotating a matrix is hard asf

**Comment by notgoodusename** [comment]
> Uhh ur 'desync' just makes ur realyaw go left and right. (with the tp fix)
> Also u need to predict when ur lby updates b4hand and then u do stuff.
> Now think how do u achieve desync.

did you check the code? i have an lbybreaker but for some reason it works when i +use or + attack

**Comment by effex1337** [comment]
> > Uhh ur 'desync' just makes ur realyaw go left and right. (with the tp fix)
> > Also u need to predict when ur lby updates b4hand and then u do stuff.
> > Now think how do u achieve desync.
> 
> did you check the code? i have an lbybreaker but for some reason it works when i +use or + attack

I didnt. I just tested ur code and my own lby breakers and stuff which gave me that result.

**Comment by notgoodusename** [comment]
i see that you dont want to share any information about your desync chams

**Comment by effex1337** [comment]
Alright
Some hints:
Sendpacket - angle
DME
Setangle
Restore angle.
That's literally it.

**Comment by notgoodusename** [comment]
> Alright
> Some hints:
> Sendpacket - angle
> DME
> Setangle
> Restore angle.
> That's literally it.

i did everything exept dme, i think i know what function you are talking about

**Comment by GA9BR** [comment]
> > Tudo bem 
> > Algumas dicas: 
> > Sendpacket - ângulo 
> > DME 
> > Setangle 
> > Restaurar ângulo. 
> > É literalmente isso.
> 
> eu fiz tudo, exceto dme, acho que sei de que função você está falando

can you add auto wall ?

**Comment by notgoodusename** [comment]
> > > Tudo bem
> > > Algumas dicas:
> > > Sendpacket - ângulo
> > > DME
> > > Setangle
> > > Restaurar ângulo.
> > > É literalmente isso.
> > 
> > 
> > eu fiz tudo, exceto dme, acho que sei de que função você está falando
> 
> can you add auto wall ?

there is already an auto wall

**Comment by notgoodusename** [comment]
> > > Tudo bem
> > > Algumas dicas:
> > > Sendpacket - ângulo
> > > DME
> > > Setangle
> > > Restaurar ângulo.
> > > É literalmente isso.
> > 
> > 
> > eu fiz tudo, exceto dme, acho que sei de que função você está falando
> 
> can you add auto wall ?

there is already an auto wall

**Comment by notgoodusename** [comment]
i got this lmao looks cool tho
https://streamable.com/ayiz7

**Comment by notgoodusename** [comment]
so im one step away from getting the chams, i have to render the model twice

**Comment by Straightplus** [comment]
very cool :D

**Comment by atk3001** [comment]
image

After adding all the stuff I get this Error. Can someone help me?

**Comment by notgoodusename** [comment]
> image
> 
> After adding all the stuff I get this Error. Can someone help me?

fixed

**Comment by notgoodusename** [comment]
Update: almost there! look at the shadows
https://streamable.com/ktvwo

**Comment by GA9BR** [comment]
> Update: almost there! look at the shadows
> https://streamable.com/ktvwo

nice bro

**Comment by xAkiraMiura** [comment]
could you explain to me why it takes 29 commits to make a simple aimbot and simple DME chams? all you do is override the material, none of this "drawing the model twice"?

ideally we would have implemented an aimbot, wait for it to get accepted, then make DME chams. doing it like you did increases your chance of getting declined as i forsee.

**Comment by streamshark** [comment]
> could you explain to me why it takes 29 commits to make a simple aimbot and simple DME chams? all you do is override the material, none of this "drawing the model twice"?
> 
> ideally we would have implemented an aimbot, wait for it to get accepted, then make DME chams. doing it like you did increases your chance of getting declined as i forsee.

do you mean antiaim instead of aimbot?

**Comment by notgoodusename** [comment]
because im not calling the original its not,
hooks.modelrender.calloriginal that would override the same model

**Comment by notgoodusename** [comment]
i think im overcomplicating the chams

**Comment by notgoodusename** [comment]
i got this, its not as easy as effex said from what i understood i should have a function that 
instantly sets the model angle so, i set the angle for the moment i need to render and after rendering i reset
`bool Chams::desync1(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept
{
    if (strstr(info.model->name, "models/player")) {
        if (info.entityIndex == interfaces.engine->getLocalPlayer()) {
            const auto localPlayer{ interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()) };
            
            auto applied{ false };
            for (size_t i = 0; i < config.chams[DESYNC].materials.size(); i++) {
                if (config.chams[DESYNC].materials[i].enabled) {
                    Vector lby = angles1;
                    lby.y = localPlayer->lby();
                    
                    if (applied) {
                        localPlayer->SetAngle2(Vector{ 0,lby.y,0 });
                        hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, customBoneToWorld);
                        return true;
                        interfaces.modelRender->forceMaterialOverride(nullptr);
                        localPlayer->SetAngle2(lby);

                    }
                    applyChams(config.chams[DESYNC].materials[i], false, localPlayer->health());
                    applied = true;
                }
            }
        }
    }
    return false;
}`

**Comment by atk3001** [comment]
image
For some reason it crashes everytime I take a grenade into the hand

**Comment by notgoodusename** [comment]
did you check weaponid?

**Comment by atk3001** [comment]
Sorry but I pretty much just pasted your changes into the cheat.  I'm pretty new to this stuff. I just checked and I have exactly the same AntiAim.cpp that you have but my guess would be thats not what you meant. Sorry

**Comment by notgoodusename** [comment]
Check file changes in github

**Comment by Straightplus** [comment]
ummm like the point of getting desync/fake angle chams is that it you can see the fake not the real?

**Comment by atk3001** [comment]
I was able to fix the error. But now I noticed that changing the pitch does nothing.

**Comment by notgoodusename** [comment]
it does

**Comment by notgoodusename** [comment]
it doesnt show client side but i actually works

**Comment by Pateeesz** [comment]
> i got this, its not as easy as effex said from what i understood i should have a function that
> instantly sets the model angle so, i set the angle for the moment i need to render and after rendering i reset
> `bool Chams::desync1(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept
> {
> if (strstr(info.model->name, "models/player")) {
> if (info.entityIndex == interfaces.engine->getLocalPlayer()) {
> const auto localPlayer{ interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()) };
> 
> ```
>         auto applied{ false };
>         for (size_t i = 0; i < config.chams[DESYNC].materials.size(); i++) {
>             if (config.chams[DESYNC].materials[i].enabled) {
>                 Vector lby = angles1;
>                 lby.y = localPlayer->lby();
>                 
>                 if (applied) {
>                     localPlayer->SetAngle2(Vector{ 0,lby.y,0 });
>                     hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, customBoneToWorld);
>                     return true;
>                     interfaces.modelRender->forceMaterialOverride(nullptr);
>                     localPlayer->SetAngle2(lby);
> 
>                 }
>                 applyChams(config.chams[DESYNC].materials[i], false, localPlayer->health());
>                 applied = true;
>             }
>         }
>     }
> }
> return false;
> ```
> 
> }`

What's the angles1 and SetAngle2?

**Comment by notgoodusename** [comment]
setangle2 https://www.unknowncheats.me/forum/counterstrike-global-offensive/238768-fake-angle-src-friendly.html

**Comment by notgoodusename** [comment]
angle1 is cmd->viewangles

**Comment by Pateeesz** [comment]
thanks

**Comment by xAkiraMiura** [comment]
> 
> 
> ummm the point of getting desync/fake angle chams is that it you can see the fake not the real?

you want to see both.

**Comment by Straightplus** [comment]
yes ik

**Comment by Straightplus** [comment]
and 
@notgoodusename 
> angle1 is cmd->viewangles

what are you supposed to type in the "Chams::render() noexcept"

        return desync(ctx, state, info, customBoneToWorld, cmd);
i have that ?

**Comment by notgoodusename** [comment]
> and
> @notgoodusename
> 
> > angle1 is cmd->viewangles
> 
> what are you supposed to type in the "Chams::render() noexcept"
> 
> ```
>     return desync(ctx, state, info, customBoneToWorld, cmd);
> ```
> 
> i have that ?

nah, its a bool make it public and call it on hooks

**Comment by Straightplus** [comment]
okay kewl

**Comment by Straightplus** [comment]
iam having some trouble with it saying it only takes 5 args but i have 6?

        if (chams.desync(ctx, state, info, customBoneToWorld, cmd))
            hooks.modelRender.callOriginal<void*, void*, void*, const ModelRenderInfo&, matrix3x4*, UserCmd*>(21, ctx, state, info, customBoneToWorld);

**Comment by notgoodusename** [comment]
because cmd isnt part of drawmodelexexute

**Comment by Pateeesz** [comment]
anyone have this in client_panorama?
static SetAngleFn SetAngle = (SetAngleFn)((DWORD)GetModuleHandle("client.dll") + 0x1C2AC0);

**Comment by Straightplus** [comment]
Thanks

**Comment by GA9BR** [comment]
Screenshot_2
i get this

**Comment by igothxps** [comment]
@ga9br well I can’t read anything other than the local player thing pretty sure it’s supposed to be LocalPlayer but I’m not very sure

**Comment by GA9BR** [comment]
i will send the code

**Comment by GA9BR** [comment]
https://pastebin.com/4zfLyhL7

**Comment by Straightplus** [comment]
static void __stdcall drawModelExecute(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld, UserCmd* cmd) noexcept
{
    if (interfaces.engine->isInGame()) {
        Visuals::nightmode();
        Visuals::fullbright();
        if (Visuals::removeHands(info.model->name) || Visuals::removeSleeves(info.model->name) || Visuals::removeWeapons(info.model->name))
            return;
        const auto isOverridden = interfaces.modelRender->isMaterialOverridden();
        static Chams chams;
        if (chams.render(ctx, state, info, customBoneToWorld))
            hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, customBoneToWorld);
        if (chams.desync(ctx, state, info, customBoneToWorld, cmd))
            hooks.modelRender.callOriginal<void*, void*, void*, const ModelRenderInfo&, matrix3x4*, UserCmd*>(21, ctx, state, info, customBoneToWorld);
        if (!isOverridden)
            interfaces.modelRender->forceMaterialOverride(nullptr);
    } else
        hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, customBoneToWorld);
}

@notgoodusename ?

**Comment by Straightplus** [comment]
@Blank Billey Eyelash#8336

**Comment by GA9BR** [comment]
help meee 
Screenshot_1
Screenshot_2

**Comment by GA9BR** [comment]
Screenshot_4

**Comment by notgoodusename** [comment]
check hooks.cpp again

**Comment by GA9BR** [comment]
I DONT KNOW CODE NOTHING ;-;

**Comment by notgoodusename** [comment]
did you fix it?

**Comment by xAkiraMiura** [comment]
pro tip: `git clone https://github.com/notgoodusename/Osiris-1` [git for windows](https://gitforwindows.org/)
**please stop trying to paste code, just use git as it was intended.**

im 90% sure you can put multiple attachments on a single post, no need for 3 seperate posts.

**Comment by notgoodusename** [comment]
Thanks!

**Comment by GA9BR** [comment]
> você consertou?

i dont know how i fix that :(

**Comment by GA9BR** [comment]
i just know paste

**Comment by xAkiraMiura** [comment]
[cmd.exe](https://en.wikipedia.org/wiki/Cmd.exe)
its been here since the 1990s with MS-DOS

or you could use github's built in download feature. https://github.com/notgoodusename/Osiris-1/archive/master.zip

**Comment by notgoodusename** [comment]
> Why you trying to broke the code?

to not manually activate fixmovement

**Comment by GA9BR** [comment]
@notgoodusename help me to fix my problem :(

**Comment by notgoodusename** [comment]
> @notgoodusename help me to fix my problem :(

put this
auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

**Comment by GA9BR** [comment]
> > @notgoodusename help me to fix my problem :(
> 
> put this
> auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());


Where ?

**Comment by notgoodusename** [comment]
at hooks.cpp

**Comment by GA9BR** [comment]
ty :) lov u

**Comment by GA9BR** [comment]
wow i get anothers erros wtf 
Screenshot_2

**Comment by streamshark** [comment]
stop trying to manually paste in changes and just clone it from notgoodusername's fork

**Comment by GA9BR** [comment]
> pare de tentar colar manualmente as alterações e apenas clone-o do fork do notgoodusername

i cant cus i pasted another features

**Comment by GA9BR** [comment]
Severity Code Description Project File Line Suppression Status
Error C3615 in consumed function 'Misc :: fixMovement' cannot cause a constant expression (compiling source file Hacks \ Misc.cpp) Osiris C: \ Users \ Alberto Oliveira \ Desktop \ Osiris \ Osiris \ Osacks \ Hacks \ Misc. 39 h

**Comment by GA9BR** [comment]
Screenshot_3

**Comment by igothxps** [comment]
@GA9BR FORK IT OFF HIS GITHUB

**Comment by GA9BR** [comment]
how i put my source in github ?

**Comment by GA9BR** [comment]
https://www.mediafire.com/file/x5odxwus2lwm1dn/Osiris.rar/file

**Comment by GA9BR** [comment]
HELP

**Comment by streamshark** [comment]
dude if you pasted other features and can't get it to work this isn't the place to resolve that, this is a discussion for this particular anti aim pull request, not to mention you don't seem like you speak fluent english

**Comment by GA9BR** [comment]
> cara, se você colou outros recursos e não conseguiu fazê-lo funcionar, este não é o lugar para resolver isso. Esta é uma discussão para essa solicitação específica de extração de mira, sem mencionar que você não parece falar inglês fluentemente

bro wtf are you talking? i'm asking for help for this thread anti-aim dont other pasted features

**Comment by GA9BR** [comment]
I'm asking for help on the anti-aim paste that went wrong

**Comment by streamshark** [comment]
you don't need to paste the antiaim, just directly download his forked repo from GitHub and compile it. you are having issues because you are trying to add other features

**Comment by xAkiraMiura** [comment]
# THIS IS NOT YOUR TECH SUPPORT CHANNEL

i literally linked you the download for it at https://github.com/notgoodusename/Osiris-1/archive/master.zip
either listen to our instructions or stop.

**Pull request closed without merging**
