### PR TITLE
added Aim position line

### PR DESCRIPTION
**Pull request by M3351AN**
added Aim position line, its function is to point out the line of "pitch0" to help prefire the head of the enemy at the same height, we call it the headshot line
}EFZEJ9FOAI27SOL_4TH~WG
NRW6YSL%6I80A89%(@%D$ 7

### CODE REVIEW

**Comment by Tempfyyyy** [comment]
nice keep it going !

**Comment by hamad12a** [comment]
I don't understand how it is helpful?

**Comment by fanat1cc** [comment]
Wouldn't it be better to put it in aimbot or Visuals?

**Comment by Fr0go1** [comment]
> Wouldn't it be better to put it in aimbot or Visuals?

im sure you can figure out how to do that

**Comment by Fr0go1** [comment]
> added Aim position line, its function is to point out the line of "pitch0" to help prefire the head of the enemy at the same height, we call it the headshot line }EFZEJ9FOAI27SOL_4TH~WG NRW6YSL%6I80A89%(@%D$ 7

very good, thanks

**Comment by Fr0go1** [comment]
1 question how do i change the size of it

**Pull request closed without merging**
