### PR TITLE
Traducción

### PR DESCRIPTION
**Pull request by SuperK2-OS**

### CODE REVIEW

**Comment by doggobot-owner** [comment]
wow but why

**Comment by caiocinel** [comment]
There are some pull requests that I'm like "so right".

**Comment by Scui1** [comment]
Okay boomer Image of him

**Comment by DEVjeSucks** [comment]
After what I've seen, I don't want to live anymore

**Comment by wemanzoz** [comment]
Its for his spanish brothers prob

**Comment by mkot2** [comment]
lmao

**Pull request closed without merging**
