### PR TITLE
Auto disconnect

### PR DESCRIPTION
**Pull request by Khajiitos**
Automatically disconnects from the game when the match ends

### CODE REVIEW

**Comment by 0xb77a9** [comment]
Sound useless sorry
but nice work!

**Comment by daisuki333** [comment]
Are you able to recreate another version of this but instead if someone tries to vote kick you it disconnects which is basically like an anti-vote kick thing. I'm not sure exactly how that works but that would be cool.

**Comment by Khajiitos** [comment]
> Are you able to recreate another version of this but instead if someone tries to vote kick you it disconnects which is basically like an anti-vote kick thing. I'm not sure exactly how that works but that would be cool.

This is pointless as even if you disconnect, if the vote is successful you won't be able to join back

**Comment by thisisprettyepic** [comment]
Nice! Thanks!

**Comment by wemanzoz** [comment]
How do i add this to my osiris build

**Comment by Heyter** [comment]
Useful, thanks.

**Pull request closed without merging**
