### PR TITLE
Add "Reload configs" button in Config tab

### PR DESCRIPTION
**Pull request by playday3008**
^

### CODE REVIEW

**Comment by Oly-UK** [comment]
nice this is actually an awesome addition @danielkrupinski please pull this

**Comment by notgoodusename** [comment]
what is this for?

**Comment by w1ldac3** [comment]
For any of you not understanding, basically when you put someone's config or ur config in folder with settings, it won't refresh list of configs. So you need to re-inject cheat again. This fixes it.

**Comment by danielkrupinski** [comment]
That's an incorrect approach, better do like in https://github.com/danielkrupinski/Osiris/blob/368806d35e666ca489d58bbe14a42210184f6218/Osiris/Config.cpp#L23-L26

**Pull request closed without merging**
