### PR TITLE
First shot delay and kill delay.

### PR DESCRIPTION
**Pull request by W4tev3n**

### CODE REVIEW

**Comment by dayz2000** [comment]
what's frist shot delay mean ?
pre delay when aimbot start shot  ?

**Comment by aljawary** [comment]
what do u mean can u xplain?

**Comment by W4tev3n** [comment]
Yeah, first shot delay is a feature to let aimbot aim on a target without shooting, it's pretty useful for deagle, ssg and awp.
Kill delay waits a given while after killing a target before aiming on a next one. 
Here's the video demonstration of these features: [https://youtu.be/Blhx_BZOMIQ](url)

**Comment by retart1337** [comment]
Get stickbugged lol

**Comment by Rcsette** [comment]
Is that a way to make the aimbot works only after a seconds thats it is activated? I mean, I press the aimkey and it is activated secons after it, even if I am not in attack. thx

**Review by rad66 — APPROVED** [review]

**Pull request closed without merging**
