### PR TITLE
Draw all backtrack Chams

### PR DESCRIPTION
**Pull request by JDeu**
Added option to draw all backtrack Chams.

Daniel will want to change where the config is stored but I'm lazy so just added to backtrack.

### CODE REVIEW

**Comment by ZPDMiller** [comment]
Nice dude

**Comment by Oly-UK** [comment]
I FUCKING LOVE YOU, YOU LEGEND!

**Comment by xsincbt** [comment]
Lmao

**Comment by furioushell98** [comment]
Cool

**Comment by igre3zy** [comment]
@JDeu think you could make it where the backtrack chams dont override enemy chams?

**Comment by thomas0aotian** [comment]
so check if player is moving?

**Comment by igre3zy** [comment]
> so check if player is moving?

@thomas0aotian The chams still override when the player is still

**Comment by thomas0aotian** [comment]
@igre3zy  backtrak cham and player cham are not in the same pos if moving

**Comment by Bywnb** [comment]
So nice job!Daniel plz pull it ~ @danielkrupinski

**Comment by Novalaki** [comment]
Excuse me if im wrong. but for backtrack doesnt it only shoot at the last tick all not all records?

**Comment by thomas0aotian** [comment]
@Novalaki no , but u can u dont have to. thats why backtrack make the target so ez to hit,they make copies of ur targets.

**Comment by Novalaki** [comment]
@thomas0aotian I dont think you understand what i was asking. i know how backtrack works

**Comment by thomas0aotian** [comment]
@Novalaki idt u understand.... no, shoot every record of backtrack will does damage to the target,it's not just the last.

**Comment by Novalaki** [comment]
@thomas0aotian look at this video i posted https://youtu.be/VDnWgduqDzs
Im saying that this feature to draw all the records (or ticks whatever you wanna call it lol) is kinda pointless because the tick count is only set for the last tick and not all of them so you can only shoot at the last one. not all of them.

**Comment by thomas0aotian** [comment]
@Novalaki is this osiris,idk let me try it today.it's not supposed to be for only the last tick

**Comment by Novalaki** [comment]
Yes im sure its osiris lol

**Comment by thomas0aotian** [comment]
@Novalaki alright bud, I test it out many times and I think the backtrak works ok. It's not only just last tick I'm sure. U can hit  between the last tick and the target but it's not as accurate maybe dude spread or latency.

**Comment by TomVonNebenan** [comment]
So how can i put this into my Osirisconfig? Where do i have to put in the code?

**Comment by m0nsterJ** [comment]
This Code posted here is outdated and will cause problems in-game.

**Comment by TomVonNebenan** [comment]
@m0nsterJ Bro, its working perfectly for me. But cna i get vacced for that? Its much better with the Backtrack + Chams, but im on a Prime Account LEM and dont want to get banned.

**Comment by m0nsterJ** [comment]
look at the bottom of the Pull Request, it says that the code conflicts with some files in the cheat.
The Problems that i experienced is, that it draws endless chams on the players with no ending,until the game crashes

**Comment by TomVonNebenan** [comment]
Oh, in my case this doesnt happen. Do you think there could be a VAC-problem with it?

**Comment by m0nsterJ** [comment]
There is always a chance of getting banned when you inject cheats, I can't guarantee you that you won't get banned using this cheat. All I can say is that I have been using this cheat for a very long time and I have never been VAC banned.
A VAC-problem with this specific feature? I don't think so VAC is just an anti cheat system running while you are playing. It won't cause any issues with specific features,except for using invalid angles,which causes untrusted bans

**Comment by TheOrangeGaming** [comment]
Tried to use this, didn't work.

**Comment by JustYourOrdinaryNormie** [comment]
2eggs really be contributing to this shit LOL

**Comment by KillaBoi** [comment]
> 2eggs really be contributing to this shit LOL

ofc, fuck valve xd

**Comment by dayz2000** [comment]
update pls

**Comment by TomVonNebenan** [comment]
yo wtf its so easy

dayz2000 <notifications@github.com> schrieb am So., 16. Aug. 2020, 00:15:

**Pull request closed without merging**
