### PR TITLE
Updated virtual method indices

### PR DESCRIPTION
**Pull request by mdilai**
Fresh update, fresh crash, fresh fix. Have a nice day.

### CODE REVIEW

**Comment by sundafused** [comment]
Thanks cuh I've been over here researching how to change offsets n shit

**Comment by VuBrian22** [comment]
> Thanks cuh I've been over here researching how to change offsets n shit

It's actually quite simple for him to do. We discovered the fix here: https://github.com/danielkrupinski/Osiris/issues/542/ 

Every game update all we have to do is raise each value in Entity.h by 1.

**Comment by sundafused** [comment]
> > Thanks cuh I've been over here researching how to change offsets n shit
> 
> It's actually quite simple for him to do. We discovered the fix here: #542
> 
> We found out that every game update, all we have to do is raise each value of CallVirtualMethonds in Entity.h by 1. So now these fixes will be a lot quicker every update rather than having to wait 23+ hours until we can find a fix.

Oh wow, okay. Thank you so much!

**Comment by Phawak** [comment]
can you give me the dll i'm too bad to do these things

**Comment by VuBrian22** [comment]
> can you give me the dll i'm too bad to do these things

Either learn to edit the source. It's damn simple or wait for Daniel to official approve this and update it.

**Comment by mdilai** [comment]
> > Thanks cuh I've been over here researching how to change offsets n shit
> 
> It's actually quite simple for him to do. We discovered the fix here: #542
> 
> We found out that every game update, all we have to do is raise each value of CallVirtualMethonds in Entity.h by 1. So now these fixes will be a lot quicker every update rather than having to wait 23+ hours until we can find a fix.

Not really dude, not so easy however is true for last two updates. Every time Valve add some new function/method to Entity class, all offsets **after** new function get shifted right. That's why we don't change getAbsOrigin() or setModelIndex() offsets - they are before new function. Also Valve may add several new functions and even add them in different places around a class (so some offsets will be incremented by 1 and some by 2, 3, whatever). There are two ways to fix - bruteforce or disassembling. Guess which is a correct one and which is used by me tonight :) 

Moreover, better to replace offsets with NETVARs, for example getActiveWeapon() can be replaced with getClientEntityByHandle(m_hActiveWeapon()) so we will not to need change it after updates. getEyePosition() can be replaced with sum of orgin and viewoffset vectors from NETVARs. And probably other function can be re-implemented same way. Let Daniel to think about this.

**Comment by VuBrian22** [comment]
> s. Every time Valve add some new function/method to Entity clas

Oh yeah forgot about that. Welp I apologize. I'm just a novice in HS studying all this so it takes time for me to learn. Thanks.

**Comment by hyperxpro** [comment]
@danielkrupinski Have a look.

**Comment by danielkrupinski** [comment]
Thanks!

**Comment by 0xE232FE** [comment]
> 
> 
> can you give me the dll i'm too bad to do these things

Don't accept any DLL given to you. If someone is smart he can hack your computer and get your passwords, contacts and banking informations. Take care and don't be so fucking green!!!

**Comment by VuBrian22** [comment]
> @Phawak
> 
> > can you give me the dll i'm too bad to do these things
> 
> Don't accept any DLL given to you. If someone is smart he can hack your computer and get your passwords, contacts and banking informations. Take care and don't be so fucking green!!!

Hence Why I don't give it to people lol. There are precautions and standards.

**Pull request merged**
