### PR TITLE
Added a few visual features, pingbased backtrack, Fullbright light and other pullrequests extended and fitted to GUI.

### PR DESCRIPTION
**Pull request by RyDeem**
Added:
-Ping Based Backtrack
-Draw all backtrack cham ticks
-Fullbright Light//mat_fullbright
-Ragdoll Gravity custom value changer
-Ragdoll Physics time scale (faster or slower moving body through time/air)//cl_phys_timescale
-Added remove weapon sway when moving/running option.//cl_use_new_headbob

-Viewmodel Move XYZ for weapons and knife independently(sv_minspec->setValue(1); is needed for more then 2.5 each xyz direction, now up to a max of 20.)
-cl_righthand in menu when selecting viewmodel for weapons and knife independent
-default (0.0.0) location for bomb equip viewmodel forced. (works 95% of the time)
-Hitmarker Damage numbers animation from chrosshair with menu settings integration.
-spec list on players you are spectating added
-Config save/load integration for all of the above.

////////////////////////////////////////////////////////////////////////

here is a link to compare
https://github.com/danielkrupinski/Osiris/compare/master...RyDeem:master

////////////////////////////////////////////////////////////////////////
if (config.human.reader) > (config.emotion.interested)=extended description{

-Pingbased backtrack is what it says on the tin, it makes the backtrack lenght match your ingame ping to server in ms. If you disable pingbased you can see the ping value in backtrack tick ms slider on the gui. Basically takes similar code like on the fps/ping watermark.

-Fullbright light = forces mat_fullbright 1 and disables brightness slider, as in my test it did nothing with fullbright on, change the world color for much crisper light now, and see chams better on no shadows and light changes in the enviroment.

-Gravity value changer = customize the gravity abount you get with the flip gravity gui button, 
do -600(default or -2400 for fast moving flying upwards ragdolls. Want them to suck to the ground when they die instantly? do 2400.

-Added a gui interface thats not perfect onto ZerGo0'ds code for changing the hitmarker damage settings, would be better if i understood how he calls for movement direction in the code. not gud coder eh,? yas :/

-And i moved around things in the visuals window, hope people arent mad about that, i had to put my new GUI poppup sliders for gravity changer, viewmodel xyz and hitmarker at the bottom for max nice effect xd

-Added ragdoll Physics timescale float input window for when selecting the option in visuals, default is 1.0 and you can set it to 0.5 for half as fast ragdoll animation/physics or 2x for faster, onr anything inbetween. Goes up from 0.0x to 10x.

};
//////////

Thank you coders!
danielkrupinski#835 By ZerGo0 // Hitmarker Damage Indicator
danielkrupinski#894 By agshaidun // Spec List on other players
danielkrupinski#730 By JDeu // Draw All Backtrack Tick Chams
danielkrupinski#584 By effex1337 // View Model Offset XYZ

### CODE REVIEW

**Comment by Shaxzy** [comment]
"if (config.human.reader) > (config.emotion.interested)=extended description{"
Lmao, made my day :p

**Comment by AbdallahMehiz** [comment]
shouldn't it be better if u pull request these changes one by one?

**Comment by RyDeem** [comment]
> shouldn't it be better if u pull request these changes one by one?

it could be probbably better, but i dont really wanna go over it a 3rd time, but i can do that.

**Comment by RyDeem** [comment]
Im having fun now adding console commands that are behind sv_cheats 1 and clientsided for my personal branch, i got tons of shite i can add here, but like this is small amount of additions now.

**Comment by RyDeem** [comment]
Was thinking of building a model mover xyz for each of the guns individually or groups like in aimbot window, to have max customization.
would be cool.
the grenades look wierd a bit with default "weapon" location, so that would be 1st id do, set default 000 for grenades, but i dont know if my way of autoupdating is good, for me it doesnt drop frames, but i can imagine its changing the cvars every tick/cycle of code in its current state, so i dont really know how to fix it/make it call only on changes.

**Comment by xAkiraMiura** [comment]
# stop
Why did you open another useless PR like this, you're stealing code from the other branches when daniel could easily just accept all the pull requests.
You could have easily just updated your old pull request, instead you closed it and made another which will never get accepted.

What you could have done:
**Make the feature you want and don't try to merge pulls for daniel, he is in control of the project. He will decide if he wants them in or not.**

**Comment by RyDeem** [comment]
okboomer w/e not like im trying to help the cause by contributing code n stuff, developing stuff further and making life easyer by having them in one place, and for other people to see this modification of the master that has more features with easy access with one merge, instead of doing it themselves. Noone would see them even if they are not on master branch, as noone would see that they exist if not for this pull request.

**Comment by xAkiraMiura** [comment]
[10 tips for better Pull Requests.](https://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/) < link you should open
1. Make it small
  A small, focused Pull Request gives you the best chance of having it accepted. 
2. Do only one thing
the rest is irrelevent but you should read up on it either way.

**Pull request closed without merging**
