### PR TITLE
Jump Check

### PR DESCRIPTION
**Pull request by zajkos**
I (with a lot of help from Kron1Q) add Jump Check to Aimbot

### CODE REVIEW

**Comment by notgoodusename** [comment]
no need to define onground just do flags() & 1

**Comment by ClaudiuHKS** [comment]
Very good idea to automatically stop the aimbot while the ``localPlayer`` not on ground.

**Comment by zajkos** [comment]
ok I will try to improve
PS. I'm just learning C ++ so for fun, I try to write something (but it doesn't always work out)

**Comment by zajkos** [comment]
> no need to define onground just do flags() & 1

can u help ?  I'm really bad

**Comment by dapaster** [comment]
**Aimbot.cpp**

if (!(localPlayer->flags() & 1) && config->aimbot[weaponIndex].jumpCheck) return;

**Entity.h**

Delete `#define FL_ONGROUND (1<<0)`

**Comment by zajkos** [comment]
OK thanks, I have already corrected

**Comment by zajkos** [comment]
BTW, it will be added or something else I have to do

**Comment by techzin** [comment]
@danielkrupinski add this to the main branch.

**Comment by dayz2000** [comment]
update ? pls ?

**Comment by AntonDoil** [comment]
Works well, thanks.

**Pull request closed without merging**
