### PR TITLE
Add Skinsearch  & better GUI & Bypass_pure & StandAlone Ragebot(junk) & NightMode

### PR DESCRIPTION
**Pull request by Cyk-Fad**
Just wait some days ,I at school now .Then I get home, I will add skinserch

### CODE REVIEW

**Comment by Oly-UK** [comment]
shadowware kekw

**Comment by Cyk-Fad** [comment]
what ?

**Comment by Cyk-Fad** [comment]
> 影子软件kekw

just changed a name haha

**Comment by Cyk-Fad** [comment]
We can search skin now ,You can wait me do English version

**Comment by wirebruh** [comment]
lmao

**Comment by unnamed01X** [comment]
you should fix everything dude, your code is kinda trash

**Comment by unnamed01X** [comment]
how menu looks like? could you share the screenshot?

**Comment by rafalohaki** [comment]
screenshot pls

**Comment by dapaster** [comment]
does it affect osiris performance?

**Comment by Cyk-Fad** [comment]
> 它会影响osiris的性能吗？

no

**Comment by Cyk-Fad** [comment]
> 菜单看起来如何？你可以分享截图吗？
UI looks like skeet , but it is junk ,too

**Comment by Cyk-Fad** [comment]
tommorow , When I get home ,I'll add English and fixed everything.
I'll make UI better

**Comment by Cyk-Fad** [comment]
I just using school's computer,so I can't play CSGO.
You can download my fork,and use release.
you can see chinese UI And better
I will add Enlish tommorow

**Comment by DoomFishWasTaken** [comment]
@Cyk-Fad won't complied and won't show angles in tp, you forgot to c+p Hooks.cpp from my pull

**Comment by Cyk-Fad** [comment]
> @ Cyk-Fad无法编译，也不会在tp中显示角度，您从我的收藏中忘记了c + p Hooks.cpp

yes, please wait me get home to fix all bug

**Comment by Cyk-Fad** [comment]
OK , I'll fix all bug now, and add English language

**Comment by Cyk-Fad** [comment]
now the skinsearch and english is working

**Comment by Cyk-Fad** [comment]
image
This is GUI
I think it is bad

**Comment by Cyk-Fad** [comment]
image
English search is working,too

**Comment by Cyk-Fad** [comment]
image
Choose 杂项 to change language

**Comment by Cyk-Fad** [comment]
image
looks good

**Comment by Cyk-Fad** [comment]
I have to go to sleep , Now in China is 0:27
明天继续优化

**Comment by KernCS** [comment]
Just an idea but why not just make a list box that auto update after every letter? instead of having a combo + a listbox?

**Comment by Cyk-Fad** [comment]
All right tommorow i will change it
Good night

**Comment by KernCS** [comment]
Good night

**Comment by notgoodusename** [comment]
That isnt a svpure bypass

**Comment by Cyk-Fad** [comment]
i don't know i just paste it

**Comment by Cyk-Fad** [comment]
Can you complete it?

**Comment by Cyk-Fad** [comment]
I'll close this,because no body need skinsearch & betterGUI

**Comment by dapaster** [comment]
Thank you for making this 👍

**Comment by Cyk-Fad** [comment]
> Thank you for making this

You're welcome

**Comment by Cyk-Fad** [comment]
If you need anything,You can tell me. I can update to you

**Comment by playday3008** [comment]
@Cyk-Fad Can you create a separate pull request?
1. SkinSearch(most needed)
2. sv_pure bypass
3. RCS and Standalone RCS
4. Slow walk
5. Bullet beams
6. Set Thirdperson can see pitch antiAim
That's better than "All in one"
Thank you very much

**Comment by dctrlight** [comment]
debugging and opening menu give an imgui error about forgetting end/endchild

**Comment by DoomFishWasTaken** [comment]
@playday3008 yep fixed it bullet beams (and other beams like beam circles are now working check the SDK/Beams.h for more info)

**Comment by Cyk-Fad** [comment]
> @Cyk-Fad Can you create a separate pull request?
> 
> 1. SkinSearch (most needed)
> 2. sv_pure bypass
> 3. RCS and Standalone RCS
> 4. Slow walk
> 5. Bullet beams (maybe will be [here](https://github.com/danielkrupinski/Osiris/pull/1546))
> 6. Set Thirdperson can see pitch antiAim
> 
> That's better than "All in one"
> Thank you very much

Sure, But I don't have time to do this

**Comment by Cyk-Fad** [comment]
I will add nightmode soon

**Comment by fwb5** [comment]
老哥，你做出皮肤筛选了吗

**Comment by KernCS** [comment]
i would still love to see a listbox that auto update after every letter? instead of having a combo + a listbox?

**Comment by Cyk-Fad** [comment]
> i would still love to see a listbox that auto update after every letter? instead of having a combo + a listbox?

fine, Pls wait me some minutes

**Comment by Cyk-Fad** [comment]
> 老哥，你做了皮肤筛选了吗

暂时不想做，你可以QQ联系我 2476159893

**Comment by Cyk-Fad** [comment]
希望各位中国人自己心里有点 B 数 ，把这个拿去卖

**Comment by Cyk-Fad** [comment]
I don't know how to autosearch, could you help me?@KernCs

**Comment by dapaster** [comment]
i can't compile https://github.com/Cyk-Fad/Shadow-Ware

image

**Comment by Cyk-Fad** [comment]
> i can't compile https://github.com/Cyk-Fad/Shadow-Ware
> 
> image

Please wait me some minutes

**Comment by egssy0** [comment]
dude, thank you for doing this things

**Pull request closed without merging**
