### PR TITLE
More AA methods.

### PR DESCRIPTION
**Pull request by xAkiraMiura**
I added static, jitter, and spin to the anti-aim (Didn't remove the legit/desync AA)

AA in action: https://youtu.be/dZYe_FR00zE 
Menu changes: https://i.imgur.com/4dK7G6a.png

_Also Visual Studio changed some spaces to tabs automatically_

### CODE REVIEW

**Comment by xAkiraMiura** [comment]
i didn't modify the legit AA at all, i did move some of the checks around but it runs the exact same as what is the current AA. I know jitter, static, and spin are all ineffective AA methods but considering the legit is forward AA static is a bit better, I only added spin because of the many issues for it.

**Comment by notgoodusename** [comment]
ADD AN LBY BREAKER

**Comment by agshaidun** [comment]
جاڠن ݢادوه٢ 😂

**Comment by xAkiraMiura** [comment]
> ADD AN LBY BREAKER

I'm not experienced in making desync/legit anti-aim, if I understood how it worked a bit better I could try but at the moment I'm adding more primitive AA methods, just so the choice is there, and its easier to make new ones in the future.

> You wont see the antiaim angles in thirdperson.
> 
> And the desync is close to useless as this is a balance desync aka the radiuses of the fake and the read head are about 5-10 units different (not very far)

I had to use bot_mimic to see what the anti-aim was doing because I haven't added fake chams yet, I might try tonight but I need to check out DrawModelExecute.

In testing i noticed just how useless the current AA method is, thats why I decided to make this pull request. Nothing was fooled by the current aa, not even legit players missed it. the new aa methods probably won't stop any competent cheats but it will at least prevent legits from hitting the head most of the time.

**Comment by xAkiraMiura** [comment]
Just noticed the PR title was the commit message rather than what I wanted to call it.

**Comment by rosesware** [comment]
Fix movement would be good, I can't walk in "Spin Mode" and "Static" and "Jitter" movement is inverted.

**Comment by xAkiraMiura** [comment]
Enable fix movement in the misc tab, from my testing it works with the anti-aim enabled.

**Comment by streamshark** [comment]
> > ADD AN LBY BREAKER
> 
> I'm not experienced in making desync/legit anti-aim, if I understood how it worked a bit better I could try but at the moment I'm adding more primitive AA methods, just so the choice is there, and its easier to make new ones in the future.
> 
> > You wont see the antiaim angles in thirdperson.
> > And the desync is close to useless as this is a balance desync aka the radiuses of the fake and the read head are about 5-10 units different (not very far)
> 
> I had to use bot_mimic to see what the anti-aim was doing because I haven't added fake chams yet, I might try tonight but I need to check out DrawModelExecute.
> 
> In testing i noticed just how useless the current AA method is, thats why I decided to make this pull request. Nothing was fooled by the current aa, not even legit players missed it. the new aa methods probably won't stop any competent cheats but it will at least prevent legits from hitting the head most of the time.

You can use sv_showlagcompensation and sv_lagcompensateself then shoot to trigger an update to show real hitbox: the amount of desync the default Osiris yaw AA provides isn't much at all. I use 5 choked packets after messing around with the value and looking at the desync this way. Here's a pic of around the max amount of desync it provides. https://i.imgur.com/isbSUmw.png

**Comment by Straightplus** [comment]
That is enough desync for a newbie to miss just saying......

> Here's a pic of around the max amount of desync it provides. https://i.imgur.com/isbSUmw.png

**Comment by Straightplus** [comment]
TL:DR the desync in the antiaim is not that good

**Comment by notgoodusename** [comment]
> That is enough desync for a newbie to miss just saying......
> 
> > Here's a pic of around the max amount of desync it provides. https://i.imgur.com/isbSUmw.png

yeah but you can get 116 degres of desync with a lby breaker

**Comment by Straightplus** [comment]
Yeah your right but its still enough desync for a noob to miss ;) iam just trolling bro jkjk

**Comment by rosesware** [comment]
> Enable fix movement in the misc tab, from my testing it works with the anti-aim enabled.

Not working, I test before saying anything.

**Comment by xAkiraMiura** [comment]
I loaded a default config with nothing, enabled the spin aa and **only** fix movement from the misc tab. It worked for me so I don't know if there is a conflicting option that disables fix movement.

Try loading a default config, only enabling the AA and fix movement.

**Comment by xAkiraMiura** [comment]
fixMovement works by finding the delta change from before we modify view angles and afterwards, In theory it doesn't matter where we call fixMove as long as its after everything that will modify view angles has finished and we can provide it the original angles. In my testing fix movement works as is and I haven't been able to reproduce it not working.

**Comment by xAkiraMiura** [comment]
Failed to rebase remote, I'm going to close this pull and re-open it/make a new one when ive fixed the above issues.

**Comment by CerberusGame** [comment]
Not working

**Comment by xAkiraMiura** [comment]
of course its not working, the pull is a month old and the game has updated a lot.
the AA methods never had an issue per se, the problem is everything else around them has not been upgraded. you can clone this pull then use `git rebase` to get a working version of the pull.

**Comment by smartxd3** [comment]
thanks alot tomorrow im going to test it :)

**Comment by Faysal1969** [comment]
i tried the AA's and they worked for me thanks

**Comment by egssy0** [comment]
its working fine :D

**Comment by zxsleebu** [comment]
How did you do the movement acting like normal? I see just a changing of viewangles and nothing more. Am i blind? Or it stopped working after update?

**Pull request closed without merging**
