### PR TITLE
Draw aimbot FOV

### PR DESCRIPTION
**Pull request by NexSqaud**

### CODE REVIEW

**Comment by Evilhelder** [comment]
Multiple errors .... Any idea how to fix it?

image

**Comment by NexSqaud** [comment]
You copied changes to wrong files.

**Comment by Evilhelder** [comment]
> 
> 
> You copied changes to wrong files.

bro, I just downloaded the modified file from your profile.... :T I didn't change anything.

image

**Comment by NexSqaud** [comment]
Uh i found error... Wait a minute.

**Comment by Evilhelder** [comment]
nice :D 
image

**Comment by Rabbe00** [comment]
Thank you for this!

**Comment by Rabbe00** [comment]
image

**Comment by NexSqaud** [comment]
@Rabbe00 download source from my repo.

**Comment by Rabbe00** [comment]
@NexSqaud 
image I did that and didn't change anything, only from Debug to Release mode and x86 and all these random errors come up.

**Comment by Evilhelder** [comment]
> 
> 
> @NexSqaud
> image I did that and didn't change anything, only from Debug to Release mode and x86 and all these random errors come up.

Strange that, here it is working perfectly ..

**Comment by Rabbe00** [comment]
@Evilhelder Yeah weird.

**Comment by NexSqaud** [comment]
idk that works for me 
Screenshot_109

**Comment by Rabbe00** [comment]
Got it working now after I cloned the git from Desktop Application.

**Comment by xAkiraMiura** [comment]
`git clone https://github.com/NexSqaud/Osiris`

Debug x86: Success
Release x86: Success

Make sure you use `git clone` or download from github. Manually copying changes is bad practice.

**Comment by ClaudiuHKS** [comment]
Awesome, this feature is really nice and useful.

**Comment by playday3008** [comment]
> idk that works for me
> Screenshot_109

Оно, конечно работает, но странно,
Радиус draw fov, больше чем реальный fov

**Comment by Evilhelder** [comment]
> Оно, конечно работает, но странно,
> Радиус draw fov, больше чем реальный fov

I also noticed this ..

**Comment by NexSqaud** [comment]
@playday3008 если ставить FOV аимбота большим, то понятно что и круг будет большим.

**Comment by playday3008** [comment]
Круг Draw fov больше чем реальный fov, то-есть голова в круге draw fov, но aim не срабатывает

**Comment by NexSqaud** [comment]
Эта ошибка из-за того что osiris использует не хитбокс для нахождения цели, а кость. Кость головы находится в середине головы. Я проверил, аимбот срабатывает когда в радиус попадает кость.

**Comment by playday3008** [comment]
image
Ну вот пример, если подведу прицел чуть ближе, то сработает, но голова полностю в круге

**Comment by danielkrupinski** [comment]
English only, please.

**Comment by NexSqaud** [comment]
Did you use aspect ratio changer?

**Comment by playday3008** [comment]
No

**Comment by Asviix** [comment]
Very good addition !

**Comment by ClaudiuHKS** [comment]
@danielkrupinski, I am pretty sure that @playday3008 wants the FOV circle to be the same size no matter the weapon is scopped or not. For example, a fast fix for what he wants would look like:

``if (isScoped(localPlayer))``
``maxAimFov = cfg.aim.fov[weapon] / 2;``
``else``
``maxAimFov = cfg.aim.fov[weapon];``

**Comment by NexSqaud** [comment]
@ClaudiuHKS There issue with different aspect ratios. I'm trying to correct for different aspect ratios.

**Comment by ClaudiuHKS** [comment]
@NexSqaud, let's say I am using an AimBOT FoV of 0.42.
On AK-47, the circle is really small. On AWP, while zoomed, the circle is like 4x bigger.
And yes, every enemy inside that circle gets AimBOT'ed.
While zoomed, the FoV should be 2x-3x smaller.

**Comment by SleekZ** [comment]
when I use your fork, I get alot of random crashes.

**Comment by xAkiraMiura** [comment]
attach a debugger and tell us where it is crashing. also this fork is a month old so the code may be outdated. (on 3/3/2020 Osiris broke due to a game update)

**Comment by SleekZ** [comment]
Probably just old code stuffing it up.

**Comment by aljawary** [comment]
i got this error pls help!
https://prnt.sc/svw07e
i use this version of osiris
https://github.com/DoomFishWasTaken/Osiris/tree/hvhPull

**Comment by mkot2** [comment]
> i got this error pls help!
> https://prnt.sc/svw07e
> i use this version of osiris
> https://github.com/DoomFishWasTaken/Osiris/tree/hvhPull

use a newer version of osiris that uses "->" instead of "." for the interfaces and stuff

**Comment by NexSqaud** [comment]
maybe later fix

**Pull request closed without merging**
