### PR TITLE
4.6.2020 csgo update fix

### PR DESCRIPTION
**Pull request by DoomFishWasTaken**
@danielkrupinski fixes the cheat for the new update, please merge

### CODE REVIEW

**Comment by real-Shigure** [comment]
Thx bro! 👍

**Comment by Trollface1928** [comment]
What do i do to fix it. like what do i do with the fix file

**Comment by DoomFishWasTaken** [comment]
nothing its already merged with master

**Comment by grokidijareja** [comment]
this virus or something? i need plz

**Comment by aloraini1419** [comment]
how to fix this

**Comment by grokidijareja** [comment]
> how to fix this

download the new version of osiris

**Comment by nexitex** [comment]
hello, when i launch the osiris i cant open inventory and do anything in csgo. someone help?
image

**Pull request closed without merging**
