### PR TITLE
Add option to edit Inventory items

### PR DESCRIPTION
**Pull request by Metaphysical1**
with this you can change wear, seed, stattrak, nametag even stickers of any skin added to inventory.

**Screenshots:** https://imgur.com/a/RgRQD4p

**ToDo:**
- [x] ~~add option to change wear of each sticker~~
- [x] ~~add preview of stickers~~
- [x] ~~drag and drop stickers~~
- [x] ~~stickers search box~~
- [ ] change other items settings like: agents patches, service medals date of issue, etc..

### CODE REVIEW

**Comment by wemanzoz** [comment]
based, redpilled pepsimod approved

**Comment by egwrl** [comment]
there errors

**Comment by wemanzoz** [comment]
> there errors and are u sure its just editing the inventorychanger.cpp file?

he'll fixed dw

**Comment by FozzyHvH** [comment]
> there errors and are u sure its just editing the inventorychanger.cpp file?

been waiting on someone to try this after I did, I thought I did something wrong haha.

**Comment by Metaphysical1** [comment]
Sorry guys, my build uses newer version of imgui which has "begin disabled" and "scroll to item" features, I retro fitted this PR to work with osiris' current version of imgui.
https://imgur.com/2OuPWhh

**Comment by ocewot** [comment]
> Sorry guys, my build uses newer version of imgui which has "begin disabled" and "scroll to item" features, I retro fitted this PR to work with osiris' current version of imgui. https://imgur.com/2OuPWhh

i just tried it and im getting errors on should edit im pretty sure i did everything right. i had less errors then  the first time i tried before you made changes to correct it but yeha

**Comment by wemanzoz** [comment]
> with this you can change wear, seed, stattrak, nametag even stickers of any skin added to inventory.
> 
> **Screenshots:** https://imgur.com/a/RgRQD4p
> 
> **ToDo:**
> 
> * [x]  ~add option to change wear of each sticker~
> * [x]  ~add preview of stickers~
> * [x]  ~drag and drop stickers~
> * [x]  ~stickers search box~
> * [ ]  change other items settings like: agents patches, service medals date of issue, etc..



> Sorry guys, my build uses newer version of imgui which has "begin disabled" and "scroll to item" features, I retro fitted this PR to work with osiris' current version of imgui. https://imgur.com/2OuPWhh

how do you update imgui?

**Comment by Metaphysical1** [comment]
> how do you update imgui? can u link me ur discord
you don't need to update imgui, this PR is working fine with the current version of imgui.
but if you need to update it, just download latest version from github and replace files (except files that hs _impl in their names and imconfig)

**Comment by R-png-max** [comment]
I get  3 errors when building
image

**Comment by wemanzoz** [comment]
> > how do you update imgui? can u link me ur discord
> 
> you don't need to update imgui, this PR is working fine with the current version of imgui. but if you need to update it, just download latest version from github and replace files (except files that hs _impl in their names and imconfig)

ah, ok ok  thanks man. i just want that sexy black thing

**Comment by Metaphysical1** [comment]
> I get 3 errors when building image

In my commits I exposed "passesFilter" to a higher scope, you should do like this:
https://github.com/danielkrupinski/Osiris/pull/3430/commits/57043ac0e5012b1d05f4fd646e34826382abe1fc#diff-589354681a3822069e83d96ed1f9957aaaaa733af2bccc6e27d11cd0515a604aR808-L848

**Comment by R-png-max** [comment]
> > I get 3 errors when building image
> 
> In my commits I exposed "passesFilter" to a higher scope, you should do like this: [57043ac#diff-589354681a3822069e83d96ed1f9957aaaaa733af2bccc6e27d11cd0515a604aR808-L848](https://github.com/danielkrupinski/Osiris/commit/57043ac0e5012b1d05f4fd646e34826382abe1fc#diff-589354681a3822069e83d96ed1f9957aaaaa733af2bccc6e27d11cd0515a604aR808-L848)

I fixed it, it just forgot to delete something that i shoudlve

**Comment by Frouk3** [comment]
i don't think that "Name Tag", "Sticker" needed to be in the editor, because there's an item to rename all weapons or add stickers

**Comment by 1nhale** [comment]
@Metaphysical1 i guess now we have some variable name conflicts with the updated source. can u please check and fix it?

**Review by Nonsocial9 — CHANGES_REQUESTED** [review]
No, Just No it doesnt work

**Comment by Jay420blaze** [comment]
plz fix for new update

**Comment by wemanzoz** [comment]
@Metaphysical1 fix pls yesmen

**Comment by wemanzoz** [comment]
Problem is on StaticData.h stuffs, any1 willing to help fix?

**Comment by n0verify** [comment]
> Problem is on StaticData.h stuffs, any1 willing to help fix?

add me on discord, n0verify#6666
unrelated, but i see you have my old osiris paste in your forks :P ftp_loader

**Comment by wemanzoz** [comment]
> n0verify#6666

xD yeahh, my older build has some features from ftp

**Comment by clashys** [comment]
doesn´t work for now. hopefully soon update (03-23-2022)

**Comment by gunsh1p** [comment]
@Metaphysical1
Hello man. Would you like to update with coll option? I can't fix some aspects myself, so I'd like to see your solution

**Comment by Coffyyy** [comment]
Can you make my life easy and just upload the InventoryChanger.cpp with you're code in it too?

**Review by IamUndetected — COMMENTED** [review]
p100

**Comment by HanabiHvH** [comment]
image

any idea how to fix this?

**Comment by Septixx** [comment]
when i compile and run it says "cannot find pattern #12" and when i press ok csgo closes couldnt find a solution and im not at all good at coding

**Comment by xuhlfps** [comment]
how would one go about pasting this into the new version?

**Review by IamUndetected — APPROVED** [review]
p100

**Review by IamUndetected — APPROVED** [review]

**Comment by PaulAndreiRO** [comment]
dosen t work

**Pull request closed without merging**
