### PR TITLE
Add more UTF-8 to ImGui Glyph Ranges

### PR DESCRIPTION
**Pull request by ClaudiuHKS**
To support Sunset Storm 壱 and Sunset Storm 弐 paint kits.

### CODE REVIEW

**Comment by wemanzoz** [comment]
kinda swag

**Comment by mkot2** [comment]
ok

**Review by mkot2 — APPROVED** [review]

**Review by danielkrupinski — COMMENTED** [review]
Tahoma font which is used in GUI doesn't contain those characters, so they still won't appear correctly. There is also a `M4A4 | 龍王 (Dragon King)` skin which has chinese characters in its name.

**Comment by ClaudiuHKS** [comment]
> Tahoma font which is used in GUI doesn't contain those characters, so they still won't appear correctly. There is also a `M4A4 | 龍王 (Dragon King)` skin which has chinese characters in its name.

You're right, I've noticed that. I've just created this **PR** as a _completion_. Of course, I don't expect `100 %` to be merged. Can be closed when the entire issue gets fixed. Maybe you should replace the font with a more **complex** one. 

`/Steam/steamapps/common/Counter-Strike Global Offensive/platform/vgui/fonts/xarialuni.ttf`, for example. Your decision, anyway.

**Review by danielkrupinski — COMMENTED** [review]
Now **Desert Eagle | Sunset Storm 弐**, **Desert Eagle | Sunset Storm 壱** and **M4A4 | 龍王 (Dragon King)** display correctly.

**Pull request closed without merging**
