### PR TITLE
Bypass sv pure, Fake latency and better backtracking

### PR DESCRIPTION
**Pull request by notgoodusename**
For the new method of hooking

### CODE REVIEW

**Comment by tirziz** [comment]
you should separate each feature. Its easier when someone take a look.

**Comment by notgoodusename** [comment]
> you should separate each feature. Its easier when someone take a look.

should i publish a separate pr for bypass sv pure?

**Comment by m0nsterJ** [comment]
@notgoodusename I am very interested in your Resolver code. Could you publish it soon please? I know its more of a Legit AA resolver, but its better than nothing!

**Comment by notgoodusename** [comment]
> @notgoodusename I am very interested in your Resolver code. Could you publish it soon please? I know its more of a Legit AA resolver, but its better than nothing!

can you send me your discord? i want to add you

**Comment by m0nsterJ** [comment]
[monsterJ]#1198

**Comment by unnamed01X** [comment]
what "Bypass sv pure" is doing? could you explain please?

**Comment by notgoodusename** [comment]
https://developer.valvesoftware.com/wiki/Pure_Servers

**Comment by afulsamet** [comment]
Works pretty with the MinHook(no-crash).

```cpp
class MinHook {
public:

    ...

    bool isInit() {
        return this->base != nullptr;
    }

    ...

private:
    void* base;
};
```

```cpp
if (!hooks->networkChannel.isInit()) {
	NetworkChannel* network = interfaces->engine->getNetworkChannel();

	if (network && interfaces->engine->isInGame())
	{
		Backtrack::UpdateIncomingSequences(true);
		hooks->networkChannel.init(network);

		hooks->networkChannel.hookAt(46, SendDatagram);
		MH_EnableHook((*reinterpret_cast<void***>(network))[46]);
	}
}

Backtrack::UpdateIncomingSequences();
```

**Comment by aljawary** [comment]
> Works pretty with the MinHook(no-crash).
> 
> ```c++
> class MinHook {
> public:
> 
>     ...
> 
>     bool isInit() {
>         return this->base != nullptr;
>     }
> 
>     ...
> 
> private:
>     void* base;
> };
> ```
> 
> ```c++
> if (!hooks->networkChannel.isInit()) {
> 	NetworkChannel* network = interfaces->engine->getNetworkChannel();
> 
> 	if (network && interfaces->engine->isInGame())
> 	{
> 		Backtrack::UpdateIncomingSequences(true);
> 		hooks->networkChannel.init(network);
> 
> 		hooks->networkChannel.hookAt(46, SendDatagram);
> 		MH_EnableHook((*reinterpret_cast<void***>(network))[46]);
> 	}
> }
> 
> Backtrack::UpdateIncomingSequences();
> ```

Make a pull pls

**Comment by afulsamet** [comment]
> Make a pull pls

you can see the full code on my fork.

**Comment by RyDeem** [comment]
if anyone want extended backtrack without bypass sv pure in one commit =
 https://github.com/RyDeem/Osiris/tree/ExtendedBacktrackTest

**Comment by playday3008** [comment]
@notgoodusename get compiler errors
image
image

**Comment by playday3008** [comment]
and create pls sv_pure bypass pr separately

**Comment by notgoodusename** [comment]
use the lastest hooks, there is a new folder containing vmtswap, minhook and vmthook, if you only use vmt and dont have minhook just put vmt instead of vmtswap

**Comment by RyDeem** [comment]
>  get compiler errors

those errors are fixed in my version of the pull request here = #1922

**Comment by playday3008** [comment]
@RyDeem  ok, how can i fix this
`auto original = hooks->networkChannel.getOriginal<bool, NetworkMessage&, bool, bool>(40, msg, bForceReliable, bVoice);`

**Comment by notgoodusename** [comment]
`auto original = hooks->networkChannel.getOriginal<bool, NetworkMessage&, bool, bool, 40>(msg, bForceReliable, bVoice);`

**Comment by playday3008** [comment]
> `auto original = hooks->networkChannel.getOriginal<bool, NetworkMessage&, bool, bool, 40>(msg, bForceReliable, bVoice);`

No, that's not working

image

**Comment by RyDeem** [comment]
bro i linked the fix, but whatever here
OLD
`    auto original = hooks->networkChannel.getOriginal<int, void*>(46, datagram);`
NEW
`    auto original = hooks->networkChannel.getOriginal<int, 46, void*>( datagram);`

in Hooks.cpp line 124

Or see https://github.com/danielkrupinski/Osiris/commit/6ed1aa363941dd4aafce2656674ba9d372d47a3b

**Comment by playday3008** [comment]
Ok, I saw that, but I had a question about another function, and now I resolve this problem

**Comment by notgoodusename** [comment]
`auto original = hooks->networkChannel.getOriginal<bool, 40,  NetworkMessage&, bool, bool>(msg, bForceReliable, bVoice);`
should work

**Comment by playday3008** [comment]
Yep, it's true

**Comment by braken1** [comment]
is this 400ms backtrack?

**Comment by notgoodusename** [comment]
> is this 400ms backtrack?

yea

**Comment by braken1** [comment]
its good but it lags so much when i see enemy players

**Comment by playday3008** [comment]
Crash if I use "Unhook", need to use MinHook, instead of VmtSwap

**Comment by AntonDoil** [comment]
Be aware and dont use VmtSwap, u'll be propably fine with MinHook.

**Comment by BaiAlbert** [comment]
Can you send me only the bypass sv pure code?
BaiAlbert#0819

**Comment by HackermanX** [comment]
> Works pretty with the MinHook(no-crash).
> 
> ```c++
> class MinHook {
> public:
> 
>     ...
> 
>     bool isInit() {
>         return this->base != nullptr;
>     }
> 
>     ...
> 
> private:
>     void* base;
> };
> ```
> 
> ```c++
> if (!hooks->networkChannel.isInit()) {
> 	NetworkChannel* network = interfaces->engine->getNetworkChannel();
> 
> 	if (network && interfaces->engine->isInGame())
> 	{
> 		Backtrack::UpdateIncomingSequences(true);
> 		hooks->networkChannel.init(network);
> 
> 		hooks->networkChannel.hookAt(46, SendDatagram);
> 		MH_EnableHook((*reinterpret_cast<void***>(network))[46]);
> 	}
> }
> 
> Backtrack::UpdateIncomingSequences();
> ```

how do u hook this using minhook you onlyu initialized hooks
it would be nice if someone told me how to hook senddatagram with minhook as well

**Comment by wemanzoz** [comment]
please make sv_pure on different pr

**Comment by Zvondaaa** [comment]
> and create pls sv_pure bypass pr separately

+1

**Pull request closed without merging**
