### PR TITLE
Small change in spectator list and pearlescent chams fix

### PR DESCRIPTION
**Pull request by NobodyNeon**
small changes

### CODE REVIEW

**Comment by tirziz** [comment]
is it just change the color?

**Review by Nonsocial9 — APPROVED** [review]
Works like a charm ,Thank you!

**Comment by NobodyNeon** [comment]
> is it just change the color?

what do you mean?

**Comment by TurkLee** [comment]
$basetexture vgui/white would be better instead of $basetexture vgui/white_additive

**Comment by Shuvi-Moro** [comment]
thnx

**Pull request closed without merging**
