### PR TITLE
Added Human BHOP

### PR DESCRIPTION
**Pull request by jimbob88**
Added [kerncs' implementation of human bhop](https://github.com/danielkrupinski/Osiris/issues/1123#issuecomment-588666316) with a GUI section added to the MISC gui

### CODE REVIEW

**Comment by MinecraftGoodGame** [comment]
How do you set max_hops_hit?

**Comment by twangsriprasoet** [comment]
@MinecraftGoodGame 
change " ImGui::InputInt("Max Hops Hit", &config.misc.hops_restricted_limit); " in GUI.cpp
to
" ImGui::InputInt("Max Hops Hit", &config.misc.max_hops_hit); "

**Comment by MinecraftGoodGame** [comment]
Ikr I just wanted to point it out

**Comment by twangsriprasoet** [comment]
oke ;)

**Comment by AbdallahMehiz** [comment]
it resets everytime i reload config ._.

**Comment by twangsriprasoet** [comment]
just do a little things in Config.cpp...

**Comment by jimbob88** [comment]
oops, thanks gius for pointing that out, I'll fix it now!

**Comment by jimbob88** [comment]
I hope this should've fixed the issues!
If there are any issues simply tell me and i'll fix them asap

**Comment by jimbob88** [comment]
Hi guys,
as seen as this doesn't seem to be pushed into the main branch of Osiris, I am going to keep this version updated with an [automatic fork updating piece of software](https://wei.github.io/pull), and every few days or when I notice an update come through I will rebuild Osiris for the following instruction sets:
 * IA32
 * SSE2
 * AVX
 * AVX2

If there are any issues with the implementation feel free to drop me an issue and I'll fix it as soon as I can :)
It should be noted, if Osiris implements its own version of the Human Bhop (other than Kerncs' implementation that mine is based on), I will either archive this repository or I will leave the Pull software running on it so as to allow it to keep up to date with the current versions, yet it will no longer recieve any new compiles...

Hope this fork can help y'all out,
Jim

**Comment by vsnrytune** [comment]
What does the restricted limit do?

**Comment by vsnrytune** [comment]
??

**Comment by OsirisUser** [comment]
needs to be updated

**Pull request closed without merging**
