### PR TITLE
correct build and inject instructions

### PR DESCRIPTION
**Pull request by Ferryistaken**

### CODE REVIEW

**Comment by newcommerdontblame** [comment]
Daniel would have added this if he wanted to because they made this. Current one is fine people can use whatever they want to inject

**Comment by Ferryistaken** [comment]
you cannot use whatever injector. I tried xenos and project hacker 2 and they both didn't work

**Comment by newcommerdontblame** [comment]
process hacker fixed after updates and never heard xenos before probably usong old method

**Comment by Ferryistaken** [comment]
Maybe you should include that after you say to just use any injector? It's not like it can affect the project in a bad manner

**Comment by bastquu** [comment]
@Ferryistaken mad?

**Comment by Ferryistaken** [comment]
@bastquu  not really just trying to help the project. People who don't know shit about cheats won't be able to inject this

**Review by danielkrupinski — COMMENTED** [review]
I do not want to advertise specific dll injector. Also launching as an administrator is not always mandatory.

**Comment by Ferryistaken** [comment]
i just thought to put it there since I couldn't inject it and had to open an issue, some guy told me to use that injector and it finally worked

**Pull request closed without merging**
