### PR TITLE
README: Remove FakePrime, Add Aspect Ratio

### PR DESCRIPTION
**Pull request by R3nzTheCodeGOD**

### CODE REVIEW

**Comment by Xonn1com** [comment]
obraz
Osiris already has aspect ratio

**Comment by mkot2** [comment]
> 
> 
> obraz
> Osiris already has aspect ratio

look at the changes

**Comment by wemanzoz** [comment]
@danielkrupinski

**Review by danielkrupinski — APPROVED** [review]

**Comment by danielkrupinski** [comment]
Thanks!

**Pull request merged**
