### PR TITLE
Improve fake ban

### PR DESCRIPTION
**Pull request by Nep-Timeline**
u don't need reconnect to the server, but only ur team can see it.

### CODE REVIEW

**Comment by b0yk3x** [comment]
why? what's the problem with fakeban?

**Comment by 2933968621** [comment]
> why? what's the problem with fakeban?

if u like original, u can ignore this change

**Comment by 2933968621** [comment]
> why? what's the problem with fakeban?

i think it's better, not fix

**Comment by b0yk3x** [comment]
lol i thought this was issues

**Pull request closed without merging**
