### PR TITLE
Close This//Close This//Thank you

### PR DESCRIPTION
**Pull request by RyDeem**
Updated to commit  3,476 // Fix game window not restoring after pressing Win + D with GUI open

To see all changes check https://github.com/danielkrupinski/Osiris/compare/master...RyDeem:master

Changed visuals window and added features.

Thank you coders!
#835 By ZerGo0 // Hitmarker Damage Indicator
#894 By agshaidun // Spec List on other players
#730 By JDeu // Draw All Backtrack Tick Chams
#584 By effex1337 // View Model Offset XYZ (I added knife position indipendent as well)
Also added:
Fullbright
No weapon sway on movement
Ragdoll gravity customize
Hit Damage menu integration (still WiP so not perfect as i dont really understand where ZerGo0's code calls for the damage text movement direction.)
cl_righthand in visuals menu for weapons or knife independent of eachother.
weapon position xyz resets on bomb equip to default 000, and back to your weapon/knife values on switch. (no toggle, just on, i can make togglable if needed)

Check the Visuals menu ingame! 💃

### CODE REVIEW

**Comment by thomas0aotian** [comment]
cool

**Comment by xAkiraMiura** [comment]
If daniel wanted the features in the game he could have just accepted the original pull requests, as such this is a useless pull with a high chance to get declined because it is too convoluted.

Your commit names are absolutely useless, commit names should give an overview of what is changed by "gg" tells us nothing and makes me not at all want to read all your changes. I can't even understand half of the changes because you offered no explaination for them in the commit message.

Also I bet that you manually merged the branches rather than using `git merge`, this is not good practice and can cause errors.

**Comment by RyDeem** [comment]
@xAkiraMiura  There are no errors.
read files changed for files changed, not commits.

**Comment by RyDeem** [comment]
@xAkiraMiura I hove modified each pull request to have full config saving loading and fixed a few things, this is not a reupload. i even credited people.

**Comment by xAkiraMiura** [comment]
There still is no reason to make a seperate PR when each PR can be merged individually and is better maintained by the original author.
You don't to mention people in every comment, whenever someone comments or get mentioned then they get subscribed to the thread.

**Comment by RyDeem** [comment]
> There still is no reason to make a seperate PR when each PR can be merged individually and is better maintained by the original author.
> You don't to mention people in every comment, whenever someone comments or get mentioned then they get subscribed to the thread.

ok, sorry about the mention stuff, im new.
But about making this PR, its because i have added features not on the original pull, for example the viewmodel mover xyz is much upgraded from what it was initialy, it has more funcionality, for example there is seperate viewmodel locations stored for knife or weapon. its not just a collection/compilation, its trying to get good and cool features on the main branch.

Im sorry if ive done some things wrong as in not using git clone, but if those can be fixed/looked past i think this is a good update.

**Comment by tirziz** [comment]
You can close this yourself đue

**Comment by agshaidun** [comment]
Come on guys, can we all just enjoy and appreciate his work :D

**Comment by Chopard** [comment]
How does it work? -Ping Based Backtrack

**Comment by RyDeem** [comment]
Sorry, how do i close this? i got a cleaned up version thats synced and cloned from github. I think i

**Comment by RyDeem** [comment]
MOVED TO https://github.com/danielkrupinski/Osiris/pull/960

**Pull request closed without merging**
