### PR TITLE
StandaloneRCS, randomized and with ignore shots

### PR DESCRIPTION
**Pull request by steel4me**
I dont wan't to waste more time on writing things in issues or pull requests here, doesn't makes sense.
No matter what you write, a large part of the people here always know everything better or ignore informations. do what you want with it or leave it.

### CODE REVIEW

**Comment by steel4me** [comment]
rly amazing

**Comment by vsnrytune** [comment]
How is this different from your other standalone rcs, is it better?

**Comment by steel4me** [comment]
yes but i dont know what daniel is planning right now, watch latest commits on aimbot from him.

**Comment by AbdallahMehiz** [comment]
the recoil control factors (X,Y) has been removed.
maybe update the PR?

**Comment by steel4me** [comment]
at the moment i dont use osiris anymore. i wrote why in many issue tabs. when i have time and get bored i will have a look at it for you.

**Comment by vsnrytune** [comment]
> at the moment i dont use osiris anymore. i wrote why in many issue tabs. when i have time and get bored i will have a look at it for you.

Could you do it?

**Comment by Hunterswat** [comment]
> > no momento eu não uso mais osíris. eu escrevi por que em muitas abas de edições quando eu tiver tempo e ficar entediado, darei uma olhada nisso para você.
> 
> Você poderia fazer isso?

I can add, discord: MunhoZ # 4150

**Pull request closed without merging**
