### PR TITLE
Add multiple config support

### PR DESCRIPTION
**Pull request by Fizz3**
I've attempted to retain old configs by checking for it in the Config constructor, so hopefully no one losses theirs. I haven't done any work in C++ before, so hopefully this is all up to standard. Added some custom ImGui controls so I could get the window looking how I wanted it to (the hardcoded text paddings need to be set to the corresponding style variable).

### CODE REVIEW

**Comment by Fizz3** [comment]
I think I've fixed what you're looking for, not sure how I didn't use std::filesystem in the first place.

**Comment by danielkrupinski** [comment]
Still seems overcomplicated to me.

**Comment by Fizz3** [comment]
Ah well, happy for you to do whatever with it. What looks complicated for you? I could get rid of the old config support, and apart from that it seems straightforward to me.

**Comment by effexcs** [comment]
I never had any configs to begin with so, i guess nothing was complicated, i made it work in the 1st time.

**Comment by danielkrupinski** [comment]
Merged, thanks for your contribution.

**Pull request merged**
