### PR TITLE
Draw AimBot FOV

### PR DESCRIPTION
**Pull request by blackMasterLord**

### CODE REVIEW

**Comment by floydGG** [comment]
This feature affect Aimbot smoothing somehow, i've tried the lowest smoothing value and the highest.
But Aimbot looks snappy af.

**Review by danielkrupinski — COMMENTED** [review]
It definitely should be implemented inside Aimbot module (Aimbot.cpp)

**Review by Frouk3 — CHANGES_REQUESTED** [review]
Update to the latest Osiris version

**Comment by Wichtxg** [comment]
The hooks.cpp datei is different

**Comment by Xtendera** [comment]
> The hooks.cpp datei is different
> 
> It isn't working

I have a solution for you. It is very easy, just click "Update" and it will work. Just the way you like it.

Link: [Click Me (Very EASY)!!!](https://www.w3schools.com/cpp/)

**Pull request closed without merging**
