### PR TITLE
Added Ammo to Weapon ESP [AGAIN]

### PR DESCRIPTION
**Pull request by Oly-UK**
Re opened for a third time because i am an idiot, but this one works and the commits aren't fucked up anymore.

Did it from an alt account so i can have seperate PRs

Preview: 
79074119-6ceac600-7ce2-11ea-8478-c3f82faa1b20

### CODE REVIEW

**Comment by Oly-UK** [comment]
@danielkrupinski check it out

**Comment by xAkiraMiura** [comment]
branches are a thing that exist, btw.
if you view [ZerGo0's ](https://github.com/ZerGo0/Osiris) or my forks we use branches to make multiple PRs with one account.

**Comment by danielkrupinski** [comment]
I think weapon name should be moved to the top of the box. Also you should check if clip isn't -1 to not display ammo on grenades or bomb.

**Comment by Oly-UK** [comment]
> I think weapon name should be moved to the top of the box. Also you should check if clip isn't -1 to not display ammo on grenades or bomb.

okay will make these changes



> branches are a thing that exist, btw.
> if you view [ZerGo0's ](https://github.com/ZerGo0/Osiris) or my forks we use branches to make multiple PRs with one account.

oh okay awesome thank you so much <3

**Comment by Oly-UK** [comment]
image
@danielkrupinski

**Comment by moonm00n** [comment]
weapon name text is too close to the box in my opinion

**Comment by unnamed01X** [comment]
[http://prntscr.com/s2ih30](url)

What's that shit in the middle? any ideas?

**Comment by Oly-UK** [comment]
@wirebruh yeah true

@unnamed01X no clue but that's not even possible to have been caused by my PR lol

**Comment by wirebruh** [comment]
@Oly-UK wanna collab on PRs with visual stuff?

**Comment by danielkrupinski** [comment]
Thank you for the contribution!

**Pull request merged**
