### PR TITLE
Changes to the autostrafe

### PR DESCRIPTION
**Pull request by ZaUserA**
Some small changes to the osiris' autostrafe to make it directional because I saw people complaining about it (and I also had some free time).

### CODE REVIEW

**Comment by hrna94** [comment]
GOOD JOB!

**Comment by Shuvi-Moro** [comment]
> This works 9999/100 works so much better now

What exactly is better about this?

**Comment by mkot2** [comment]
> > This works 9999/100 works so much better now
> 
> What exactly is better about this?

autostrafe now works when you bhop sideways and backwards

**Comment by jmplpark** [comment]
it keeps saying 'identifier vector is undefined'

**Pull request closed without merging**
