### PR TITLE
add fakePrime

### PR DESCRIPTION
**Pull request by Nep-Timeline**
if not, switch to the match ui
TIPS:this just fake, if u toggle to RANKED MATCH,ur match is still not unranked
but if player in ur room, he see u is a prime player
(linux is not work)

### CODE REVIEW

**Comment by SunzBody** [comment]
visible for others ?

**Comment by SunzBody** [comment]
good job !

**Comment by acey1337** [comment]
nice one

**Comment by Callum151800** [comment]
It's working...But ranks are missing. Can you update so that ranks can be displayed? (Maybe we can set our rank and how many matches we win)

**Comment by 2933968621** [comment]
> It's working...But ranks are missing. Can you update so that ranks can be displayed? (Maybe we can set our rank and how many matches we win)

this just fake, your match is unranked, if you wanna get ranks, you can try use fakeprime and profilechanger #2503

**Review by Callum151800 — APPROVED** [review]

**Comment by ledyyq** [comment]
may i ask where is the feature located in the menu?

**Comment by 2933968621** [comment]
> may i ask where is the feature located in the menu?
um... misc

**Pull request closed without merging**
