### PR TITLE
Add Github workflow to automatically build

### PR DESCRIPTION
**Pull request by robootgit**
Hi

This patch adds a Github workflow that automatically builds Osiris when changes are pushed or any pull request is created. This is a great way to weed out low quality pull requests. If you want, you can even configure the workflow to automatically upload a compiled DLL to https://github.com/danielkrupinski/Osiris/releases.

### CODE REVIEW

**Comment by barbadully** [comment]
sorry for being retarded, but what exactly do I have to do to make this work? haha, great commit nontheless

**Comment by effex1337** [comment]
It just builds the dll when some change is made and auto uploaded

**Comment by robootgit** [comment]
> sorry for being retarded, but what exactly do I have to do to make this work? haha, great commit nontheless

You don't have to do anything, the build is done automatically on a GitHub server.

**Comment by rafalohaki** [comment]
+1

**Comment by hxotic** [comment]
+1

**Comment by danielkrupinski** [comment]
Thanks! Let's see how it works out.

**Pull request merged**
