### PR TITLE
Added sv pure bypass

### PR DESCRIPTION
**Pull request by notgoodusename**
Havent tested on linux

### CODE REVIEW

**Comment by wemanzoz** [comment]
pog

**Comment by mkot2** [comment]
doesnt the sendnetmsg thing work too?

**Comment by notgoodusename** [comment]
it does but its not as consistent as this method

**Comment by 3Ld4D** [comment]
fileSystem is an interface.

filesystem_stdio.dll -> VFileSystem017

**Comment by notgoodusename** [comment]
> fileSystem is an interface.
> 
> filesystem_stdio.dll -> VFileSystem017

cant update it rn, but will do later if possible

**Comment by wemanzoz** [comment]
@notgoodusename broken after new osiris update :/

**Comment by pparadoxx** [comment]
doesn't work btw

**Pull request closed without merging**
