### PR TITLE
Customizable Damage Indicator

### PR DESCRIPTION
**Pull request by grey-stack**
Inspired by @ZerGo0

### CODE REVIEW

**Comment by doggobot-owner** [comment]
looks awesome if you put max rainbow speed

**Comment by doggobot-owner** [comment]
the time of damage indicator being shown should be changable

**Comment by grey-stack** [comment]
> the time of damage indicator being shown should be changable

Like how long the indicator stays there for?

**Comment by Heyter** [comment]
> the time of damage indicator being shown should be changable

`hitMarkerInfo.push_back({memory->globalVars->realtime + 0.6f , event->getInt("dmg_health")});`

**Pull request closed without merging**
