### PR TITLE
added noAimPunch feature to visuals menu

### PR DESCRIPTION
**Pull request by mindofenzo**
also increased the size of the tab so it wouldnt cut off the other checkboxes.

video of it working: https://youtu.be/CRPXQwNmais

### CODE REVIEW

**Comment by danielkrupinski** [comment]
It's basically the same as "No visual recoil".

**Comment by mindofenzo** [comment]
The code is the same, but keeps the visual recoil on your weapon. Something about turning off visual recoil throws off my aim.

**Comment by danielkrupinski** [comment]
I think you should just modify https://github.com/danielkrupinski/Osiris/blob/c909cae99e3531ef4329bb9345e9433524c55f51/Osiris/Hacks/Visuals.cpp#L60 function.

**Comment by tirziz** [comment]
This is actually useful, I use this when playing classic game, and completely remove visual recoil when playing Zombie escape

**Pull request closed without merging**
