### PR TITLE
Left, right and bottom HP and AR bar positions

### PR DESCRIPTION
**Pull request by Oly-UK**
Took me 3 days for my dumbass to figure out how to draw horizontally but i finally did it and i want to release some of my stress by sharing my work with you, so here you are :)

With this pull request you can choose the position of the health and armor bars between 3, left, right and bottom of the box. And don't worry i've taken care of the side text and bottom text to make sure the bars and text don't overlap!

Video: 
https://streamable.com/jg4xqd

edit: going to upload another commit in a second to make the bottom bars larger

edit #2: everything should be perfect now, enjoy :)

@danielkrupinski give this a look, it's pretty cool

### CODE REVIEW

**Comment by notmugi** [comment]
it looks great! if i could suggest 1 thing however, unify the thicknesses between the bottom, left, and right versions of each. just pixel check them and make sure they're all the same width :)

**Comment by Oly-UK** [comment]
image
my second commit made them a little thicker but i just realised they are not exactly the same width, will fix that now @notmugi 👍

**Comment by Oly-UK** [comment]
actually it's probably best i dont because they get thicker at distance 
image
the current thickness is not perfectly the same but not a huge issue imo

**Comment by rosesware** [comment]
> actually it's probably best i dont because they get thicker at distance
> image
> the current thickness is not perfectly the same but not a huge issue imo

But still not having the same width.

**Comment by playday3008** [comment]
@Oly-UK ur the best man, maybe you can help me with it, because i'm too stupid to add it to my [modified ](https://github.com/playday3008/Osiris/tree/beta-v2) code, if you can, just create pull request to my repo, thx

**Comment by Oly-UK** [comment]
@rosesware pixel checked, they are the same now

**Comment by Oly-UK** [comment]
idk why the esp.cpp is now fucked, i guess im not commiting right, but if you just click view file you can C+P it

**Comment by wirebruh** [comment]
@Oly-UK can you show a screenshot of it fixed?

**Comment by Oly-UK** [comment]
image
image
image
turns out i was a pixel off :/

**Pull request merged**
