### PR TITLE
Remove Blur in HUD (Panorama Blur)

### PR DESCRIPTION
**Pull request by Novalaki**
This is my way of removing panorama blur
example: https://www.youtube.com/watch?v=QD1n97i4TEU

### CODE REVIEW

**Comment by thomas0aotian** [comment]
Yeah this looks cool but don't know ehy ppl beed it tho xD

**Comment by thomas0aotian** [comment]
Lmao dude it's literally a cvar

**Comment by thomas0aotian** [comment]
Ez

**Comment by Novalaki** [comment]
Yeah it is a cvar. and yeah people just want it because it looks cool

**Comment by xsincbt** [comment]
its only ingame but not on main menu

**Comment by matt1tk** [comment]
Like noobdog :D

**Comment by danielkrupinski** [comment]
Thanks!

**Pull request merged**
