### PR TITLE
Autoscope fix

### PR DESCRIPTION
**Pull request by mkot2**
simple fix for autoscope

### CODE REVIEW

**Comment by notgoodusename** [comment]
there is a way easier to do this

**Comment by mkot2** [comment]
> there is a way easier to do this

how does it get simpler than this

**Comment by notgoodusename** [comment]
this
```
if (config->ragebot[weaponIndex].scopedOnly && activeWeapon->isSniperRifle() && !localPlayer->isScoped() && localPlayer->flags() & 1 ) {
if (config->ragebot[weaponIndex].autoScope)
        cmd->buttons |= UserCmd::IN_ATTACK2;
   return;
}
```
on [here](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L165)

**Comment by afulsamet** [comment]
Another method

```cpp
if (cmd->buttons & UserCmd::IN_ATTACK && config->aimbot[weaponIndex].autoScope && activeWeapon->isSniperRifle()) {
    if (!localPlayer->isScoped()) {
        cmd->buttons &= ~UserCmd::IN_ATTACK;
        cmd->buttons |= UserCmd::IN_ZOOM;
    }
}
```

```cpp
struct UserCmd {
    enum {
        ...
        IN_ZOOM = 1 << 19,
        ...
    };
};
```

**Comment by enescglyn** [comment]
the maintainer of this repo makes commits everyday but he ignores pull requests

**Comment by mkot2** [comment]
> the maintainer of this repo makes commits everyday but he ignores pull requests

yep

**Comment by danielkrupinski** [comment]
It breaks "Auto shot" with low "Max angle delta" values.

**Comment by enescglyn** [comment]
Then why you made autoscope if its not made to work?

**Comment by newcommerdontblame** [comment]
bruh fix it or remove from gui then

**Comment by mkot2** [comment]
> It breaks "Auto shot" with low "Max angle delta" values.

what does max angle delta even do

**Comment by infinity1211** [comment]
@mkot2  maximum viewangles change per tick

**Comment by mkot2** [comment]
> @mkot2 maximum viewangles change per tick

oh for like aimstep?

**Pull request closed without merging**
