### PR TITLE
Clean FPS and PING flags

### PR DESCRIPTION
**Pull request by xpossed-you**

### CODE REVIEW

**Comment by danielkrupinski** [comment]
I'll wait to see what others think.

**Comment by playday3008** [comment]
Maybe screenshot to compare?

**Comment by playday3008** [comment]
If small screen ok, else, anyway

**Comment by xpossed-you** [comment]
wow thanks for the approval, this is my first pull request

**Comment by xpossed-you** [comment]
closed because conflicting files, will come back soon

**Comment by toprak1224** [comment]
this is my first pull request thxx

**Pull request closed without merging**
