### PR TITLE
Added Custom View model Offset (Highly Requested)

### PR DESCRIPTION
**Pull request by effex1337**
I tried an unique approach for saving fps as it constantly changes value but if i keep a button it does its job but its a bit annoying. @danielkrupinski Please let me know your opinion.

### CODE REVIEW

**Comment by deprale** [comment]
Why not add a button like I did? :) Also static ConVar* is not needed.
You can just do the default static auto ones because theres a overrideview hook so you don't have to use the sv_competitive_minspec meme...
#574 check my reply :P

**Comment by effex1337** [comment]
It does its job so yeah and did you mean checkbox by `Why not add a button like I did? :) `

**Comment by effex1337** [comment]
and also i did with memory usage in mind.

**Comment by effex1337** [comment]
@danielkrupunski can u please take a look?

**Comment by deprale** [comment]
yeah i meant a checkbox cuz then every single time u inject u will have x y z offset all set to 0 instantly which is gay.
at least if u inject and have a checkbox u dont have this slight annoyance. 
also could be better if you just made a struct with saved original x y z structs and if you disable the checkbox just return the original value to the cvars including the callbacks :P but yea thats a bit more work and generally not needed for most people

**Comment by xAkiraMiura** [comment]
how about you check if any of the values have changed across function calls and run it if they have? that would solve the issue of low fps due to constantly updating a cvar but also not require any user intervention.

**Comment by DerLi1** [comment]
How can i do auto update?

**Comment by xAkiraMiura** [comment]
you need to understand basic logic first. 

if (current == previous) // it changed
previous = current

**Comment by RyDeem** [comment]
> you need to understand basic logic first.
> 
> if (current != previous) // it changed
> previous = current

Sorry for necro or whatever but

is this code better? 

`////
void Visuals::ViewmodelXYZ() noexcept {

    if (!localPlayer)
        return;

    int viewmodel_x = 0; int viewmodel_y = 0; int viewmodel_z = 0; int minspec = 0;
    interfaces->cvar->findVar("viewmodel_offset_x")->setValue(viewmodel_x);
    interfaces->cvar->findVar("viewmodel_offset_y")->setValue(viewmodel_y);
    interfaces->cvar->findVar("viewmodel_offset_z")->setValue(viewmodel_z);
    interfaces->cvar->findVar("sv_competitive_minspec")->setValue(minspec);

    if (minspec != 0)
        interfaces->cvar->findVar("sv_competitive_minspec")->setValue(0);
    if (viewmodel_x != config->visuals.viewmodel_x)
        interfaces->cvar->findVar("viewmodel_offset_x")->setValue(config->visuals.viewmodel_x);
    if (viewmodel_y != config->visuals.viewmodel_y)
        interfaces->cvar->findVar("viewmodel_offset_y")->setValue(config->visuals.viewmodel_y);
    if (viewmodel_z != config->visuals.viewmodel_z)
        interfaces->cvar->findVar("viewmodel_offset_z")->setValue(config->visuals.viewmodel_z);`

minspec is to move the value more then 2.5 each direction

// i dont master the code quote function in this forum xd

**Comment by littlehurensohn** [comment]
Do null callbacks and everything be fine, like that u can risk untrusted.

**Comment by xAkiraMiura** [comment]
> null callbacks 

do you know what a callback is?
C++ doesn't implement null and it is only ever defined in Windows.h as 0
you ment "check for nullptr"

**Pull request closed without merging**
