### PR TITLE
Glow chams & Envmaptint modulation

### PR DESCRIPTION
**Pull request by nullang**
since someone asked for it, i'm not saying it's not pasted because it is.

### CODE REVIEW

**Comment by designer1337** [comment]
this is the ugliest thing i ever seen:
` (*(void(__thiscall**)(int, float, float, float))(*(DWORD*)pVar + 44))((uintptr_t)pVar, col2[0], col2[1], col2[2]);`

just use setVectorValue, it is index **11** in **iMaterialVar** class :)
`pVar ->setVectorValue(col2[0], col2[1], col2[2]);`

**Comment by xAkiraMiura** [comment]
> 
> 
> this is the ugliest thing i ever seen:
> ` (*(void(__thiscall**)(int, float, float, float))(*(DWORD*)pVar + 44))((uintptr_t)pVar, col2[0], col2[1], col2[2]);`
> 
> just use setVectorValue, it is index **11** in **iMaterialVar** class :)
> `pVar->setVectorValue(col2[0], col2[1], col2[2]);`

its a contestent for when i saw someone do `if (!(!(!(!(!(!(!(!(!(!(!(!(booleanSomething))))))))))))) {}`

**Comment by effex1337** [comment]
He just proceeded to make it look even uglier lmao

**Comment by xAkiraMiura** [comment]
1. why is the brace on a new line
2. why is there padding between the start of a block and the end (if you do a brace this is redundant)
3. this is being repeated in every block `(*(void(__thiscall**)(int, float, float, float))(*(DWORD*)pVar + 44))((uintptr_t)pVar,` literally just make it a variable.

**Comment by speedplane2248** [comment]
lol

**Pull request closed without merging**
