### PR TITLE
AddStyle: Added Gold Style

### PR DESCRIPTION
**Pull request by R3nzTheCodeGOD**
# New Gold Style
image
image

### CODE REVIEW

**Comment by wirekuro** [comment]
Can't make this style default, it only switches to gold when I load a cfg. I think you should add something to imgui. Nice work btw.

**Comment by R3nzTheCodeGOD** [comment]
## Make this style default
**change the code in [this line](https://github.com/R3nzTheCodeGOD/Osiris/blob/3177c3ca13b18feefdb71124af91a3a79f5a759e/Osiris/GUI.cpp#L59) to `StyleColorsGold()`, secondly you need to change the variable [here](https://github.com/R3nzTheCodeGOD/Osiris/blob/3177c3ca13b18feefdb71124af91a3a79f5a759e/Osiris/Config.h#L112) to 3.**

After these changes, the gold theme opens by default. @wirekuro

**Comment by notgoodusename** [comment]
cool

**Comment by Xonn1com** [comment]
For everyone that doesn't want to create new built 

<details>
  <summary>edit cfg in file</summary>
  
    "Colors": {
      "Border": [
        0.51,
        0.36,
        0.15,
        1.0
      ],
      "BorderShadow": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "Button": [
        0.51,
        0.36,
        0.15,
        1.0
      ],
      "ButtonActive": [
        0.78,
        0.55,
        0.21,
        1.0
      ],
      "ButtonHovered": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "CheckMark": [
        0.78,
        0.55,
        0.21,
        1.0
      ],
      "ChildBg": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "DragDropTarget": [
        1.0,
        1.0,
        0.0,
        0.9
      ],
      "FrameBg": [
        0.11,
        0.11,
        0.11,
        1.0
      ],
      "FrameBgActive": [
        0.78,
        0.55,
        0.21,
        1.0
      ],
      "FrameBgHovered": [
        0.51,
        0.36,
        0.15,
        1.0
      ],
      "Header": [
        0.51,
        0.36,
        0.15,
        1.0
      ],
      "HeaderActive": [
        0.93,
        0.65,
        0.14,
        1.0
      ],
      "HeaderHovered": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "MenuBarBg": [
        0.11,
        0.11,
        0.11,
        1.0
      ],
      "ModalWindowDimBg": [
        0.2,
        0.2,
        0.2,
        0.35
      ],
      "NavHighlight": [
        0.45,
        0.45,
        0.9,
        0.8
      ],
      "NavWindowingDimBg": [
        0.8,
        0.8,
        0.8,
        0.2
      ],
      "NavWindowingHighlight": [
        1.0,
        1.0,
        1.0,
        0.7
      ],
      "PlotHistogram": [
        0.9,
        0.7,
        0.0,
        1.0
      ],
      "PlotHistogramHovered": [
        1.0,
        0.6,
        0.0,
        1.0
      ],
      "PlotLines": [
        0.61,
        0.61,
        0.61,
        1.0
      ],
      "PlotLinesHovered": [
        1.0,
        0.43,
        0.35,
        1.0
      ],
      "PopupBg": [
        0.08,
        0.08,
        0.08,
        0.94
      ],
      "ResizeGrip": [
        0.21,
        0.21,
        0.21,
        1.0
      ],
      "ResizeGripActive": [
        0.78,
        0.55,
        0.21,
        1.0
      ],
      "ResizeGripHovered": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "ScrollbarBg": [
        0.06,
        0.06,
        0.06,
        0.53
      ],
      "ScrollbarGrab": [
        0.21,
        0.21,
        0.21,
        1.0
      ],
      "ScrollbarGrabActive": [
        0.81,
        0.83,
        0.81,
        1.0
      ],
      "ScrollbarGrabHovered": [
        0.47,
        0.47,
        0.47,
        1.0
      ],
      "Separator": [
        0.21,
        0.21,
        0.21,
        1.0
      ],
      "SeparatorActive": [
        0.78,
        0.55,
        0.21,
        1.0
      ],
      "SeparatorHovered": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "SliderGrab": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "SliderGrabActive": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "Tab": [
        0.51,
        0.36,
        0.15,
        1.0
      ],
      "TabActive": [
        0.78,
        0.55,
        0.21,
        1.0
      ],
      "TabHovered": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "TabUnfocused": [
        0.2832,
        0.2832,
        0.56880003,
        0.8212
      ],
      "TabUnfocusedActive": [
        0.3504,
        0.3504,
        0.6516,
        0.8372
      ],
      "TableBorderLight": [
        0.26,
        0.26,
        0.28,
        1.0
      ],
      "TableBorderStrong": [
        0.31,
        0.31,
        0.45,
        1.0
      ],
      "TableHeaderBg": [
        0.27,
        0.27,
        0.38,
        1.0
      ],
      "TableRowBg": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "TableRowBgAlt": [
        1.0,
        1.0,
        1.0,
        0.07
      ],
      "Text": [
        0.92,
        0.92,
        0.92,
        1.0
      ],
      "TextDisabled": [
        0.44,
        0.44,
        0.44,
        1.0
      ],
      "TextSelectedBg": [
        0.26,
        0.59,
        0.98,
        0.35
      ],
      "TitleBg": [
        0.51,
        0.36,
        0.15,
        1.0
      ],
      "TitleBgActive": [
        0.91,
        0.64,
        0.13,
        1.0
      ],
      "TitleBgCollapsed": [
        0.0,
        0.0,
        0.0,
        0.51
      ],
      "WindowBg": [
        0.06,
        0.06,
        0.06,
        1.0
      ]
    },
</details>

**Comment by techzin** [comment]
Dont edit Imgui sources, add your StyleColorsGold to ImGuiCustom.
edit imgui.h code, will cause problems the moment there is an update on imgui.

**Pull request closed without merging**
