### PR TITLE
Add cases to inventory changer.

### PR DESCRIPTION
**Pull request by wirekuro**
(Still can't open these cases with keys added by inventory changer.)

### CODE REVIEW

**Comment by KurastikO** [comment]
There's some source code that can help you with the problem that you can't open some cases. 

This is the link:
https://github.com/B3akers/csgo-fake-opening/tree/master/csgo-fake-opening

It is very easy to merge this with your commit :)

**Comment by wirekuro** [comment]
> There's some source code that can help you with the problem that you can't open some cases.
> 
> This is the link:
> https://github.com/B3akers/csgo-fake-opening/tree/master/csgo-fake-opening
> 
> It is very easy to merge this with your commit :)

To tell you the truth I never learned coding (im 16) I just pasted this code from daniel's CaseKey update :)

**Comment by wemanzoz** [comment]
i mean, it works. it stay true with the pr name

**Review by danielkrupinski — APPROVED** [review]

**Comment by danielkrupinski** [comment]
Thanks!

**Pull request merged**
