### PR TITLE
Triggerbot hitchance

### PR DESCRIPTION
**Pull request by pubsense**
just 2 lines of code and now triggerbot stop spamming shots

### CODE REVIEW

**Comment by AbdallahMehiz** [comment]
Your code doesn't compile correctly, i think your code should be like this :
`            if (damage >= (config.triggerbot[weaponIndex].killshot ? trace.entity->health() : config.triggerbot[weaponIndex].minDamage)) { 
                if ((!config.triggerbot[weaponIndex].hitChance || (1.0f - (activeWeapon->getInaccuracy())) * 100.f >= config.triggerbot[weaponIndex].hitChanceAmmount)) {
                    cmd->buttons |= UserCmd::IN_ATTACK;
                    lastTime = 0.0f;
                }`
Instead of this:
`                if ((!config.triggerbot[weaponIndex].hitChance || (1.0f - (activeWeapon->getInaccuracy())) * 100.f >= hitchance)) {
                    cmd->buttons |= UserCmd::IN_ATTACK;
                    lastTime = 0.0f;
                }`
tell me if i am correct :")

**Comment by pubsense** [comment]
I forgot to define the hitchance thing. added in last commit @AbdallahMehiz

**Comment by pubsense** [comment]
> Your code doesn't compile correctly, i think your code should be like this :

forgot to add the float value for hitchance also to assign min value and max value for slider in gui

**Comment by streamshark** [comment]
One thing I would note is max inaccuracy threshold and true hitchance are different things. Osiris doesn't currently have true hitchance which involves tracing a bunch of imaginary rays and seeing how many would hit to get a percent estimate of hitting the target, while max inaccuracy method just tells you the current inaccuracy of yourself based on if you are walking, crouched, etc. The major difference here is true hitchance will shoot if you are high inaccuracy but close to the target (likely to hit) for example, while max inaccuracy will shoot no matter the positioning of the target (more resource efficient but can lead to shooting when unlikely to hit). I suggest labeling this is as triggerbot max shot inaccuracy, in the same way it's labeled in the aimbot tab.

**Comment by xAkiraMiura** [comment]
you could probably get away with calculating how large the player is in your view, if you were looking straight at them. a perspective calculation would probably be faster than ray tracing a lot.

**Comment by AbdallahMehiz** [comment]
this might have to be updated because of the latestcommits from daniel

**Pull request closed without merging**
