### PR TITLE
Custom yaw antiaim, more customizable autohop

### PR DESCRIPTION
**Pull request by miropasting**
Also removes the useless desync

### CODE REVIEW

**Comment by Cyk-Fad** [comment]
Too many the same pull LOL

**Comment by newcommerdontblame** [comment]
Is this flicking on gotv?

**Comment by miropasting** [comment]
> 
> 
> Too many the same pull LOL

yea i shouldve probably just took the pr straight from moi's repo since i fucked around with the readme file

**Comment by miropasting** [comment]
> 
> 
> Is this flicking on gotv?

not sure

**Comment by notgoodusename** [comment]
if you have a high ping it will flick

**Comment by newcommerdontblame** [comment]
> 
> not sure

Lol what u mean bro haven't you tried it yet?:DDDD??

**Comment by notgoodusename** [comment]
> Lol what u mean bro haven't you tried it yet?:DDDD??

this isnt for desync

**Comment by miropasting** [comment]
motherfucker just pull the pr

**Comment by notgoodusename** [comment]
> motherfucker just pull the pr

it isnt needed for the cheat

**Comment by miropasting** [comment]
> 
> 
> > motherfucker just pull the pr
> 
> it isnt needed for the cheat

"noo you cant just add useful features to a shit base noo"

**Comment by notgoodusename** [comment]
it isnt useful in anyway because this isnt a rage cheat, also talking to people that way wont get your pr merged

**Pull request closed without merging**
