### PR TITLE
Update offsets

### PR DESCRIPTION
**Pull request by simonsmh**
#1036

### CODE REVIEW

**Comment by ClaudiuHKS** [comment]
Awesome work, thanks!

**Comment by tamas0313** [comment]
Névtelen
Esp Active Weapon isn't working!

**Comment by simonsmh** [comment]
Might be getWeaponData problem. let me debug for a while.

**Comment by rosesware** [comment]
And "Auto wall" is not working.

**Comment by simonsmh** [comment]
@tamas0313 
image
Well I think there should be some problem in `interfaces.localize->find()` that it couldn't find translation? I think it is not related to this pull request.
I force print the name instead to test the result.
```
diff --git a/Osiris/Hacks/Esp.cpp b/Osiris/Hacks/Esp.cpp
index e8d589a8..f513a019 100644
--- a/Osiris/Hacks/Esp.cpp
+++ b/Osiris/Hacks/Esp.cpp
@@ -310,7 +310,10 @@ static void renderWeaponBox(Entity* entity, const Config::Esp::Weapon& config) n
         renderBox(bbox, config);

         if (config.name.enabled) {
-            const auto name{ interfaces.localize->find(entity->getWeaponData()->name) };
+            const size_t cSize = strlen(entity->getWeaponData()->name) + 1;
+            wchar_t *wc = new wchar_t[cSize];
+            mbstowcs(wc, entity->getWeaponData()->name, cSize);
+            const auto name{wc};
             const auto [width, height] { interfaces.surface->getTextSize(config.font, name) };
             interfaces.surface->setTextFont(config.font);
             if (config.name.rainbow)
```

**Comment by notgoodusename** [comment]
this is how daniel does it every update 
https://github.com/danielkrupinski/Osiris/commit/d92e6e0b5039562d7482bea16a89e2b29658d7a8

**Pull request closed without merging**
