### PR TITLE
Deathmatch godmode

### PR DESCRIPTION
**Pull request by debooga**

### CODE REVIEW

**Comment by wemanzoz** [comment]
lol

**Comment by ZokyChecks** [comment]
LOL nice thx :0

**Comment by linuxer9** [comment]
osiris > skeet

**Comment by wemanzoz** [comment]
doesnt work

**Comment by debooga** [comment]
> doesnt work

really? i used it 2 hours ago and it still was working

**Comment by wemanzoz** [comment]
> > doesnt work
> 
> really? i used it 2 hours ago and it still was working

i guess try make a showcase of it, a tutorial on how to use it lol

**Comment by Bakedpurple** [comment]
How does this work are you unkillable or why is it called god mode

**Comment by debooga** [comment]
> How does this work are you unkillable or why is it called god mode

It makes you immune until you shoot. Just look in third person.

**Comment by debooga** [comment]
image
image

**Comment by wemanzoz** [comment]
> > How does this work are you unkillable or why is it called god mode
> 
> It makes you immune until you shoot. Just look in third person.

can you walk with it?

**Comment by debooga** [comment]
> > > How does this work are you unkillable or why is it called god mode
> > 
> > 
> > It makes you immune until you shoot. Just look in third person.
> 
> can you walk with it?

Yes, you just can't shoot.

**Comment by debooga** [comment]
image

**Review by danielkrupinski — APPROVED** [review]

**Comment by danielkrupinski** [comment]
Thanks for your contribution!

**Pull request merged**
