### PR TITLE
Add more tag animation

### PR DESCRIPTION
**Pull request by sserve-kr**
+ Default tag (Animated tag, Clock tag)
+ Reverse tag ( Example tag -> gat elpmaxE )
+ Reverse animation
```
animation
nimationa
imationan
mationani
...
```
+ Reverse tag animation
```
noitamina
oitaminan
itaminano
taminanoi
...
```
+ Auto reverse animation
```
a
an
ani
anim
anime
anim
ani
an
a
```

I'm new at c++, sorry for my poor c++ & coding skill.

### CODE REVIEW

**Comment by sserve-kr** [comment]
Crashing. idk how to fix it.
anybody fix this, please.

**Comment by Cyk-Fad** [comment]
use curtime to do that


...
{
              const auto setclantag = [](const char* tag)
              {
                  static auto set_clantag_fn = reinterpret_cast<int(__fastcall*)(const char*, const char*)>(findas.FindSignatureA("engine.dll", "53 56 57 8B DA 8B F9 FF 15"));

                  set_clantag_fn(tag, tag);
              };

              static auto was_on = false;

              was_on = true;

              static int prevtime;
              static int prevval;


                  if (int(memory->globalVars->currenttime * 3.1) != prevtime)
                  {
                      if (prevval != int(memory->globalVars->currenttime * 3.1) % 31)
                      {
                          prevval = int(memory->globalVars->currenttime * 3.1) % 31;
                          switch (int(memory->globalVars->currenttime * 3.1) % 31)
                          {
                          case 30: { _(s30, "[ShadowWare]"); setclantag(s30); break; }
                          case 24: { _(s24, "[ShadowWar]"); setclantag(s24); break; }
                          case 23: { _(s23, "[ShadowWa]"); setclantag(s23); break; }
                          case 22: { _(s22, "[ShadowW]"); setclantag(s22); break; }
                          case 21: { _(s21, "[Shadow]"); setclantag(s21); break; }
                          case 20: { _(s20, "[Shado]"); setclantag(s20); break; }
                          case 19: { _(s19, "[Shad]"); setclantag(s19); break; }
                          case 18: { _(s18, "[Sha]"); setclantag(s18); break; }
                          case 17: { _(s17, "[Sh]"); setclantag(s17); break; }
                          case 16: { _(s16, "[S]"); setclantag(s16); break; }
                          case 15: { _(s15, "[  -S-  ]"); setclantag(s15); break; }
                          case 14: { _(s14, "[ --S-- ]"); setclantag(s14); break; }
                          case 13: { _(s13, "[-F-S---]"); setclantag(s13); break; }
                          case 12: { _(s12, "[-F-A---]"); setclantag(s12); break; }
                          case 11: { _(s11, "[-F-A-D-]"); setclantag(s11); break; }
                          case 10: { _(s10, "[-F-S-D-]"); setclantag(s10); break; }
                          case 9: { _(s9, "[S"); setclantag(s9); break; }
                          case 8: { _(s8, "[Sh]"); setclantag(s8); break; }
                          case 7: { _(s7, "[Sha]"); setclantag(s7); break; }
                          case 6: { _(s6, "[Shad]"); setclantag(s6); break; }
                          case 5: { _(s5, "[Shado]"); setclantag(s5); break; }
                          case 4: { _(s4, "[Shadow]"); setclantag(s4); break; }
                          case 3: { _(s3, "[ShadowW]"); setclantag(s3); break; }
                          case 2: { _(s2, "[ShadowWa]"); setclantag(s2); break; }
                          case 1: { _(s1, "[ShadowWar]"); setclantag(s1); break; }
                          case 0: { _(s0, "[ShadowWare]"); setclantag(s0); break; }
                          default:;
                          }
                      }
                  }
              
              prevtime = int(memory->globalVars->currenttime);
          }
...

**Comment by sserve-kr** [comment]
changed, but still crashing.
I'm working  on it.

**Comment by sserve-kr** [comment]
I will back when all fixed

**Comment by Cyk-Fad** [comment]
oh

**Comment by unnamed01X** [comment]
did you fix that?

**Comment by sserve-kr** [comment]
no, there's so many error.

**Pull request closed without merging**
