### PR TITLE
Classic Hitmarker

### PR DESCRIPTION
**Pull request by ZerGo0**
Like I said I added the wrong one in the last pull request.

### CODE REVIEW

**Comment by anonymouschicken1111** [comment]
This is even more classic
```
else if (config.visuals.hitMarker == 6)
{
	const auto [width, height] = interfaces.surface->getScreenSize();

	int widthMid = width / 2;
	int heightMid = height / 2;
	
	interfaces.surface->setDrawColor(20, 255, 0, 225);
	interfaces.surface->drawLine(widthMid + 10, heightMid + 10, widthMid + 2, heightMid + 2);
	interfaces.surface->drawLine(widthMid - 10, heightMid + 10, widthMid - 2, heightMid + 2);
	interfaces.surface->drawLine(widthMid + 10, heightMid - 10, widthMid + 2, heightMid - 2);
	interfaces.surface->drawLine(widthMid - 10, heightMid - 10, widthMid - 2, heightMid - 2);
}
```

**Comment by ZerGo0** [comment]
> This is even more classic
> 
> ```
> else if (config.visuals.hitMarker == 6)
> {
> 	const auto [width, height] = interfaces.surface->getScreenSize();
> 
> 	int widthMid = width / 2;
> 	int heightMid = height / 2;
> 	
> 	interfaces.surface->setDrawColor(20, 255, 0, 225);
> 	interfaces.surface->drawLine(widthMid + 10, heightMid + 10, widthMid + 2, heightMid + 2);
> 	interfaces.surface->drawLine(widthMid - 10, heightMid + 10, widthMid - 2, heightMid + 2);
> 	interfaces.surface->drawLine(widthMid + 10, heightMid - 10, widthMid + 2, heightMid - 2);
> 	interfaces.surface->drawLine(widthMid - 10, heightMid - 10, widthMid - 2, heightMid - 2);
> }
> ```

I agree, changed, thanks.

**Comment by anonymouschicken1111** [comment]
> > This is even more classic
> > ```
> > else if (config.visuals.hitMarker == 6)
> > {
> > 	const auto [width, height] = interfaces.surface->getScreenSize();
> > 
> > 	int widthMid = width / 2;
> > 	int heightMid = height / 2;
> > 	
> > 	interfaces.surface->setDrawColor(20, 255, 0, 225);
> > 	interfaces.surface->drawLine(widthMid + 10, heightMid + 10, widthMid + 2, heightMid + 2);
> > 	interfaces.surface->drawLine(widthMid - 10, heightMid + 10, widthMid - 2, heightMid + 2);
> > 	interfaces.surface->drawLine(widthMid + 10, heightMid - 10, widthMid + 2, heightMid - 2);
> > 	interfaces.surface->drawLine(widthMid - 10, heightMid - 10, widthMid - 2, heightMid - 2);
> > }
> > ```
> 
> I agree, changed, thanks.

Happy to help :)

**Comment by danielkrupinski** [comment]
It should be drawn in `PaintTraverse` hook as it uses Surface interface but it seems to be working anyway.

**Comment by ZerGo0** [comment]
> It should be drawn in `PaintTraverse` hook as it uses Surface interface but it seems to be working anyway.

Yes I noticed that when I made the damage indicator that it draws stuff in a blurry way, haven't tested it in `PaintTraverse` yet, not sure if that will mess up the other hit marker effects.

**Comment by xAkiraMiura** [comment]
calling it outside of painttraverse can cause crashes the same way trying to use d3d without beginscene being called first can crash.

**Comment by danielkrupinski** [comment]
I've renamed previous "Hit marker" to "Hit effect". Please update your "Hit marker" as a separate function and do drawing in `PaintTraverse` hook.

**Comment by ZerGo0** [comment]
> I've renamed previous "Hit marker" to "Hit effect". Please update your "Hit marker" as a separate function and do drawing in `PaintTraverse` hook.

Sure, I will update it next weekend.

**Comment by ZerGo0** [comment]
@danielkrupinski #1015 ;)

**Pull request closed without merging**
