### PR TITLE
Custom Skybox

### PR DESCRIPTION
**Pull request by caiocinel**
Just add skybox files in "csgo/materials/skybox", choose "Custom" in Skybox menu and write skyname in input.

### CODE REVIEW

**Comment by xXTOO-HARDXx** [comment]
Good job.

**Comment by ryseDMT** [comment]
Nice one, I added custom skyboxes to my build too, but my way was inferior to yours. I just added them to the source manually. Good job.

**Comment by aljawary** [comment]
not work on official matchmaking : (

**Comment by aljawary** [comment]
doesnt work in official matchmaking

**Comment by barbadully** [comment]
I guess this wouldn't work in official mm, same as with the custom hitmarker sounds...

**Comment by xXTOO-HARDXx** [comment]
@barbadully no, it's not the same case. All hitmarker sounds are custom, they aren't from csgo usually. Check the code

**Comment by jestemgosciem** [comment]
dosen't work for me, help

**Comment by cailloubr** [comment]
Ignore 11/Jun commits

**Comment by jestemgosciem** [comment]
@danielkrupinski why custom skybox doesn't work on normal games(mm, wingman and others)?

**Comment by cailloubr** [comment]
> @danielkrupinski why custom skybox doesn't work on normal games(mm, wingman and others)?

Perhaps https://developer.valvesoftware.com/wiki/Pure_Servers ?

**Comment by xXTOO-HARDXx** [comment]
It won't be anything to do with Pure Servers, a 'pure server' is just a server that requires a TRUE value for sv_pure from each client that joins the server or their connection rejected. So as long as you're ON the server, a Pure Server isn't going to continuously check files or anything similar, afaik.

**Comment by Cyk-Fad** [comment]
nice job

**Comment by cailloubr** [comment]
Living and learning, ty.

**Pull request closed without merging**
