### PR TITLE
TraceToExit fix

### PR DESCRIPTION
**Pull request by voidzer0-development**
Quick rebuild of the function

### CODE REVIEW

**Comment by NiceNem** [comment]
LGTM!

**Comment by voidzero-development** [comment]
All you need to make it work on linux is the signature for isBreakable.
Win32 is \x55\x8B\xEC\x51\x56\x8B\xF1\x85\xF6\x74\x68

**Comment by trailyy** [comment]
LGTM!

**Comment by Shuvi-Moro** [comment]
yep it's work

**Comment by trailyy** [comment]
works well, thanks for updating it

**Pull request closed without merging**
