### PR TITLE
update entity.h

### PR DESCRIPTION
**Pull request by VacCatGT**

### CODE REVIEW

**Comment by rosesware** [comment]
For what reason? Game don't update.

**Comment by xAkiraMiura** [comment]
probably related to the 3/3/20 update 5 days ago.

**Comment by designer1337** [comment]
This wrong... Is weapon and is player didn't change

**Comment by ClaudiuHKS** [comment]
You should close this PR, like @designer1337 said, @danielkrupinski has already updated Osiris because of the CS:GO game update and these two game offsets have not changed.

See [8bed464dfd604758812cc5b73603183a39eee7bc](https://github.com/danielkrupinski/Osiris/commit/8bed464dfd604758812cc5b73603183a39eee7bc) for more details.

**Comment by VacCatGT** [comment]
well.. ok i close now cya

**Pull request closed without merging**
