### PR TITLE
Added progress bars to Misc::drawBombTimer() for the Explosion time and Defuse time.

### PR DESCRIPTION
**Pull request by sambrashaw**

### CODE REVIEW

**Comment by Bywnb** [comment]
Thank you very much for implementing my suggestion

**Comment by sambrashaw** [comment]
I did this after sifting through the issues tab trying to find something I could feasibly program with my limited C++ knowledge.

**Comment by Bywnb** [comment]
> I did this after sifting through the issues tab trying to find something I could feasibly program with my limited C++ knowledge.

You've done a good job. Thank you

**Comment by sambrashaw** [comment]
Yeh my friend wanted this when I compiled it for him and forgot to take it out of the commit :)

**Comment by tirziz** [comment]
How to stop the text vibrates when the countdown clock running ? . may be just fix the position of that text

**Comment by Mufinekkk** [comment]
Good

**Comment by sambrashaw** [comment]
A merge for this would be fantastic.

**Comment by sambrashaw** [comment]
@danielkrupinski can you pls merge this

**Comment by danielkrupinski** [comment]
Thanks for your contribution!

**Pull request merged**
