### PR TITLE
Team based player models

### PR DESCRIPTION
**Pull request by MinecraftGoodGame**
Ability to have different player models on different teams. Simple as that.

### CODE REVIEW

**Comment by rosesware** [comment]
Interesting, but at the same time unnecessary.
Well, nice work. 👍

**Comment by Straightplus** [comment]
maybe for skinchanger?

**Comment by Straightplus** [comment]
Pretty good find :D

**Comment by anonymouschicken1111** [comment]
@roseware might be useless to you but maybe not for others

**Comment by danielkrupinski** [comment]
Thank you! I'd be great to also set model for player ragdoll (body falling on ground) as it reverts to default model.

**Comment by MinecraftGoodGame** [comment]
I don't think there is a way to determine if ragdoll is localplayer, correct me if I'm wrong

**Comment by Straightplus** [comment]
I aproove i actually like this thanks for sharing :D

**Pull request merged**
