### PR TITLE
Standalone Rcs (steel4me)

### PR DESCRIPTION
**Pull request by BapNiel21**
ty for everything in this code steel4me (https://github.com/steel4me/Osiris.git), i'm just making this up to date.

### CODE REVIEW

**Comment by BapNiel21** [comment]
I'm soooo new on github,if i'm making something wrong plz tell me, ty.

**Comment by aljawary** [comment]
duplicate pr delete pls

**Comment by dayz2000** [comment]
but i cant find rcs

**Comment by liucyin** [comment]
uhhh i cant find rcs too

**Comment by FalloutBruhMoments** [comment]
can i hav hlp plz how do i add to original

**Pull request closed without merging**
