### PR TITLE
Bomb timer + Draw aimbot FOV + Custom kill message

### PR DESCRIPTION
**Pull request by NexSqaud**

### CODE REVIEW

**Comment by tirziz** [comment]
Good work 👍

**Comment by danielkrupinski** [comment]
Don't make functions static (Misc.h). Place declaration in header and definition in source file instead.

**Comment by mmnt1337** [comment]
can u update please?

**Comment by mmnt1337** [comment]
> Don't make functions static (Misc.h). Place declaration in header and definition in source file instead.

can u update please?

**Comment by Bywnb** [comment]
daniel could add these functions ,thanks

**Comment by 0xE232FE** [comment]
@NexSqaud: I find it help full to look into this before making BombTimer or something.
Any information you need is wellknown in here. The Offsets are not interesting because they are dynamic but the Names are usefull! Actually I dump all functionnames from the Mac OS Binaries, they include all names we need.

https://raw.githubusercontent.com/iisp33dii/CSGO-Netvar-Class-Dump/master/CompleteDump.txt

best regards

**Comment by NexSqaud** [comment]
@0xE232FE What do you mean?

**Comment by 0xE232FE** [comment]
Getting the actual value of Bombtimer with Netvar **m_flC4Blow** and check if the bomb is planted with **m_bBombTicking** so you get the Bombtimer even if you have disconnect and reconnect into a already running round where the bomb has been planted. Did you get what I mean?

**Comment by NexSqaud** [comment]
But if you join the game when the round starts, you will be dead, will you not?

**Comment by 0xE232FE** [comment]
Yes, I think there are million ways to make a bomb timer. Yours is as fine as mine. And your Bombtimer is working pretty well, I have tested it. Thanks for the commit anyway :-) Everybody will enjoy it! Appreciate!

**Comment by 0xE232FE** [comment]
Additionally if you Enable the Bombtimer after the Bomb is planted, your Bombtimer is not able to show the time. Or when you load Config after planted Bomb. This is on my mind when I use **m_flC4Blow** and **m_bBombTicking**. I just want to help you make your Bombtimer better its no critic on your way just an improvement. Best wishes and thanks for your Commit, I think Daniel is busy atm with Anubis and C Prorgamming ;-)

**Comment by Novalaki** [comment]
Sorry to bump an old post but I'm trying to add the aimbot fov circle and i keep getting a crash when I inject

because of the updates to the cheat since this commit was released I made the fov circle function look like this.

static float actualFov = 0.0f;

	static void drawAimbotFov() noexcept
	{
		auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
		auto activeWeapon = localPlayer->getActiveWeapon();
		if (!config.misc.drawAimbotFov || actualFov == 0.0f || !interfaces.engine->isInGame() || !localPlayer || !localPlayer->getActiveWeapon()) return;
		auto weaponIndex = getWeaponIndex(activeWeapon->itemDefinitionIndex2());
		if (!config.aimbot[weaponIndex].enabled) weaponIndex = 0;
		if (!config.aimbot[weaponIndex].enabled) return;
		auto screenSize = interfaces.surface->getScreenSize();
		if (config.aimbot[weaponIndex].silent) interfaces.surface->setDrawColor(255, 10, 10, 255);
		else interfaces.surface->setDrawColor(10, 255, 10, 255);
		float radius = std::tan(degreesToRadians(config.aimbot[weaponIndex].fov) / 2.f) / std::tan(degreesToRadians(actualFov) / 2.f) * screenSize.first;
		interfaces.surface->drawOutlinedCircle(screenSize.first / 2, screenSize.second / 2, radius, 100);
	}

if anybody can help itd be appreciated!

**Pull request closed without merging**
