### PR TITLE
Auto jumpbug using engine prediction

### PR DESCRIPTION
**Pull request by Vonr**

### CODE REVIEW

**Comment by Vonr** [comment]
this is very borked, do not merge

**Comment by Vonr** [comment]
dont know how to make it better but ill keep trying, did all sorts of weird combinations already. current one seems to be the best yet still broken

**Comment by Vonr** [comment]
closed until i can make it better

**Comment by Cyk-Fad** [comment]
What's jump bug?

**Comment by xAkiraMiura** [comment]
> 
> What's jump bug?

[this](https://lmgtfy.com/?q=csgo+jump+bug)

**Comment by Cyk-Fad** [comment]
> > What's jump bug?
> 
> [this](https://lmgtfy.com/?q=csgo+jump+bug)

Thanks

**Pull request closed without merging**
