### PR TITLE
从零开始加强Osiris

### PR DESCRIPTION
**Pull request by Cyk-Fad**
SlowWalk Update.

### CODE REVIEW

**Comment by Cyk-Fad** [comment]
Just wait a second

**Comment by Cyk-Fad** [comment]
Please enjoy

**Comment by notgoodusename** [comment]
?????????????????????????? this is useless, since osiris already has this feature

**Comment by wirebruh** [comment]
oh my god...

**Comment by wirebruh** [comment]
great, he removed the license file, renamed the solution and added already existing feature

**Pull request closed without merging**
