### PR TITLE
Make thirdperson show cmd->viewangles

### PR DESCRIPTION
**Pull request by DoomFishWasTaken**
Made this into a standalone pull because a lot of people have been requesting this to be a standalone pull.

### CODE REVIEW

**Comment by notgoodusename** [comment]
Can be done easier and showing chocked viewangles wont make the player show your fake, just set it to the last sent viewangle rather than giving the option to the player, and setting the player viewangles to real will show your fake because the model isnt in sync with server animations

**Comment by joshcancode** [comment]
A better way to do this would be to hook EyeAngles and modify the calls to pitch and yaw.

**Comment by notgoodusename** [comment]
> A better way to do this would be to hook EyeAngles and modify the calls to pitch and yaw, it will also allow you to see your desync leaning.

i dont see how a modifying a netvar would make your angles visible.

**Comment by joshcancode** [comment]
> > A better way to do this would be to hook EyeAngles and modify the calls to pitch and yaw, it will also allow you to see your desync leaning.
> 
> i dont see how a modifying a netvar would make your angles visible.

Don't hook the netvar, hook the function.

**Pull request closed without merging**
