### PR TITLE
KnifeBot

### PR DESCRIPTION
**Pull request by MrDumox**
add knifebot

### CODE REVIEW

**Comment by aljawary** [comment]
What?

**Comment by MrDumox** [comment]
> What?

Add KnifeBot to cheat

**Comment by aljawary** [comment]
I cant see the knifebot code

**Comment by senisditron** [comment]
what?

**Comment by AntonDoil** [comment]
XDDD

**Comment by aljawary** [comment]
U should check ur code one more time xd

**Comment by newcommerdontblame** [comment]
wrong source bro

**Comment by techzin** [comment]
Update to the new Osiris ImGui Version

**Comment by mkot2** [comment]
lmao

**Pull request closed without merging**
