### PR TITLE
Osiris Event Log

### PR DESCRIPTION
**Pull request by aoqia194**
Well, it's about that time. #3343 asked. I know this has been done before most likely, but oh well.
I am open to updating, fixing, improving or optimizing my code. Please leave your criticism as constructive and not hateful.

Events that get logged:
player_hurt
player_death
player_falldamage
bomb_planted
bomb_defused
bomb_exploded
bomb_begindefuse

Open for suggestions, criticism, issue reports, etc.
Previews Below!

[Damage Log (Console)](https://i.imgur.com/vYTLyYJ.png)
[Death Log (Console)](https://i.imgur.com/wrt7uaJ.png)
[Fall Damage Log (Console)](https://i.imgur.com/tz2XlOd.png)

[Damage Log (Chat)](https://i.imgur.com/8dwr9i6.png)
[Death Log (Chat)](https://i.imgur.com/S807wPI.png)
[Fall Damage Log (Chat)](https://i.imgur.com/NyZuc2q.png)

### CODE REVIEW

**Comment by Metaphysical1** [comment]
> How do we incorporate this into the master code

1. CTRL + C 
2. CTRL + V

**Comment by skirtsandflirts** [comment]
> 
> 
> > > How do we incorporate this into the master code
> > 
> > 
> > 
> > 1. CTRL + C
> > 2. CTRL + V
> 
> https://gyazo.com/22d5da2ab83624ecb6f1224baf227ee6

Go through all changes I made from the difference between main and my branch (see here)[https://github.com/danielkrupinski/Osiris/pull/3350/files]
Then just copy paste in the files accordingly.

**Comment by hitman2933** [comment]
> > > > How do we incorporate this into the master code
> > > 
> > > 
> > > 
> > > 1. CTRL + C
> > > 2. CTRL + V
> > 
> > 
> > https://gyazo.com/22d5da2ab83624ecb6f1224baf227ee6
> 
> Go through all changes I made from the difference between main and my branch (see here)[https://github.com/[/pull/3350](https://github.com/danielkrupinski/Osiris/pull/3350)/files] Then just copy paste in the files accordingly.

Ok, I found the issue, I wasn't using the misc.h file and that was causing the issues. Assuming there is no RDM, this will be perfect for TTT. Thank you <33

**Comment by skirtsandflirts** [comment]
> 
> 
> > > > > > How do we incorporate this into the master code
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. CTRL + C
> > > > > 2. CTRL + V
> > > > 
> > > > 
> > > > https://gyazo.com/22d5da2ab83624ecb6f1224baf227ee6
> > > 
> > > 
> > > Go through all changes I made from the difference between main and my branch (see here)[https://github.com/[/pull/3350](https://github.com/danielkrupinski/Osiris/pull/3350)/files] Then just copy paste in the files accordingly.
> > 
> > 
> > Ok, I found the issue, I wasn't using the misc.h file and that was causing the issues. Assuming there is no RDM, this will be perfect for TTT. Thank you <33
> 
> Now I'm having this issue. Is there a way you can share the DLL you have? https://streamable.com/u8pe3i

I will do some more testing and see what I can do. I am implementing proper player_falldamage event

**Comment by skirtsandflirts** [comment]
Updated!

**Comment by skirtsandflirts** [comment]
> 
> 
> > > > > > How do we incorporate this into the master code
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. CTRL + C
> > > > > 2. CTRL + V
> > > > 
> > > > 
> > > > https://gyazo.com/22d5da2ab83624ecb6f1224baf227ee6
> > > 
> > > 
> > > Go through all changes I made from the difference between main and my branch (see here)[https://github.com/[/pull/3350](https://github.com/danielkrupinski/Osiris/pull/3350)/files] Then just copy paste in the files accordingly.
> > 
> > 
> > Ok, I found the issue, I wasn't using the misc.h file and that was causing the issues. Assuming there is no RDM, this will be perfect for TTT. Thank you <33
> 
> Now I'm having this issue. Is there a way you can share the DLL you have? https://streamable.com/u8pe3i

It should work for servers with actual players now. Can you try to either download my source or implement my code directly into your source, and then see if that works?

**Comment by Frouk3** [comment]
you can do in the corner one

**Pull request closed without merging**
