### PR TITLE
[useless post] im messing up with printText to make useless skeet.cc-like bar for UI

### PR DESCRIPTION
**Pull request by xpossed-you**
oh also, i make the FPS and PING flags clean

its just for style, it is written on Misc.cpp/watermark() . 
example because im too lazy to post picture :
______________________________________________
osiris                                                    10 fps
                                                          100 ms

### CODE REVIEW

**Comment by effex1337** [comment]
Omg this makes me feel so uncomfortable.

**Comment by xpossed-you** [comment]
> 
> 
> Omg this makes me feel so uncomfortable.

heeheh

**Comment by designer1337** [comment]
imagine printing tons of "_" instead of a line

**Comment by xpossed-you** [comment]
> 
> 
> imagine printing tons of "_" instead of a line

hahah ikr

**Pull request closed without merging**
