### PR TITLE
Add SkinSearch

### PR DESCRIPTION
**Pull request by cailloubr**
SearchEngine by @Cyk-Fad
This can become highly optimized, but i don't know how :/

Cyk-Fad closed the pull, then i make this again to more people can view and improve this code.

### CODE REVIEW

**Comment by 18339256125** [comment]
When I use "One Window", I cannot change the skin of the glove

**Comment by cailloubr** [comment]
> When I use "One Window", I cannot change the skin of the glove

solved

**Comment by 18339256125** [comment]
> > 使用“一个窗口”时，无法更换手套的皮肤
> 
> 解决了

Thats cool

**Comment by 18339256125** [comment]
but is not working

**Comment by cailloubr** [comment]
> but is not working

Remember, this search are CaSe-SeNsItIvE

**Comment by xAkiraMiura** [comment]
you can go through every character and set it to the lowercase variant and then set the input to lowercase aswell.

imo you should make it detect whenever a character changes and then search rather than having to click a button.

**Comment by Cyk-Fad** [comment]
close this , wait I do it better

**Comment by Cyk-Fad** [comment]
Now ver can serch Chinese( UTF-8 )

**Comment by Cyk-Fad** [comment]
close this, thanks, These are junk codes

**Comment by playday3008** [comment]
Now need fix Cyrillic symbols in search
image

**Comment by techprimedev** [comment]
don`t work for me, any skin are showed,

**Comment by Cyk-Fad** [comment]
> Now need fix Cyrillic symbols in search
> image

You can paste codes from other source in SearchEngine,Then using it in GUI.cpp. I'm Chinese, so I add Chinese Search,So Search has many codes about Chinese's pinyin.

**Comment by Cyk-Fad** [comment]
> but is not working

打钱解决 QQ2476159893

**Comment by cailloubr** [comment]
o chupa pica ai pediu pra fechar, vou fazer o que?

Vou fazer o meu, daí posto

**Comment by infinity1211** [comment]
I added this. Now i cannot close other options in the menu (Aimbot,etc) i dont have a "X" in it

**Comment by cailloubr** [comment]
> I added this. Now i cannot close other options in the menu (Aimbot,etc) i dont have a "X" in it

This pull request are closed, try modify popup code.

**Comment by infinity1211** [comment]
> > I added this. Now i cannot close other options in the menu (Aimbot,etc) i dont have a "X" in it
> 
> This pull request are closed, try modify popup code.

Fixed

**Pull request closed without merging**
