### PR TITLE
Draw Aimbot FOV 

### PR DESCRIPTION
**Pull request by agshaidun**
FOV
Very useful for Silent Aim

Based on ZPDMiller

### CODE REVIEW

**Comment by DerLi1** [comment]
I have dont work aim fov. I use u instruction

**Comment by agshaidun** [comment]
Sorry but its not working on "All" category. You need to set on every single weapon

**Comment by DerLi1** [comment]
I dont have fov, in all categories. I dont know fix this

**Comment by agshaidun** [comment]
You mean the 
`Draw Aimbot FOV`
 does not appear?

**Comment by DerLi1** [comment]
Yes, this

**Comment by agshaidun** [comment]
There must be something you did wrong . Try to do it again

**Comment by DerLi1** [comment]
Give, you version Osiris, work fov. Plz

**Comment by agshaidun** [comment]
https://github.com/agshaidun/Osiris

**Comment by DerLi1** [comment]
> https://github.com/agshaidun/Osiris

https://drive.google.com/file/d/1cQb2z2PfBcbyJ1vgwLukl-V7Cue8BxWN/view?usp=sharing
If you can see what I did wrong

**Comment by xAkiraMiura** [comment]
Could you fork the project and commit your changes, im not downloading a rar and uncompressing it when i could just use a web view.

**Comment by DerLi1** [comment]
I dont know what do it

**Comment by DerLi1** [comment]
> Could you fork the project and commit your changes, im not downloading a rar and uncompressing it when i could just use a web view.

https://github.com/DerLi1/Osiris

**Comment by MrSleekZ** [comment]
You fixed where you have to select every weapon for the FOV circle didn't you?

**Comment by MrSleekZ** [comment]
hm k lol

**Pull request closed without merging**
