### PR TITLE
Osiris for Counter-Strike 2

### PR DESCRIPTION
**Pull request by danielkrupinski**
## New GUI built with Panorama
GUI

### HUD
* Bomb Timer - shows time left to detonation and bombsite where the bomb is planted
Bomb Timer
* Defusing Alert - shows remaining time for defusing to end. Green color means the bomb can be defused before explosion, red means it can not.
Defusing Alert
* Preserve My Killfeed - keeps your kills and assists visible on killfeed until the end of the round

### Visuals
* Remove Scope Overlay - removes the black texture and blur when looking though a scope of a sniper rifle

### CODE REVIEW

**Comment by Xsintashi** [comment]
Daniel Goat!

**Comment by ThrowTop** [comment]
Impressive ussage of built in panorama ui

**Comment by nick-laotie** [comment]
Silent self-aim，my love

**Comment by censfr** [comment]
i like the use of the panorama ui but i think there should be an option to hide it of course. Cant wait for ESP.

**Comment by F1tis** [comment]
where is it going to be ready for download :D

**Comment by Xsintashi** [comment]
> where is it going to be ready for download :D

at ur pc if u build it by urself

**Pull request merged**
