### PR TITLE
bunnyhop hitchance

### PR DESCRIPTION
**Pull request by designer1337**
hitchance based (0-100%) legit bunny hop

### CODE REVIEW

**Comment by Bywnb** [comment]
thanks

**Comment by tirziz** [comment]
I think we can add randomly +jump before and after to simulate mouse scroll

**Comment by tirziz** [comment]
Can you make a SMAC free version ?, I add this hitchance and still get banned by smac

**Comment by l0ccy** [comment]
++++++

**Comment by l0ccy** [comment]
how to fix it after getProperty changed in code

**Comment by BlackmanWhite** [comment]
And max bhops in a row too

**Comment by deprale** [comment]
@designer1337 getProperty fix?

**Comment by deXyy999** [comment]
Yes please❤️❤️🤠

**Comment by thomas0aotian** [comment]
New update?
Danial change the bunnyhop function from misc.h to misc.cpp

**Comment by techprimedev** [comment]
Does it still work?

**Comment by Jonizz** [comment]
Would you be able to update this so that it works? Would be appreciated!

**Pull request closed without merging**
