### PR TITLE
Spectator list on other player & local player

### PR DESCRIPTION
**Pull request by agshaidun**
Untitled

Its also work on local player

### CODE REVIEW

**Comment by Shaxzy** [comment]
Why would you need this?
Isn't the whole point of spectator list to know if someone in your team is watching you, so you know if you can go blatant or not without getting kicked?

No hate or anything, I am just curious :) I appreciate pull requests, it's the second best thing on github!

**Comment by agshaidun** [comment]
But it also work on local player when someone spectating D:

**Comment by notgoodusename** [comment]
this is cool

**Comment by Laxybaxy** [comment]
I like it a lot

**Comment by notgoodusename** [comment]
@agshaidun what happened to your vids?

**Comment by unnamed01X** [comment]
@agshaidun 

How to add it into "new" osiris?
it's little bit different, i don't want to broke something

**Pull request closed without merging**
