### PR TITLE
Animation Fix

### PR DESCRIPTION
**Pull request by notgoodusename**
Maybe innaccurate at times, but for legit aa works fine and is enough
The point of an animation fix is to show server hitboxes.

### CODE REVIEW

**Comment by 3Ld4D** [comment]
good job.

**Comment by Cyk-Fad** [comment]
What is Animation ？ For example ?

**Comment by DoomFishWasTaken** [comment]
@notgoodusername good work man, imma go now bash my head on the keyboard to make desync chams with this :)

**Comment by notgoodusename** [comment]
Trying the same, good luck man!

**Comment by Cyk-Fad** [comment]
LNK2001 OMG

**Comment by notgoodusename** [comment]
Remove both listener, pattern 
select add existing file and that should fix your error

**Comment by 3Ld4D** [comment]
@Cyk-Fad you managed to implement search engine and other stuff while u can't even fix linker error.

**Comment by XEDYYY** [comment]
doesn't seem to work, triggers a breakpoint at 

`        assert(newVmt);
` 
¯\_(ツ)_/¯

**Comment by notgoodusename** [comment]
> doesn't seem to work, triggers a breakpoint at
> 
> ` assert(newVmt);`
> 
> ¯_(ツ)_/¯

Do you have this? https://github.com/danielkrupinski/Osiris/commit/abd14654ef993b96ce832f17261fe7dcd6a00fb1

**Comment by XEDYYY** [comment]
> > doesn't seem to work, triggers a breakpoint at
> > ` assert(newVmt);`
> > ¯_(ツ)_/¯
> 
> Do you have this? [abd1465](https://github.com/danielkrupinski/Osiris/commit/abd14654ef993b96ce832f17261fe7dcd6a00fb1)

Apparently I forgot to include that, thanks for the reply, issues are fixed!

**Comment by Cyk-Fad** [comment]
> @Cyk-Fad you managed to implement search engine and other stuff while u can't even fix linker error.

I'm a noob /happy

**Comment by Oly-UK** [comment]
yo did you ever get around to finishing the resolver?

**Comment by notgoodusename** [comment]
> yo did you ever get around to finishing the resolver?

i didnt continue working on it, although i can finish it

**Comment by Oly-UK** [comment]
> i have some code but i am lazy and i want to do work on other things , although i can finish it
it's cool bro, just wondering if you're planning to release it, it looked super useful!

**Comment by notgoodusename** [comment]
> it's cool bro, just wondering if you're planning to release it, it looked super useful!


for hvh, it doesnt hit much , but for legit aa, i would work

**Comment by effex1337** [comment]
image
premium animfix

**Comment by notgoodusename** [comment]
how did u manage that , i mean it isnt a next p2c animfix but how

**Comment by effex1337** [comment]
download compile and run yes?

**Comment by notgoodusename** [comment]
yes, but i mean what did you do to get that, from what i did that can happen when fakeducking

**Comment by notgoodusename** [comment]
also showing lag comp wont show the current server tick rather the old one, so by shothing in 1 tick and then flicking back you wont see the tick when you shot but the tick before that

**Comment by newcommerdontblame** [comment]
Untitled
it says this for me also do u have discord?

**Comment by notgoodusename** [comment]
https://github.com/danielkrupinski/Osiris/commit/efe8d16d0ea5d6e5cd45208a7f3d6ef2ff5526e6

**Comment by notgoodusename** [comment]
bruh

**Comment by notgoodusename** [comment]
omg im stupid bro, i hit the button by accident

**Comment by newcommerdontblame** [comment]
it doesnt work bro can u update ur source file

**Comment by XEDYYY** [comment]
mind sending me your discord?

**Comment by newcommerdontblame** [comment]
> mind sending me your discord?

1lexysexy#7219

**Comment by newcommerdontblame** [comment]
why cant i merge this pull in github desktop

**Comment by wirebruh** [comment]
@notgoodusename please fix it i want to merge it too lol

**Comment by notgoodusename** [comment]
> mind sending me your discord?

didnt see this, srry
sent yours and i will add you

**Comment by notgoodusename** [comment]
#1819

**Pull request closed without merging**
