### PR TITLE
Fake prime

### PR DESCRIPTION
**Pull request by ZerGo0**
Pretty self-explanatory, it fakes the prime status which apparently will show for other in-game, but you will end up in non-prime games.

Preview: https://i.imgur.com/LYTIDgh.gifv

If anyone knows a better place to call it then feel free to tell me, I'm currently calling it in `FrameStage::RENDER_START`.

### CODE REVIEW

**Comment by HackerGeo-sp1ne** [comment]
nice, thank you

**Comment by ifoverload** [comment]
i just tested and working thankyou
can you add like an anti kick with **dispatchUserMessage** stuff

**Comment by agshaidun** [comment]
NICEEEEE MANNNNN!!!

**Comment by xAkiraMiura** [comment]
@ifoverload anti-votes were removed when operation shattered web dropped last month.

**Comment by RadicalRedemption** [comment]
Works for me aswell.

**Comment by danielkrupinski** [comment]
Do other players in lobby see your 'fake prime' status? There is a problem if you unload cheat with 'fake prime' enabled and try to load cheat again, it fails to find pattern because it was changed by patch.

I found an alternative signature:
`fakePrime = findPattern<uint8_t*>(L"client_panorama", "\x17\xF6\x40\x14\x10") - 1;`
where only one byte needs to be patched (`0x74` - original, `0xEB` - patched).

**Comment by ZerGo0** [comment]
> Do other players in lobby see your 'fake prime' status? There is a problem if you unload cheat with 'fake prime' enabled and try to load cheat again, it fails to find pattern because it was changed by patch.

People on UC said that it shows for lobby members as well, I can't confirm it myself tho, I only play on prime accounts. https://www.unknowncheats.me/forum/2631999-post1.html

> I found an alternative signature:
> `fakePrime = findPattern<uint8_t*>(L"client_panorama", "\x17\xF6\x40\x14\x10") - 1;`
> where only one byte needs to be patched (`0x74` - original, `0xEB` - patched).

Tested and changed, thank you very much.

**Comment by anarbmw** [comment]
@ZerGo0 could u send the dll itself?

**Comment by xAkiraMiura** [comment]
`git clone https://github.com/ZerGo0/Osiris.git` and then build it in vs2019

**Comment by ZerGo0** [comment]
> @ZerGo0 could u send the dll itself?

No, not going to do that, it is extremely easy to do it yourself.

**Comment by anarbmw** [comment]
@ZerGo0, dude, come on, my vs just doesn’t wanna work. Please send me the dll.

**Comment by xAkiraMiura** [comment]
what VS version are you using?

open the .SLN file in the clone
change the build type to `x86 release`
ctrl + b or build -> build
go into the osiris folder -> release -> osiris.dll

**Comment by danielkrupinski** [comment]
Thanks!

**Comment by anarbmw** [comment]
@ZerGo0 @xAkiraMiura two errors when I try to build it: MSB8003 and TRK0005

**Comment by VuBrian22** [comment]
@anarbmw It looks like you have the build tools missing. Try reinstalling VS19 or add those packages through the VS Installer.

**Comment by pointydev** [comment]
Now it's been merged this closes #851.

**Pull request merged**
