### PR TITLE
Dead thirdperson

### PR DESCRIPTION
**Pull request by JDeu**
As title says...

### CODE REVIEW

**Comment by xAkiraMiura** [comment]
Is this always on when dead or toggle-able like when alive?

**Comment by JDeu** [comment]
It acts the same as the normal third person apart from you can’t set a distance. There is a slight issue that the player card stays on your screen while spectating, but I haven’t found a fix yet.

**Comment by notgoodusename** [comment]
Where did you get the observermode class i need it for a better spec list

**Comment by xAkiraMiura** [comment]
m_iObserverMode is a integer netvar.
you can use a netvar dumper to get it.

ObserverMode is an enum, not a class.

You could just use int and use `if (observerMode == 4) {}`, works fine, only issue is that they become magic numbers.

**Comment by notgoodusename** [comment]
i want to do a switch like third person first person and free cam

**Comment by TheFantasticLoki** [comment]
If you can get this fixed I'd love to have it added.

**Comment by RyDeem** [comment]
> It acts the same as the normal third person apart from you can’t set a distance. There is a slight issue that the player card stays on your screen while spectating, but I haven’t found a fix yet.

so i got an idea, make the regular thirdperson distance apply when dead aswell here

**Comment by effex1337** [comment]
If the current code for regular thirdperson distance doesn't work then you'll need to use a cvar for it 
cam_idealdist or smthin

**Comment by rosesware** [comment]
It's broken.

**Comment by JDeu** [comment]
> If the current code for regular thirdperson distance doesn't work then you'll need to use a cvar for it
> cam_idealdist or smthin

There is a netvar `m_flObserverChaseDistance` but the max distance is defined to 96.f so can’t really change it to most people’s third person distance.

**Comment by playday3008** [comment]
now we have getObserverMode, sooo, how can I use Dead thirdperson with `localPlayer->getObserverMode()`
bcoz `localPlayer->getObserverMode() = (!config->visuals.thirdpersonKey || isInThirdperson) ? ObsMode::Chase : ObsMode::InEye;` have C2106 error

**Comment by playday3008** [comment]
@JDeu

**Comment by JDeu** [comment]
> now we have getObserverMode, sooo, how can I use Dead thirdperson with `localPlayer->getObserverMode()`
> bcoz `localPlayer->getObserverMode() = (!config->visuals.thirdpersonKey || isInThirdperson) ? ObsMode::Chase : ObsMode::InEye;` have C2106 error

GetObserverMode is a function that returns the enum, not sets. You need to add the netvar `m_iObserverMode`, which allows you to change the current observer mode.

**Comment by playday3008** [comment]
@JDeu ok, and why `OBS_MODE_ROAMING = 7`? bcoz in getObserverMode, `Roaming = 6`
image

**Comment by JDeu** [comment]
> @JDeu ok thanks, and why `OBS_MODE_ROAMING = 7`? bcoz in getObserverMode, `Roaming = 6`
> image

It is 6? the enum starts at index 0

**Pull request closed without merging**
