### PR TITLE
Better colour picker :)

### PR DESCRIPTION
**Pull request by Rainerr123**

### CODE REVIEW

**Comment by R3nzTheCodeGOD** [comment]
can you share a screenshot ?

**Review by danielkrupinski — COMMENTED** [review]
I'm not convinced that it's "better" to have a hue wheel instead of a square picker.

**Comment by nieatty** [comment]
> I'm not convinced that it's "better" to have a hue wheel instead of a square picker.

I prefer the square picker, my 2 cents worth.

**Comment by Smellon69** [comment]
> > @Rainerr123
> > image
> > i dont have enough space on the Rainbow tab can u help me?
> 
> stop fucking pasting and learncpp.com

lmfao

**Pull request closed without merging**
