### PR TITLE
Slightly change bhop & Clock ClanTag

### PR DESCRIPTION
**Pull request by tirziz**
maybe useful for someone.

### CODE REVIEW

**Comment by effex1337** [comment]
Cool stuff!

**Comment by danielkrupinski** [comment]
I've updated bunnyhop in master, it'll be great if you test it with SMAC.

**Comment by tirziz** [comment]
> I've updated bunnyhop in master, it'll be great if you test it with SMAC.

Its work !

**Comment by danielkrupinski** [comment]
Thanks!

**Pull request merged**
