### PR TITLE
Classic Hitmarker

### PR DESCRIPTION
**Pull request by ZerGo0**
Nothing special, just a normal hitmarker, quite surprised that it wasn't a thing yet.

Preview: https://i.imgur.com/6KW4uWp.png

No idea why that shit isn't centered, the calculations should be right, I guess the CS:GO crosshair is scuffed.

I want to add floating and fading damage numbers as well, I'm quite busy tho so yea not going to happen anytime soon I think, sorry.

### CODE REVIEW

**Comment by giangero1** [comment]
image
why u do diz

**Comment by ZerGo0** [comment]
> image
> why u do diz

Fixed.

**Comment by giangero1** [comment]
very nice

**Comment by thomas0aotian** [comment]
Is it 2d?

**Comment by ZerGo0** [comment]
> Is it 2d?

Yea, it's just in the middle of the screen.

**Comment by anonymouschicken1111** [comment]
Made the same shit closed it cuz idk why Daniel ain't adding thus

**Comment by ZerGo0** [comment]
Changed the branch, adding the right one in a second.

**Pull request closed without merging**
