### PR TITLE
Glow Material For Chams

### PR DESCRIPTION
**Pull request by effex1337**
Just a lot cleaner!

### CODE REVIEW

**Comment by effex1337** [comment]
image
image

**Comment by effex1337** [comment]
image
image

**Comment by Chopard** [comment]
WTF?
FDY1aqErZ9E

**Comment by Chopard** [comment]
WTF?
Screenshot_11

**Comment by notgoodusename** [comment]
effex you should try this https://www.unknowncheats.me/forum/counterstrike-global-offensive/337040-dynamic-metallic-chams.html

**Comment by danielkrupinski** [comment]
Great work! @Chopard you have to use glow as a secondary material.

**Comment by effex1337** [comment]
Yes, it's supposed to be used as an overlay, meaning that you need to use a base material then apply glow as a second material.

**Pull request merged**
