### PR TITLE
Magnet TriggerBot/Fix Viewmodel on sg/aug

### PR DESCRIPTION
**Pull request by thomas0aotian**
**Aimlock** on people when **triggerbotting**
settings base on your aimbot settings
basically toggle aimlock when triggerbotting lol
ez and fast xD
傲天认证

### CODE REVIEW

**Comment by Oly-UK** [comment]
epic

**Comment by nothanku** [comment]
@thomas0aotian can u make a fix for the viewmodel fov so it looks like the same viewmodel fov when i spectate people instead of it being zoomed in and looks extremely ugly, since i've changed something that makes my viewmodel go more out when i zoom

**Comment by igothxps** [comment]
@thomas0aotian it doesnt shoot for me even with max fov

**Comment by xAkiraMiura** [comment]
Useless PR, this is already in Osiris.

1. Set the **aimbot** on key to be the same as the **trigger bot** on key (this causes it to turn on when the trigger bot turns on)
2. Disable silent aim on **aimbot** (this causes you to see the aimbot)
3. Enable aimlock on **aimbot** (this causes it to lock on even when not shooting)
4. Set the **aimbot** FOV to be the magnet range

**Comment by thomas0aotian** [comment]
@xAkiraMiura I had a complete magnet triggerbot on my paste but I'm posting it out atm

**Comment by xAkiraMiura** [comment]
if you havent noticed you have an open pull still. anyone watching the repo gets notifications for this.
nice ego you got there :)

**Pull request closed without merging**
