### PR TITLE
Aimbot and Triggerbot activated by 2 selectable keys

### PR DESCRIPTION
**Pull request by Asviix**
You can now activate aimbot with key A or B
Same with the Triggerbot

### CODE REVIEW

**Comment by Asviix** [comment]
Found some bugs, will push an update soon

**Comment by thomas0aotian** [comment]
'So usefull'

**Comment by Asviix** [comment]
@thomas0aotian I needed this for personal use but still wanted to make the community profit from it if they find it useful.

**Comment by xAkiraMiura** [comment]
> 
> 
> 'So usefull'

magnet trigger bot paste very useful as well

**Comment by Asviix** [comment]
lmao yikes imagine using pastes

**Pull request closed without merging**
