### PR TITLE
Autostrafe fix?

### PR DESCRIPTION
**Pull request by daisuki333**
I believe some values for the autostrafe were not right, and i feel this change fixes autostrafe cause it was kind of wonky before

### CODE REVIEW

**Comment by ClaudiuHKS** [comment]
Thanks!

**Comment by xAkiraMiura** [comment]
i think the original purpose of the delta check was to not make the autostrafe too smooth and have VACnet determine it was a robot rather than somebody pressing the keys themself, if you havent encountered any vac auths or bans while using the change then the original purpose is probably obsolete.

**Comment by daisuki333** [comment]
> i think the original purpose of the delta check was to not make the autostrafe too smooth and have VACnet determine it was a robot rather than somebody pressing the keys themself, if you havent encountered any vac auths or bans while using the change then the original purpose is probably obsolete.

I mean i'm kind of new to c++ in a way which kind of makes me question if i'm right or wrong, but like i haven't necessarily gotten any vac auth errors, if i am wrong and people do get then, i apologise.

**Comment by notgoodusename** [comment]
i dont think you can get vac auth from a legit autostrafe, like vac auth comes when you flick alot on casual,deathmatch,etc

**Comment by xAkiraMiura** [comment]
valve probably isn't smart enough to check if your velocity always follows your view angle but if they are the slightest bit competent then it could become a detection vector in the future.

**Comment by danielkrupinski** [comment]
It was done to not strafe while jumping on box but it seems velocity check would be better.

**Pull request merged**
