### PR TITLE
ViewModel XYZ Changer

### PR DESCRIPTION
**Pull request by blackMasterLord**

### CODE REVIEW

**Comment by KurastikO** [comment]
even without osiris my viewmodel commands are messed up.

there's no limit anymore and I can't adjust it properly, dunno why that happens but howwww

**Comment by wemanzoz** [comment]
@blackMasterLord it would be better if we have an option to turn off/on xyz since it overrides your viewmodel in game even without changing a single setting

**Comment by wemanzoz** [comment]
also it stutters your gun for some reason, (when moving left and right)

**Comment by wemanzoz** [comment]
@blackMasterLord please add a checkbox that can make this feature off and on

**Comment by blackMasterLord** [comment]
> @blackMasterLord please add a checkbox that can make this feature off and on

it's done.
i think.

**Comment by xomarko** [comment]
when i enable its so zoomed in lol

**Comment by xomarko** [comment]
image

**Pull request closed without merging**
