### PR TITLE
Added bomb damage indicator

### PR DESCRIPTION
**Pull request by Laxybaxy**
predicts bomb damage based on armor value and position from bomb.

its positioned in bottom right corner, kinda hard to spot but ye

video: https://youtu.be/8nHfuEH7840

Thanks to Casual_Hacker from UC

### CODE REVIEW

**Comment by KernCS** [comment]
Nice GJ!

**Comment by RyDeem** [comment]
Nice work man.

id like it to be integrated into bomb timer tho, at the same location about on the middle top screen.
as players using this cheat are accustomed to check the bomb timer spot on bomb info, and checking further away is a bit of a chore xd

For the the timer is at top right not bottom right as you show. but i did not change any code, so im confused how the code works, but fun to see how and what you did it for my own projects.

**Comment by Laxybaxy** [comment]
@RyDeem done.

**Comment by RyDeem** [comment]
i do belive you need to change drawPositionY to drawPositionDamageY for compatability in code after where you placed yours, because of conflicting names, it did not build with just this
``            auto drawPositionDamageY{ interfaces.surface->getScreenSize().second / 10 };
            interfaces.surface->setTextPosition(bombDmgX, drawPositionDamageY);
            interfaces.surface->printText(bombDmgText.c_str());

            drawPositionDamageY += interfaces.surface->getTextSize(font, bombDmgText.c_str()).second;``

**Comment by RyDeem** [comment]
i do belive you need to change drawPositionY to drawPositionDamageY for compatability in code after where you placed yours, because of conflicting names,
 it did not build with just drawPositionY

on my branch i changed it to drawPositionDamageY and it worked, could be the fix? idk, does your build? maybe im out of sync, or maybe your branch is? 
```
auto drawPositionDamageY{ interfaces.surface->getScreenSize().second / 10 };
interfaces.surface->setTextPosition(bombDmgX, drawPositionDamageY);
interfaces.surface->printText(bombDmgText.c_str());

        drawPositionDamageY += interfaces.surface->getTextSize(font, bombDmgText.c_str()).second;
```

**Comment by RyDeem** [comment]
you could change the code to say health left instead of damage taken, for easy spotting of how much will be left with no in head multiplication.

`            auto bombDmgText{ (std::wstringstream{ } << L"Health after explosion:  " << localPlayer->health()-bombDamage).str() };`

localPlayer->health()-bombDamage
original:
bombDamage

and changed string to Health after explosion:  
(with a extra space for seeing the number better?)

What do you think?

**Comment by Laxybaxy** [comment]
You do it. @RyDeem

**Comment by RyDeem** [comment]
> You do it. @RyDeem

ok, you dont want feedback,i understand.

Rye out.

(i did do it in my branch, or whatever its called)
I think i keep mistaking github for a place to forum and do stuff like talking and discussing, but i guess its all business and stuff.

**Comment by Laxybaxy** [comment]
@RyDeem it was only a sugestion, i make it how i would like it to be and then, if you want to personalise the hud, you are free to do so :D

**Pull request closed without merging**
