### PR TITLE
Edgebug

### PR DESCRIPTION
**Pull request by csgofever**
(pasted)

### CODE REVIEW

**Comment by Patrixsin** [comment]
Didn't u forget call this in Hooks.cpp?

**Comment by Yoka1998** [comment]
Is it working?

**Comment by csgofever** [comment]
Yeah my bad I forgot to call it in hooks I’ll fix it later

**Comment by csgofever** [comment]
And yes it is working but I forgot to call it in hooks

**Comment by csgofever** [comment]
wait no i did call it in hooks

**Comment by csgofever** [comment]
fixed

**Comment by convict-real** [comment]
how do i make it not crouch?

**Comment by csgofever** [comment]
its supposed to crouch

**Comment by Yoka1998** [comment]
Thank you mate,
Also could you please make jumpbug and movement graph please?

**Comment by mezleca** [comment]
> Thank you mate, Also could you please make jumpbug and movement graph please?

just paste from this repo https://github.com/xeyay/Elter-Hook

**Comment by Skroomy** [comment]
yo this works only on specific surfaces, does anyone know a fix?

**Comment by Shuvi-Moro** [comment]
thnx

**Comment by wirekuro** [comment]
@csgofever update pls

**Comment by JukoiDev** [comment]
lmao it's bad

**Pull request closed without merging**
