### PR TITLE
Hitmarker Damage Indicator

### PR DESCRIPTION
**Pull request by ZerGo0**
Hey guys,

I just added a Hitmarker Damage Indicator to it: https://i.imgur.com/oXKKZq6.gifv

I hope that I didn't miss anything.

### CODE REVIEW

**Comment by AbdallahMehiz** [comment]
FINALLY
Some good fuc**ng FEATURES
TY BRO

**Comment by agshaidun** [comment]
😎😎😎

**Comment by ZerGo0** [comment]
> building this when merged to the master repository results in Error C2027 due to use of undefined type 'Surface' Osiris C:\Path\Repository_Name\Osiris\Hacks\Visuals.cpp at line 275, this is not the only instance

Missed a include in the Visual.cpp, updated the file.

**Comment by GA9BR** [comment]
Man i have one problem, look: 
Screenshot_1 
no matching token found
Can you help me ? 
my code 

#include "../fnv.h"
#include "Visuals.h"

#include "../SDK/ConVar.h"
#include "../SDK/Entity.h"
#include "../SDK/FrameStage.h"
#include "../SDK/GameEvent.h"
#include "../SDK/GlobalVars.h"
#include "../SDK/Input.h"
#include "../SDK/Material.h"
#include "../SDK/MaterialSystem.h"
#include "../SDK/RenderContext.h"
#include "../SDK/Surface.h"
#include "../SDK/ModelInfo.h"

#include <array>

void Visuals::playerModel(FrameStage stage) noexcept
{
    if (stage != FrameStage::NET_UPDATE_POSTDATAUPDATE_START)
        return;

    const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
    if (!localPlayer)
        return;

    constexpr auto getModel = [](int team) constexpr noexcept -> const char* {
        constexpr std::array models{
        "models/player/custom_player/legacy/ctm_fbi_variantb.mdl",
        "models/player/custom_player/legacy/ctm_fbi_variantf.mdl",
        "models/player/custom_player/legacy/ctm_fbi_variantg.mdl",
        "models/player/custom_player/legacy/ctm_fbi_varianth.mdl",
        "models/player/custom_player/legacy/ctm_sas_variantf.mdl",
        "models/player/custom_player/legacy/ctm_st6_variante.mdl",
        "models/player/custom_player/legacy/ctm_st6_variantg.mdl",
        "models/player/custom_player/legacy/ctm_st6_varianti.mdl",
        "models/player/custom_player/legacy/ctm_st6_variantk.mdl",
        "models/player/custom_player/legacy/ctm_st6_variantm.mdl",
        "models/player/custom_player/legacy/tm_balkan_variantf.mdl",
        "models/player/custom_player/legacy/tm_balkan_variantg.mdl",
        "models/player/custom_player/legacy/tm_balkan_varianth.mdl",
        "models/player/custom_player/legacy/tm_balkan_varianti.mdl",
        "models/player/custom_player/legacy/tm_balkan_variantj.mdl",
        "models/player/custom_player/legacy/tm_leet_variantf.mdl",
        "models/player/custom_player/legacy/tm_leet_variantg.mdl",
        "models/player/custom_player/legacy/tm_leet_varianth.mdl",
        "models/player/custom_player/legacy/tm_leet_varianti.mdl",
        "models/player/custom_player/legacy/tm_phoenix_variantf.mdl",
        "models/player/custom_player/legacy/tm_phoenix_variantg.mdl",
        "models/player/custom_player/legacy/tm_phoenix_varianth.mdl"
        };

        switch (team) {
        case 2: return config.visuals.playerModelT > 0 && config.visuals.playerModelT <= models.size() ? models[config.visuals.playerModelT - 1] : nullptr;
        case 3: return config.visuals.playerModelCT > 0 && config.visuals.playerModelCT <= models.size() ? models[config.visuals.playerModelCT - 1] : nullptr;
        default: return nullptr;
        }
    };

    if (const auto model = getModel(localPlayer->team())) {
        const auto idx = interfaces.modelInfo->getModelIndex(model);
        localPlayer->setModelIndex(idx);

        if (const auto ragdoll = interfaces.entityList->getEntityFromHandle(localPlayer->ragdoll()))
            ragdoll->setModelIndex(idx);
    }
}

void Visuals::colorWorld() noexcept
{
    for (short h = interfaces.materialSystem->firstMaterial(); h != interfaces.materialSystem->invalidMaterial(); h = interfaces.materialSystem->nextMaterial(h)) {
        if (Material* mat = interfaces.materialSystem->getMaterial(h); mat && mat->isPrecached()) {
            if (config.visuals.world.enabled && std::strstr(mat->getTextureGroupName(), "World")) {
                if (config.visuals.world.rainbow)
                    mat->colorModulate(rainbowColor(memory.globalVars->realtime, config.visuals.world.rainbowSpeed));
                else
                    mat->colorModulate(config.visuals.world.color);
            } else if (config.visuals.sky.enabled && std::strstr(mat->getTextureGroupName(), "SkyBox")) {
                if (config.visuals.sky.rainbow)
                    mat->colorModulate(rainbowColor(memory.globalVars->realtime, config.visuals.sky.rainbowSpeed));
                else
                    mat->colorModulate(config.visuals.sky.color);
            }
        }
    }
}

void Visuals::modifySmoke() noexcept
{
    static constexpr const char* smokeMaterials[]{
        "particle/vistasmokev1/vistasmokev1_emods",
        "particle/vistasmokev1/vistasmokev1_emods_impactdust",
        "particle/vistasmokev1/vistasmokev1_fire",
        "particle/vistasmokev1/vistasmokev1_smokegrenade",
    };

    for (const auto mat : smokeMaterials) {
        auto material = interfaces.materialSystem->findMaterial(mat);
        material->setMaterialVarFlag(MaterialVarFlag::NO_DRAW, config.visuals.noSmoke);
        material->setMaterialVarFlag(MaterialVarFlag::WIREFRAME, config.visuals.wireframeSmoke);
    }

    if (config.visuals.noSmoke || config.visuals.wireframeSmoke)
        *memory.smokeCount = 0;
}

void Visuals::thirdperson() noexcept
{
    static bool isInThirdperson{ true };
    static float lastTime{ 0.0f };

    if (GetAsyncKeyState(config.visuals.thirdpersonKey) && memory.globalVars->realtime - lastTime > 0.5f) {
        isInThirdperson = !isInThirdperson;
        lastTime = memory.globalVars->realtime;
    }

    if (config.visuals.thirdperson)
        if (memory.input->isCameraInThirdPerson = (!config.visuals.thirdpersonKey || isInThirdperson)
            && interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->isAlive())
            memory.input->cameraOffset.z = static_cast<float>(config.visuals.thirdpersonDistance);
}

void Visuals::removeVisualRecoil(FrameStage stage) noexcept
{
    static Vector aimPunch;
    static Vector viewPunch;
    auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
    if (stage == FrameStage::RENDER_START) {
        aimPunch = localPlayer->aimPunchAngle();
        viewPunch = localPlayer->viewPunchAngle();

        if (config.visuals.noAimPunch && !config.misc.recoilCrosshair)
            localPlayer->aimPunchAngle() = Vector{ };

        if (config.visuals.noViewPunch)
            localPlayer->viewPunchAngle() = Vector{ };

    } else if (stage == FrameStage::RENDER_END) {
        localPlayer->aimPunchAngle() = aimPunch;
        localPlayer->viewPunchAngle() = viewPunch;
    }
}

void Visuals::removeBlur() noexcept
{
    static auto blur = interfaces.materialSystem->findMaterial("dev/scope_bluroverlay");
    blur->setMaterialVarFlag(MaterialVarFlag::NO_DRAW, config.visuals.noBlur);
}

void Visuals::updateBrightness() noexcept
{
    static auto brightness = interfaces.cvar->findVar("mat_force_tonemap_scale");
    brightness->setValue(config.visuals.brightness);
}

void Visuals::removeGrass() noexcept
{
    constexpr auto getGrassMaterialName = []() constexpr noexcept -> const char* {
        switch (fnv::hashRuntime(interfaces.engine->getLevelName())) {
        case fnv::hash("dz_blacksite"): return "detail/detailsprites_survival";
        case fnv::hash("dz_sirocco"): return "detail/dust_massive_detail_sprites";
        case fnv::hash("dz_junglety"): return "detail/tropical_grass";
        default: return nullptr;
        }
    };

    if (const auto grassMaterialName = getGrassMaterialName())
        interfaces.materialSystem->findMaterial(grassMaterialName)->setMaterialVarFlag(MaterialVarFlag::NO_DRAW, config.visuals.noGrass);
}

void Visuals::remove3dSky() noexcept
{
    static auto sky = interfaces.cvar->findVar("r_3dsky");
    sky->setValue(!config.visuals.no3dSky);
}

void Visuals::removeShadows() noexcept
{
    static auto shadows = interfaces.cvar->findVar("cl_csm_enabled");
    shadows->setValue(!config.visuals.noShadows);
}

void Visuals::applyZoom(FrameStage stage) noexcept
{
    if (config.visuals.zoom) {
        auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
        if (stage == FrameStage::RENDER_START && localPlayer && (localPlayer->fov() == 90 || localPlayer->fovStart() == 90)) {
            static bool scoped{ false };

            if (GetAsyncKeyState(config.visuals.zoomKey) & 1)
                scoped = !scoped;

            if (scoped) {
                localPlayer->fov() = 40;
                localPlayer->fovStart() = 40;
            }
        }
    }
}

void Visuals::noZoom() noexcept
{
    if (config.visuals.noZoom) {
        auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
        if (localPlayer && localPlayer->isScoped()) {
            localPlayer->fov() = 90 + config.visuals.fov;
            localPlayer->fovStart() = 90 + config.visuals.fov;
        }
    }
}

static __declspec(naked) void drawScreenEffectMaterial(Material* material, int x, int y, int width, int height) noexcept
{
    __asm {
        push ebp
        mov ebp, esp
        push height
        push width
        push y
        mov edx, x
        mov ecx, material
        call memory.drawScreenEffectMaterial
        mov esp, ebp
        pop ebp
        ret
    }
}

void Visuals::applyScreenEffects() noexcept
{
    if (config.visuals.screenEffect) {
        constexpr auto getEffectMaterial = [] {
            static constexpr const char* effects[]{
            "effects/dronecam",
            "effects/underwater_overlay",
            "effects/healthboost",
            "effects/dangerzone_screen"
            };

            if (config.visuals.screenEffect <= 2)
                return effects[0];
            return effects[config.visuals.screenEffect - 2];
        };

        auto renderContext = interfaces.materialSystem->getRenderContext();
        renderContext->beginRender();
        int x, y, width, height;
        renderContext->getViewport(x, y, width, height);
        auto material = interfaces.materialSystem->findMaterial(getEffectMaterial());
        if (config.visuals.screenEffect == 1)
            material->findVar("$c0_x")->setValue(0.0f);
        else if (config.visuals.screenEffect == 2)
            material->findVar("$c0_x")->setValue(0.1f);
        else if (config.visuals.screenEffect >= 4)
            material->findVar("$c0_x")->setValue(1.0f);
        drawScreenEffectMaterial(material, 0, 0, width, height);
        renderContext->endRender();
        renderContext->release();
    }
}

void Visuals::hitMarker(GameEvent* event) noexcept
{
    if (config.visuals.hitMarker) {
        static float lastHitTime = 0.0f;

        if (event && interfaces.engine->getPlayerForUserID(event->getInt("attacker")) == interfaces.engine->getLocalPlayer()) {
            lastHitTime = memory.globalVars->realtime;
            return;
        }

        if (lastHitTime + config.visuals.hitMarkerTime >= memory.globalVars->realtime) {
            if (config.visuals.hitMarker > 0 && config.visuals.hitMarker < 6) {
                constexpr auto getEffectMaterial = [] {
                    static constexpr const char* effects[]{
                    "effects/dronecam",
                    "effects/underwater_overlay",
                    "effects/healthboost",
                    "effects/dangerzone_screen"
                    };

                    if (config.visuals.hitMarker <= 2)
                        return effects[0];
                    return effects[config.visuals.hitMarker - 2];
                    constexpr auto getEffectMaterial = [] {
                        static constexpr const char* effects[]{
                        "effects/dronecam",
                        "effects/underwater_overlay",
                        "effects/healthboost",
                        "effects/dangerzone_screen"
                        };

                        if (config.visuals.hitMarker <= 2)
                            return effects[0];
                        return effects[config.visuals.hitMarker - 2];
                    };

                    auto renderContext = interfaces.materialSystem->getRenderContext();
                    renderContext->beginRender();
                    int x, y, width, height;
                    renderContext->getViewport(x, y, width, height);
                    auto material = interfaces.materialSystem->findMaterial(getEffectMaterial());
                    if (config.visuals.hitMarker == 1)
                        material->findVar("$c0_x")->setValue(0.0f);
                    else if (config.visuals.hitMarker == 2)
                        material->findVar("$c0_x")->setValue(0.1f);
                    else if (config.visuals.hitMarker >= 4)
                        material->findVar("$c0_x")->setValue(1.0f);
                    drawScreenEffectMaterial(material, 0, 0, width, height);
                    renderContext->endRender();
                    renderContext->release();
                };
            }
        }
    }

        void Visuals::hitMarkerSetDamageIndicator(GameEvent * event) noexcept;
        {
            if (config.visuals.hitMarkerDamageIndicator)
            {
                if (event && interfaces.engine->getPlayerForUserID(event->getInt("attacker")) == interfaces.engine->getLocalPlayer()) {
                    hitMarkerInfo.push_back({ memory.globalVars->realtime + config.visuals.hitMarkerTime, event->getInt("dmg_health") });
                }
            }
        }

        void Visuals::hitMarkerDamageIndicator() noexcept;
        {
            if (config.visuals.hitMarkerDamageIndicator)
            {
                if (hitMarkerInfo.empty()) return;

                const auto [width, height] = interfaces.surface->getScreenSize();

                for (size_t i = 0; i < hitMarkerInfo.size(); i++)
                {
                    const auto diff = hitMarkerInfo.at(i).hitMarkerExpTime - memory.globalVars->realtime;

                    if (diff < 0.f)
                    {
                        hitMarkerInfo.erase(hitMarkerInfo.begin() + i);
                        continue;
                    }

                    const auto dist = 24;
                    const auto ratio = 1.f - diff / 0.8f;
                    const auto alpha = diff * 255;

                    const auto font_id = 17;
                    interfaces.surface->setTextFont(font_id);
                    interfaces.surface->setTextPosition(width / 2 + 6 + ratio * dist / 2, height / 2 + 6 + ratio * dist);
                    interfaces.surface->setTextColor(255, 255, 255, alpha);
                    interfaces.surface->printText(std::to_wstring(hitMarkerInfo.at(i).hitMarkerDmg));
                }
            }
        }

**Comment by xAkiraMiura** [comment]
# google.com
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1075?view=vs-2019
https://stackoverflow.com/questions/2672495/fatal-error-c1075-end-of-file-found-before-the-left-brace-and-read-and-write-fi

please upload your code to pastebin, hastebin, or some other service, its impossible to read when half of the code isnt even in a code block and takes up 12 screens of height.

**Comment by GA9BR** [comment]
https://pastebin.com/3ssJcxn4

**Comment by ZerGo0** [comment]
> https://pastebin.com/3ssJcxn4

You are missing a "}" at line 315. The fact that you had to ask for this is just sad, there is no faith for you.

**Comment by GA9BR** [comment]
Osiris is only showing the damange, its dont showing the hitmarker 
Screenshot_1

**Comment by ZerGo0** [comment]
> Osiris is only showing the damange, its dont showing the hitmarker
> Screenshot_1

That's because this is only the indicator like the title says, the actual hitmarker is in another pull request...

**Comment by GA9BR** [comment]
thank you ^^, more can i  enable and unable this feature in middle game ? can i off or on the damange in middle game?

**Comment by danielkrupinski** [comment]
Please merge those two functions into single one. No need to expose the vector in the header file.

**Comment by ZerGo0** [comment]
Updated and fixed everything should be all good now

**Comment by Or3nges** [comment]
i'm having errors, since this pull request is pretty old.
image

**Comment by DoctorYasin** [comment]
where's the switch to turn it off completely?

bro fix?
```
Visuals.cpp(378,120): warning C4805: '==' : Mix of 'T' type and 'Type' unsafe in operation
        with
        [
            T=int
        ]
        and
        [
            T=bool
        ]

>> 	if (event && interfaces->engine->getPlayerForUserID(event->getInt("attacker")) == interfaces->engine->getLocalPlayer())
```

**Comment by squizzyv9** [comment]
Please update latest osiris.

**Pull request closed without merging**
