### PR TITLE
Update imgui library

### PR DESCRIPTION
**Pull request by yEsPaP**
Update imgui to 1.72 WiP + use fnv1a hashing. All fixes made by daniel are applied so just needs to be merged

### CODE REVIEW

**Comment by yEsPaP** [comment]
Damn hes not gonna merge it :(

**Comment by Primeknight19** [comment]
lolz

**Comment by yEsPaP** [comment]
> lolz

why

**Comment by Primeknight19** [comment]
just wait he will merge it maybe

**Comment by danielkrupinski** [comment]
Looks like you changed indentation of some files, it should be corrected. I think you forgot about custom checkmark in imgui_widgets.cpp.

**Comment by yEsPaP** [comment]
> Looks like you changed indentation of some files, it should be corrected. I think you forgot about custom checkmark in imgui_widgets.cpp.

Oof looks like i did wait.

**Pull request closed without merging**
