### PR TITLE
Skinsearch [ Better ]

### PR DESCRIPTION
**Pull request by Cyk-Fad**
-Can Search Chinese And English

-Auto Search ----When you input each word

-Please Enjoy

### CODE REVIEW

**Comment by Cyk-Fad** [comment]
各位国人好 此次发布一个皮肤搜索
任何不懂的问题 / 不会复制到自己源码上的
可以加我QQ 2476159893 只在周末在线
我是学生 谢谢支持

**Comment by aljawary** [comment]
thx man good work

**Comment by cailloubr** [comment]
> > Good job!
> > Would it be possible to remove the "CaSe-SenSiTiVe"?
> 
> yes by changing both skin name and search to lower/upper case

Yes, but in pull.

**Comment by tirziz** [comment]
nice work there

**Comment by Cyk-Fad** [comment]
Wait some hours, I'll delete something

**Comment by Cyk-Fad** [comment]
I'll delete the chinese search because I think you don't need it

**Comment by techzin** [comment]
How to resize listbox? high and width

**Comment by Cyk-Fad** [comment]
> 如果列表框为空，则单击“应用”按钮时崩溃。（obs->仅在调试模式下）



> Crashing on Click in Apply button if listbox has empty. (obs -> Only in Debug Mode)

Add a search check (bool)

**Comment by cailloubr** [comment]
Why? '-'

**Comment by Cyk-Fad** [comment]
> Why? '-'

All right

**Comment by xdNub** [comment]
idk if its only me or what, but the search doesn't work let's say i search "fade" then it will pick the first skin that got fade in the [Video](https://youtu.be/Vm3nBBimV1E)

**Comment by caiocinel** [comment]
Check my "BRCheats-CS" repository, I had this same issue as you.

>

**Comment by senisditron** [comment]
thanks works great <3

**Pull request closed without merging**
