### PR TITLE
Standalone RCS with ignore shots

### PR DESCRIPTION
**Pull request by steel4me**
Standalone RCS with ignore shots, integrated with aimbot. 

I found many requests / suggestions for this on issue tab. I had a free hour and i like to share it with everyone to optimize it.

Activation is depending on enabled Aimbot, Recoil control x and y and checkbox Standalone RCS.
Ignore shots 0 means RCS is fully active on first shot, to make it look more legit you should set this at least to ignore 1 shot, if you do some single shots sometimes ;)

**This commit is still for testing purposes**. Added Code should be clean / fine.
@danielkrupinski , as far as i know, i don't have to normalize / clamp angles for aimpunch. Is this correct? If not, please give me some hints.

**Don't use it online till daniel has confirmed pull request.**

Have fun!

### CODE REVIEW

**Comment by tirziz** [comment]
nice, gonna see it when I get home

**Comment by steel4me** [comment]
> nice, gonna see it when I get home

yes, cool, give me feedback. i tested a bit around, it was very stronk ;)

**Comment by NNiX1** [comment]
working perfectly great job buddy :)

**Comment by steel4me** [comment]
> working perfectly great job buddy :)

thx for info! i just did 4 competetives without problems, lets see if all is fine / save. hopefully daniel can soonly doublecheck.

**Comment by NNiX1** [comment]
found a thing ingore shots not saving at all ( tryed it without my modifications and tryed making brand new config)

**Comment by steel4me** [comment]
> found a thing ingore shots not saving at all ( tryed it without my modifications and tryed making brand new config)

okay, thx for feedback, will fix this this weekend!

**Comment by thomas0aotian** [comment]
I found where the problem is ima go study it.

**Comment by steel4me** [comment]
> I found where the problem is ima go study it.

okay, if you find something let me know, i just merged commits for csgo update today, have no time till weekend, cause i have to much shit in RL to sort out...

**Comment by steel4me** [comment]
Fixed...shame on me, watch commit description and changes i think you can laugh out loud...

**Comment by thomas0aotian** [comment]
@steel4me i actually knew it lmao I was looking at it

**Comment by NNiX1** [comment]
no problem buddy i was looking at it for like 20 mins didnt saw it too :D

**Comment by moonm00n** [comment]
shouldn't it be smoothed a bit?

**Comment by steel4me** [comment]
> shouldn't it be smoothed a bit?

for the moment i would leave it native till @danielkrupinski has authorized it. cause im not 100% sure if everything is fine with viewangles and netvar m_iShotsFired. Or, espacially, with checks like isAlive or something. Osiris had no standalone rcs about long time, i don't know why, this is only an example for testing, you should not use it online to avoid VAC ban.

**Comment by steel4me** [comment]
it works fine for me long time now but i have seen many rcs solutions for osiris in other pull requests. somehow @danielkrupinski don't implement it. would be nice to know why and see his optimized standalone rcs solutions soon ;)

**Comment by xAkiraMiura** [comment]
hes working on an rcs? they aren't that hard, just grab the aimpunch netvar, half it, subtract the previous amount and add it to the viewangles.

**Comment by steel4me** [comment]
> hes working on an rcs? they aren't that hard, just grab the aimpunch netvar, half it, subtract the previous amount and add it to the viewangles.

@xAkiraMiura are you kidding me? I know how RCS works, that why i opened this pull request in November 2019, cause i added standalone RCS to aimbot. 

Did you even know what a pull request is? Maybe.
Did you even watched the code? Seems not ;)

Horrible.

**Comment by xAkiraMiura** [comment]
if hes working on an rcs like you said it should take him as long, considering you of all people found it easy.
the reason he didnt accept your pull is probably because of your super long variable names and over use of auto when the type is easily guessable. 

why are you trying to start a fight? i wasn't even commenting about your code in the first place.

fixing your grammar:
*Do you even know what a pull request is?
*Do you even watch the code

**Comment by steel4me** [comment]
first of all thanks for the advice and the grammar correction, my english is not perfect

I definitely don't want to start a fight. it's all a question of interpretation. if you simply write a copy and paste answer that you recently used in an issue case without seeing that I have already done a working rcs, your answer or proposed solution is unprofessional.

This is exactly what you blame others for, unfortunately your answers are not useful.

In addition, i did not directly say that Daniel is working on an RCS, but that it **would** be nice if he will publish an optimized RCS.

> i wasn't even commenting about your code in the first place.

This is exactly what github is there for, reviewing, checking and optimizing code together.

Your only meaningful comment was that I used variables that were too long.

**Comment by xAkiraMiura** [comment]
i wasn't actively contributing back when tirziz made their review so it had nothing to do with me? they haven't commented on this for over 3 months.

**Comment by thomas0aotian** [comment]
@steel4me brother leave him alone he's one of those offensive kids. Just be cool with it.

**Comment by vsnrytune** [comment]
So can you update this to be smooth and more legit? I wanna just add it myself if it wont be added to the main cheat anytime soon

**Comment by xAkiraMiura** [comment]
post has been closed for 2 months, you just necro'd
the original pull is from novemember 2019, chances are they no longer want to maintain the pull.

**Pull request closed without merging**
