### PR TITLE
Cross-platform calculateVmtLength() function

### PR DESCRIPTION
**Pull request by mdilai**
1. Moved calculateVmtLength() function to Helpers.cpp for code reuse
2. Implemented proper calculation for Linux
3. Changed MinHook, VmtHook and VmtSwap to call this function instead of duplicated code in three places.

### CODE REVIEW

**Comment by cristeigabriel** [comment]
Can't we calculate a virtual method table's size just like this?
```
    while (m_original_table[m_table_size] != 0) {
        ++m_table_size;
    }
```

**Review by mkot2 — APPROVED** [review]

**Comment by mkot2** [comment]
> 
> 
> Can't we calculate a virtual method table's size just like this?
> 
> ```
>     while (m_original_table[m_table_size] != 0) {
>         ++m_table_size;
>     }
> ```

if it was that simple why would he do it like this with OS specific things

**Comment by cristeigabriel** [comment]
> > Can't we calculate a virtual method table's size just like this?
> > ```
> >     while (m_original_table[m_table_size] != 0) {
> >         ++m_table_size;
> >     }
> > ```
> 
> if it was that simple why would he do it like this with OS specific things

Yeah, that's what I'm asking, the method I've presented works on my end.

**Comment by mdilai** [comment]
> > > Can't we calculate a virtual method table's size just like this?
> 
> > > ```
> 
> > >     while (m_original_table[m_table_size] != 0) {
> 
> > >         ++m_table_size;
> 
> > >     }
> 
> > > ```
> 
> > 
> 
> > if it was that simple why would he do it like this with OS specific things
> 
> 
> 
> Yeah, that's what I'm asking, the method I've presented works on my end.

To be honest, i am not sure that this is the easiest way to do that and your code _looks_ working too. What i did is ported exactly behavior of Windows code to Linux. Probably this should be more safer way with negligible performance effects, but i am not sure, let Daniel decide the future of this PR. I just was unable to watch this hardcoded variable anymore.

**Review by danielkrupinski — COMMENTED** [review]
The problem is that `mprotect()` creates an additional rwx section:
#### Before injecting
before
#### After
after

**Comment by mdilai** [comment]
@danielkrupinski understand. So lets stick to @cristeigabriel method, it work for me without any issues.

**Review by danielkrupinski — APPROVED** [review]

**Comment by danielkrupinski** [comment]
Thanks!

**Pull request merged**
